export const titulos = [
    'Cristo Jovem',
    'Contrutores de História',
    'Deixa a luz do céu entrar',
    'Deus trino',
    'Emaús(Daniel Ventura e Rodrigo Medeiros)',
    'És água viva',
    'Estandarte',
    'Eu venho do sul e do norte',
    'Fica sempre',
    'Fico feliz',
    'Hoje é tempo de louvar a Deus',
    'Povo de Deus',
    'Oração pela família',
    'Senhor é Rei',
    'Porque ele vive',
    'Quiero cantar',
    'Reunidos aqui',
    'Salmo de la creacion',
    'Senhor, quem entrará?',
    'Vamos adorá-lo(de mãos dadas)',
    'Conheço um coração',
    'Compadece-te',
    'kyrie Eleison',
    'Misericórdia',
    'Pelos pecados',
    'Perdão do Jumas',
    'Perdão Senhor, tantos erros cometi',
    'Renova-me',
    'Senhor, estou aqui',
    'Senhor que vieste salvar',
    'Senhor, tende piedade de nós',
    'Tenho saudade',
    'No mueras hermano',
    'Canto louvores ao Pai',
    'Glória a Deus nas alturas',
    'Glória a Deus nos altos céus',
    'Glória ao Pai criador',
    'Glória, Glória, Glória aleluia(louvemos ao Senhor)',
    'Glória, Glória, Glória, aleluia!',
    'Louvado seja o meu Senhor',
    'Aleluia, a minh’alma eu abrirei',
    'Aleluia, alguém do povo exclama',
    'Aleluia, ao santo evangelho vamos aclamar',
    'Aleluia, Jumas aberto a escutar',
    'Aleluia, quando estamos unidos',
    'Buscai primeiro',
    'Como são belos',
    'Eu vim para escutar',
    'Rendei-lhe a javé',
    'Shemá israel(escuta israel)',
    'Tua palavra é assim',
    'A ti meu Deus',
    'Consagrado para amar',
    'De mãos estendidas',
    'Este pranto(Waldeci Farias e Dom Navarro)',
    'Mãos abertas',
    'Meu coração é para ti',
    'Minha vida tem sentido',
    'Neste altar',
    'Sabes, Senhor',
    'Sobe a Jerusalém(Waldeci Farias e Dom Navarro',
    'Só em ti viver(as coisas...)',
    'Teu som',
    'Um coração para amar(Padre Zezinho)',
    'Venho, Senhor',
    'Vou te oferecer',
    'Senhor é santo',
    'Santo(justo, forte)',
    'Santo, Deus do universo',
    'Santo (dizem todos os anjos)',
    'Santo é(Javé)',
    'A paz esteja contigo',
    'Aperte a minha mão',
    'Paz, paz de Cristo',
    'Quero te dar a Paz',
    'Shalom',
    'Sonho de Paz',
    'Cordeiro de Deus',
    'Cordeiro de Deus(comunidade Shalom)',
    'Cordeiro de Deus 2',
    'Amém',
    'Amém 2',
    'A Barca',
    'Acende uma luz',
    'Alma de Cristo',
    'Amar',
    'Amor sem fim(Julio Fabiano)',
    'A Bíblia é a palavra de Deus',
    'Caminho de eternidade',
    'Cantar a beleza da vida',
    'Cántaro niño(Manu Lopez Naon)',
    'Cenda de Jueves(Manu Lopez Naon)',
    'Como és lindo',
    'Como um niño(P. Enrique Dafonseca',
    'Confía',
    'Cristo, quero ser instrumento(Frei Fabreti, ofm)',
    'De cirene(Manu Lopez Naon)',
    'Déjate',
    'Después de caer(Manu Lopez Naon)',
    'Entrega',
    'El que muere por mi(Francisco Alvarado)',
    'Estas entre nos',
    'Ferro e Fogo',
    'Jesus, alimento que da vida',
    'Jesus estou aqui',
    'Jesus estoy aqui',
    'Joia rara',
    'La Samaritana',
    'Lazaro',
    'Majestosa Eucaristia',
    'Maria de Deus, Senhora da Paz',
    'Mestre',
    'Meu pai',
    'Milagre de Amor',
    'Missão de apóstolo',
    'Ninguem te ama como eu',
    'Pão da vida',
    'No hay amor mas grande',
    'Prova de amor',
    'Quão grande és tu',
    'Sacramento da Comunhão',
    'Salmo 22 - Pelos prados e campinas',
    'Sempre foste tu',
    'Segura na mão de Deus',
    'Sibdo al Simómoro',
    'Te amarei',
    'Tudo é do pai',
    'Vem, e eu mostrarei',
    'Abraço de pai',
    'A ele a glória',
    'A fonte',
    'Basta querer',
    'Diante do Rei',
    'Cristo Rey',
    'Deus é maior',
    'Deus existe',
    'Deus imenso',
    'Em tua presença',
    'Eu sou o que sou',
    'Gratidão',
    'Hoje livre sou',
    'Jesus esta aqui',
    'Jesus super astro',
    'Livre acesso',
    'Não dá mais pra voltar',
    'Noites traiçoeiras',
    'O mistério da trindade',
    'Onde grande é ser pequeno',
    'Pai nosso',
    'Podes reinar',
    'Príncipe da paz',
    'Quem perde sua vida a encontrará',
    'Quero mergulhar',
    'Quiero ser santo',
    'Senhor da vida',
    'Sonda-me',
    'Só por ti, Jesus',
    'Tão sublime sacramento',
    'Te louvo em verdade',
    'Como antes, más que antes',
    'Enviai o vosso espírito senhor - salmo',
    'Eu navegarei',
    'cenáculo',
    'Vuela',
    'A escolhida',
    'Alza mi paz',
    'Aos pés da cruz',
    'Avanza reina',
    'Consagração (Jumas)',
    'Consagração (Jufem)',
    'Eis aí tua mãe',
    'La de Siempre',
    'Madre',
    'Mãe Admirável',
    'Mãe do Homem Novo',
    'Maravilhas',
    'Maria da Aliança',
    'Maria de la Alianza',
    'Maria de Nazaré',
    'Maria e o anjo',
    'María Madre',
    'Marcha del buen viaje',
    'Nuestra Alianza',
    'Perfeito é quem te criou',
    'Quem é esta que avança',
    'Reina de la misión',
    'Hasta que el mundo arda por él',
    'Vem maria vem',
    'Alegria do senhor é a nossa força',
    'A alegria esta no coração',
    'Alma missionária',
    'Ave imperatrix',
    'A viagem',
    'Chuva de graça',
    'Derrame o teu amor aqui',
    'Entregue seu caminho a Deus',
    'Envia-me',
    'Esperando contra toda esperanza',
    'Eu celebrarei',
    'Eu sou de maria',
    'Hino de peregrino',
    'Iê, iê, iê de Jesus',
    'Madre (Remix)',
    'Mar adentro',
    'Misionero',
    'Missão Jovem',
    'Não me canso de caminhar',
    'Novas todas as coisas',
    'O meu lugar é o céu',
    'O nosso general',
    'Senhor tua bondade',
    'Señora de la loma',
    'Solta o cabo da nau',
    'Somos JM, somo iglesia',
    'Tres cosas',
    'Tu és a vencedora',
    'Vamos cantar',
    'Vive o senhor',
    'Aleluia, Cristo Tabor',
    'Algum dia moveremos as montanhas',
    'Canto a Deus pai (Grande é teu carinho)',
    'Alzar banderas',
    'Como fogo nascemos',
    'Contigo caminhar',
    'Duas espadas',
    'Ele amou a Maria',
    'Entrega de amor',
    'En tus manos',
    'Eu só sei te amar',
    'FIAT',
    'Fidelidad',
    'Fiel a missão vem',
    'Filho de Schoenstatt',
    'Fuego de su fuego',
    'Herencia',
    'Heróis de fogo',
    'Hino de Franz Reinisch',
    'Hino da escola de líderes de 1997',
    'Hino dos pioneiros',
    'Jeito de ser',
    'Jumas somos nós',
    'Mãe do nosso tabor',
    'Mãe da aliança',
    'Más allá del mar',
    'Nossa razão de viver',
    'Nova geração',
    'Nuevas Playas',
    'O mundo todo é nosso campo de batalha',
    'Pai fundador',
    'Pego a peregrina',
    'Pioneiro',
    'Providência',
    'Puer et pater',
    'Quero hoje me entregar',
    'Querida MTA',
    'Sé que me escuchas',
    'Sião Multicolor',
    'Stabat',
    'Tu amor',
    'Um aliado',
    'Una llamada de amor',
    'Varone generación',
    'Vem ser feliz',
    'Adeus ano velho',
    'É natal',
    'Glória ao Senhor (Entrada)',
    'Marcas do que se foi',
    'Nasceu-nos hoje (Entrada)',
    'Noite feliz',
    'Vinde, cristão (Glória)'
];
