
export const UnaLlamadaDeAmor = [
  //_________________________________
  'Bm                 F#m',
  'He buscado un hombre nuevo',
  'D               A',
  'Que descubra la misión',
  'F#m                   Bm',
  'Y que en ella encuentre algo',
  'Em               A',
  'El amor del Padre Dios.',
  ' ',
  'Congregante verdadero',
  'En su espada encuentra fuego',
  'Y lucha como un guerrero',
  'Sin importarle el dolor.',
  'G         A             D',
  'Y por ello entrega el corazón.',
  ' ',
  'G              A',
  ' Una llamada de amor',
  '       D    A/C#  Bm',
  'A la espera de un sí',
  'G                   A',
  'Cuando nadie es escuchado',
  'D      A/C#       Bm    G',
  'Y todos somos ignorados',
  'A                     D     B7',
  'Confiamos plenamente en Ti.',
  ' ',
  ' E         B7       C#m     A',
  '//:Aquí estamos dispuestos Padre',
  'Vamos contigo en la batalla',
  'Queremos ser el hombre nuevo',
  'Que tu obra ha logrado reflejar.',
  'En tus manos nos hemos abandonado',
  'En tu corazón hallamos una morada',
  'En tu misión queremos construir',
  'El anhelo de una Tierra Santa://'
];

export const VaronesGeneracion = [
  //_________________________________
  ' Em',
  'Apenas unos pocos,',
  '         Am      Em',
  '¡Varones Generación!',
  '                          E7',
  'ardiendo generosos en las sombras',
  '  Am               Em',
  'para irradiar al mundo su consigna,',
  '  C                     B7',
  'minutos antes de la medianoche.',
  ' ',
  'Revienta un nuevo grito,',
  '¡Varones Generación!',
  'y se abre el corazón a toda América',
  'para asumir del Padre la misión',
  'que ha de partir hacia la nueva orilla.',
  ' ',
  'Refrão:',
  '  E',
  'Para gritarle al mundo que nació',
  '      A',
  'quien ha de ser ejemplo de vivir',
  '  B7          E         C#m',
  'para forjar mañana bajo el sol',
  '  F#m                    B7',
  'pilares de una nueva sociedad.',
  '  E',
  'Para gritarle al mundo que nació',
  '      A',
  'quien ha de ser ejemplo de vivir',
  '  B7          E         C#m',
  'para forjar mañana bajo el sol',
  '  F#m           B7         Em',
  'pilares de una nueva sociedad',
  ' ',
  'Marcando van los rumbos',
  '¡Varones Generación!',
  'y el ritmo mantenido de sus pasos',
  'es la vital canción guerrera que les dio',
  'la Reina que ha de sostener sus brazos.',
  'Y el eco se hace vida ¡Varones Generación!',
  'transforma los santuarios en cuarteles',
  'la aurora que se avecina verá,',
  'marchar legiones de santos y padres.'
];

export const VemSerFeliz = [
  //_________________________________
  'D',
  'Mãe Rainha,',
  'D/F#                  G',
  '  Tu és minha fonte de vida',
  'D/F#   Em                A A4 A',
  'e de esperança. Sou teu filho.',
  'D       D/F#',
  'Meu Jesus me sinto vivo,',
  '        G     D/F#    Em',
  'pois eu sei que estás aqui,',
  '           A A4 A',
  'bem perto de mim',
  ' ',
  'Refrão:',
  'G       A7',
  'E quando me perguntam',
  'D            D7',
  ' como disso eu sei.',
  'G      A7',
  'Eu respondo é simples',
  ' D            D7',
  'é só sentir o amor',
  'G  A7',
  'O amor de Deus',
  '    D              D7 Em',
  'que inunda a nossa vida,',
  '              A',
  'e nos convida: “Vem ser feliz!”',
  ' ',
  'D',
  'Jesus agora sim',
  'D/F#',
  '  posso ouvir o Teu',
  '   G  D/F#   Em',
  'chamado, que me diz:',
  '                   A',
  '“Já não vos chamo servo,',
  '         D D/F#',
  'mas amigo”',
  '     G  A',
  'Meu amigo. Vem comigo!',
  ' ',
  'Refrão:',
  'G        A7',
  'E quando me perguntam',
  'D           D7',
  'como disso eu sei.',
  'G      A7',
  'Eu respondo é simples',
  ' D             D7',
  'é só sentir o amor',
  'G     A7',
  'O amor de Deus',
  '      D            D7',
  'que inunda a nossa vida,',
  'Em          A',
  ' e nos convida: “Vem ser feliz!”'
];

export const AdeusAnoVelho = [
  //_________________________________
  '  E',
  'Adeus ano velho Feliz ano novo',
  '               C#7',
  'Que tudo se realize',
  '                   F#m',
  'no ano que vai nascer',
  '           A       E',
  'Muito dinheiro no bolso',
  '  B7                E',
  'saúde pra dar e vender.'
];

export const ENatal = [
  //_________________________________
  '     E9 A9                  E9  A9',
  'É Natal!  Um menino nos foi dado',
  'E a nós foi revelado',
  '   E9        A9  D7M    B',
  'o plano de amor do Pai',
  '     E9 A9',
  'É Natal!',
  '                     E9   A9',
  'E Jesus se faz se criança',
  '                E9',
  'E em nós a esperança',
  '     A9    B      E9 A9',
  'de reaprender a amar',
  ' ',
  'Refrão:',
  '    E7M(9) A9',
  'É Jesus,',
  '              C#m   A9',
  'o Príncipe da paz,',
  '               E7M(9)   A9',
  'Sinal para os perdidos,',
  '                  D   B',
  'astro que brilha mais.',
  '    E7M(9) A9',
  'É Jesus,',
  '                C#m   A9',
  'mão forte do Senhor,',
  '            E7M(9)',
  'Consolo e ternura.',
  '   A9  B7          E (A9)',
  'Do Pai, olhar de amor'
];

export const GloriaAoSenhor = [
  //_________________________________
  '    A       F#m          D',
  '1. Reis e nações se amotinam',
  '    E           A',
  'e tramam, por quê?',
  '      F#m          D',
  'E vão contra o Senhor',
  '        E          A  D',
  'e o Messias, por quê?',
  ' A     F#m        D          E',
  'Deles se ri e aborrece o Senhor,',
  '       A',
  'e ouvirão:',
  '        F#m        D',
  'Fui eu quem consagrei',
  '       E       A   D   E',
  'o meu rei em Sião!',
  ' ',
  'Refrão:',
  '  A          F#m',
  'Glória ao Senhor,',
  '       D            E',
  'nas alturas sem cessar,',
  '  A          F#m',
  'Glória ao Senhor,',
  '         E          A   (D E)',
  'terra inteira a cantar! (2x)',
  ' ',
  '    A        F#m      D',
  '2. Vou proclamar o decreto',
  '     E         A',
  'que vem do Senhor.',
  '     F#m          D',
  'O que disse o Senhor',
  '     E         A    D',
  'e dizer me mandou:',
  '  A       F#m         D',
  '“Tu és meu filho, meu filho,',
  '       E          A',
  'a Ti, hoje, eu gerei.',
  '      F#m     D',
  'Tu me pedes e eu',
  '      E         A   D  E',
  'as nações te darei!”',
  ' ',
  'Refrão:',
  '  A          F#m',
  'Glória ao Senhor,',
  '       D            E',
  'nas alturas sem cessar,',
  '  A          F#m',
  'Glória ao Senhor,',
  '         E          A   (D E)',
  'terra inteira a cantar! (2x)',
  ' ',
  '    A      F#m         D',
  '3. Cetro de ferro nas mãos,',
  '      E        A',
  'as nações regerás,',
  '        F#m     D',
  'Como um pote de barro',
  '       E     A  D',
  'as despedaçarás!',
  ' A     F#m        D',
  'Reis e juízes da terra,',
  '   E          A',
  'guiar-vos deixai,',
  '      F#m        D',
  'Ao Senhor com temor',
  '       E         A D E',
  'lhe servi e honrai!',
  ' ',
  'Refrão:',
  '  A          F#m',
  'Glória ao Senhor,',
  '       D            E',
  'nas alturas sem cessar,',
  '  A          F#m',
  'Glória ao Senhor,',
  '         E          A   (D E)',
  'terra inteira a cantar! (2x)'
];

export const MarcasDoQueSeFoi = [
  //_________________________________
  'G                 C',
  'Este ano eu quero paz',
  '       D        G',
  'no meu coração',
  'Quem quiser ter um amigo',
  'C             D',
  ' que me dê a mão',
  '        G           C         D',
  'O tempo passa e com ele caminhamos',
  '       G              C',
  'todos juntos sem parar',
  '                     G         D',
  'Nossos passos pelo chão vão ficar.',
  ' ',
  'Refrão:',
  ' G          C     G',
  'Marcas do que se foi,',
  ' D          C     G',
  'sonhos que vamos ter.',
  '               C',
  'Como todo dia nasce novo',
  '    G     D      G',
  'em cada amanhecer. (2x)'
];

export const NasceuNosHoje = [
  //_________________________________
  'Refrão:',
  '           Bm        Em',
  'Nasceu-nos hoje um menino',
  '      F#           Bm',
  'e um Filho nos foi dado',
  '        Bm         Em',
  'Grande é este pequenino.',
  '        F#         Bm',
  'Rei da paz será chamado.',
  '   Em        Bm       F#       Bm',
  'Aleluia, aleluia, aleluia, aleluia (2x)',
  ' ',
  '       Bm      F#       Bm',
  '1. Cantai, cantai ao Senhor',
  'Em       F#           Bm',
  'um canto novo, um louvor!',
  '    Bm  F#         Bm',
  'Por maravilha tão grande,',
  'Em       F#           Bm',
  'um canto novo, um louvor!',
  '    Em              Bm',
  'Por tal vitória e poder,',
  'G       C#7           F#',
  'um canto novo, um louvor!',
  '    Em           Bm',
  'Por um amor tão fiel,',
  'G        F#          Bm',
  'um canto novo, um louvor!',
  ' ',
  'Refrão:',
  '           Bm        Em',
  'Nasceu-nos hoje um menino',
  '      F#           Bm',
  'e um Filho nos foi dado',
  '        Bm         Em',
  'Grande é este pequenino.',
  '        F#         Bm',
  'Rei da paz será chamado.',
  '   Em        Bm       F#       Bm',
  'Aleluia, aleluia, aleluia, aleluia (2x)',
  ' ',
  '     Bm    F#         Bm',
  '2. A salvação resplendeu,',
  'Em       F#           Bm',
  'um canto novo, um louvor!',
  '   Bm   F#   Bm   Em       F#',
  'Justiça apareceu, um canto novo,',
  '      Bm',
  'um louvor!',
  '     Em   Bm         G',
  'Toda a terra contemplou,',
  'C#7                   F#',
  'um canto novo, um louvor!',
  '    Em           Bm',
  'Com alegria aplaudi,',
  ' G       F#          Bm',
  'um canto novo, um louvor!',
  ' ',
  'Refrão:',
  '           Bm        Em',
  'Nasceu-nos hoje um menino',
  '      F#           Bm',
  'e um Filho nos foi dado',
  '        Bm         Em',
  'Grande é este pequenino.',
  '        F#         Bm',
  'Rei da paz será chamado.',
  '   Em        Bm       F#       Bm',
  'Aleluia, aleluia, aleluia, aleluia (2x)',
  ' ',
  '       Bm     F#      Bm',
  '3. Clarins, violões tocai,',
  'Em        F#          Bm',
  'um canto novo, um louvor!',
  '   Bm      F#     Bm',
  'Ao Rei Senhor aclamai,',
  'Em       F#          Bm',
  'um canto novo, um louvor!',
  '    Em       Bm     G',
  'Cante o mar, o universo,',
  'C#7                  F#',
  'um canto novo, um louvor!',
  '      Em    Bm     G',
  'Na presença do Senhor,',
  'F#                   Bm ',
  'um canto novo, um louvor!',
  ' ',
  'Refrão:',
  '           Bm        Em',
  'Nasceu-nos hoje um menino',
  '      F#           Bm',
  'e um Filho nos foi dado',
  '        Bm         Em',
  'Grande é este pequenino.',
  '        F#         Bm',
  'Rei da paz será chamado.',
  '   Em        Bm       F#       Bm',
  'Aleluia, aleluia, aleluia, aleluia (2x)'
];

export const NoiteFeliz = [
  //_________________________________
  '    A',
  '1. Noite feliz, noite feliz.',
  'E         A',
  'Ó Senhor, Deus de amor.',
  'D               A',
  'Pobrezinho, nasceu em Belém.',
  'D              A',
  'Eis na lapa Jesus, nosso bem.',
  'E         E7       A F#m',
  'Dorme em paz, ó Jesus.',
  ' A        E        A',
  'Dorme em paz, ó Jesus.',
  ' ',
  '    A',
  '2. Noite feliz, noite feliz.',
  'E        A',
  'Ó Jesus, Deus da luz.',
  '  D            A',
  'Quão afável é Teu coração',
  ' D               A',
  'que quiseste nascer nosso irmão.',
  'E        E7       A F#m',
  'E a nós todos salvar.',
  'A        E        A',
  'E a nós todos salvar.',
  ' ',
  '    A',
  '3. Noite feliz, noite feliz.',
  'E             A',
  'Eis que no ar vem cantar.',
  'D                   A',
  'Aos pastores, seus anjos no céu.',
  'D               A',
  'Anunciando a chegada de Deus.',
  ' E    E7        A F#m',
  'De Jesus salvador.',
  'A     E        A',
  'De Jesus salvador.'
];

export const VindeCristao = [
  //_________________________________
  '    F                     C     F',
  '1. Vinde, cristãos, vinde à porfia,',
  '                C    F',
  'hinos cantemos de louvor.',
  '                 C    F',
  'Hinos de paz e de alegria que os anjos',
  '      C     F',
  'cantam ao Senhor.',
  ' ',
  'Refrão:',
  'F F7 Bb C F Dm Gm C',
  'Gló...ó...ó...ó...ória',
  'F Bb F Bb F C',
  'A Deus nas alturas. (2x)',
  ' ',
  '    F                     C      F',
  '2. Vinde, juntar-vos aos pastores,',
  '               C   F',
  'vinde com eles a Belém.',
  '                C     F',
  'Vinde correndo pressurosos,',
  '                   C      F',
  'o Salvador que enfim nos vem.',
  ' ',
  'Refrão:',
  'F F7 Bb C F Dm Gm C',
  'Gló...ó...ó...ó...ória',
  'F Bb F Bb F C',
  'A Deus nas alturas. (2x)',
  ' ',
  '    F              C      F',
  '3. Foi nesta noite venturosa,',
  '               C     F',
  'de nascimento do Senhor.',
  '                        C    F',
  'Que os anjos de voz harmoniosa,',
  '                 C      F',
  'deram a Deus o seu louvor.',
  ' ',
  'Refrão:',
  'F F7 Bb C F Dm Gm C',
  'Gló...ó...ó...ó...ória',
  'F Bb F Bb F C',
  'A Deus nas alturas. (2x)'
];
