export const HojeLivreSou = [
  //_________________________________
  'F9         C      Dm',
  'Presença forte em mim,',
  '           Bb              C',
  'eu posso dizer: habitas aqui.',
  'F9        C       Dm',
  'Porque escravo eu fui',
  '          Bb',
  'e hoje eu sou mais livre',
  '          C',
  'aos Teus pés.',
  ' ',
  '   Dm       Bb',
  'Sentido na vida',
  '     C7          F9',
  'minh’alma encontrou.',
  '    Dm       Bb',
  'Tua mão poderosa',
  '       C7       F9',
  'veio e me libertou.',
  '  Dm      Bb   C7   Dm',
  'Agora eu posso declarar:',
  '     Bb  C  F9',
  'Hoje livre sou.',
  ' ',
  'Refrão:',
  'F9                 Dm',
  'Tenho sede da Tua graça',
  '     Bb   F9',
  'cada dia mais',
  'Sou mais forte,',
  '          Dm',
  'vou mais longe',
  '         Bb    C',
  'quando aqui estás.',
  '                  Bb',
  'Com palavras de amor,',
  '    Dm        Gm',
  'Te adoro, Senhor.',
  '     Bb   C  F9',
  'Hoje livre sou',
  '                         Dm',
  'Meu tesouro, minha herança,',
  '          Bb    F9',
  'meu supremo bem.',
  'Nem tribulações,',
  '    Dm            Bb    C',
  'nem dor podem nos separar.',
  '                  Bb',
  'E jamais irão romper',
  '       Dm       Gm',
  'o que o amor selou.',
  '    Bb   C  F9',
  'Hoje livre sou'
];

export const JesusEstaAqui = [
  //_________________________________
  '  D      A   D          D7',
  'Jesus está aqui (Ele está aqui)',
  '    G',
  'tão certo como o ar',
  '    A      D   D7',
  'que eu respiro',
  '     G               A',
  'Tão certo como o amanhã',
  '         D  Bm',
  'que se levanta',
  '     Em              A',
  'Tão certo como eu te falo',
  '           D',
  'podes me ouvir.',
  ' ',
  'Deus está...',
  'O Espírito está...',
  'Maria está ...'
];

export const JesusSuperAstro = [
  //_________________________________
  '(intro) D D/C D/B D/Bb D',
  'D          D/C',
  'Ontem de manhã (Ontem de manhã)',
  'D/B          D/Bb',
  'Eu vi você por aí (Eu vi você por aí)',
  'D        D/C',
  'Nos automóveis (Nos automóveis)',
  'D/B               D/Bb',
  'Dos homens cheios daqui (Dos homens cheios daqui)',
  'D              D/C',
  'Vi uma luz diferente (Vi uma luz diferente)',
  'D/B                D/Bb',
  'No Santo daquele altar (No santo daquele altar)',
  'D                   D/C',
  'E me sentei bem na frente (me sentei bem na frente)',
  'D/B           D/Bb',
  'E comecei a rezar (e comecei a rezar)',
  'D             D/C',
  'Os bancos atrás de mim',
  ' D/B                D/Bb',
  'vazios nunca foram assim',
  'D           D/C',
  ' Sem um violão, (sem um violão)',
  'D/B      D/Bb',
  'Sem um menino, (sem um menino)',
  'D               D/C',
  ' Sem uma canção,',
  'D/B              D/Bb',
  'da missa de domingo',
  '       D',
  'E eu estava só(e eu estava só)',
  '         D/C',
  'e eu estava só ( e eu estava só)',
  '     D/B      D/Bb',
  'E eu estava só',
  '       D',
  'Com você(com você)',
  '     D/C',
  'Jesus Cristo (Jesus Cristo)',
  '      D/B',
  'Super astro(Super astro)',
  '   D/Bb',
  'super rei (Super Rei)',
  '      D               D/C',
  'Encontrei você, encontrei você,',
  '   D/B      D/Bb',
  'Eu encontrei você',
  '      D          D/C',
  'Jesus Cristo Eu te adoro',
  '   D/B    D/Bb D',
  'Eu te adoro Amém!'
];

export const LivreAcesso = [
  //_________________________________
  'E                          G#m',
  'Eu abro as portas do meu coração,',
  'A                   E',
  'te dou livre acesso, Senhor.',
  '                  G#m   A',
  'Eu abro as portas do meu coração,',
  '      E',
  'te dou livre acesso.',
  ' ',
  ' C        D',
  'Pois com Teu braço',
  '   Em C     D        Em',
  'forte   realizas prodígios',
  ' C        D           G',
  'Pois com Teu braço forte,',
  'D/F# Em Am    Am/G        D',
  ' Senhor,   me ergues do chão.',
  ' C        D',
  'Pois com Teu braço',
  '   Em  C     D       Em',
  'forte realizas prodígios',
  ' C        D          G',
  'Pois com Teu braço forte,',
  'D/F# Em     Am      D   G',
  ' Senhor, me ergues do chão.'
];

export const NaoDaMaisPraVoltar = [
  //_________________________________
  '    G Bm',
  'Não dá mais pra voltar,',
  'C          Am  D',
  ' o barco está em alto-mar (2x)',
  ' ',
  '    G C               D',
  'Não dá mais pra negar,',
  '                 G',
  'o mar é Deus e o barco sou eu',
  'E          E7',
  ' E o vento forte',
  'Am                     D',
  ' que me leva pra frente',
  '             G',
  'é o amor de Deus',
  ' ',
  'Não dá nem mais pra ver o porto',
  'que era seguro',
  'Eu sou impulsionado a desbravar',
  'um novo mundo'
];

export const NoitesTraicoeiras = [
  //_________________________________
  ' E                     G#m',
  'Deus está aqui neste momento.',
  '        A      F#m            B7',
  'Sua presença é real em meu viver.',
  '    E                       G#m',
  'Entregue sua vida e seus problemas.',
  '          A          F#m        B7',
  'Fale com Deus, Ele vai ajudar você.',
  ' ',
  'A              F#m            B7',
  'Deus te trouxe aqui para aliviar',
  '            E',
  'o teu sofrimento.',
  'A               F#m',
  'É Ele o autor da fé,',
  '                 B7',
  'do princípio ao fim,',
  '                    E     E7',
  'de todos os seus momentos.',
  ' ',
  'Refrão:',
  '             A               B7',
  'E ainda se vier noites traiçoeiras,',
  '                  E',
  'se a cruz pesada for,',
  '                  A',
  'Cristo estará contigo.',
  '             F#m                B7',
  'O mundo pode até fazer você chorar,',
  '                     E     (E7)',
  'mas Deus te quer sorrindo. (2x)',
  ' ',
  ' E                     G#m',
  'Seja qual for o seu problema,',
  '           A          F#m       B7',
  'fale com Deus, Ele vai ajudar você.',
  '  E                 G#m',
  'Após a dor vem a alegria.',
  '              A',
  'Pois Deus é amor',
  '         F#m         B7',
  'e não te deixará sofrer.'
];

export const MisterioDaTrindade = [
  //_________________________________
  'Intr. Bm A F#m G A/B',
  ' ',
  'Bm             F#m          Bm',
  'Caminhando na praia deserta,',
  '         F#m',
  'me vi a pensar',
  '       G           A     Bm',
  'No mistério da Trindade Santa',
  '                    F#m',
  'Quando ao longe um menino',
  'Bm              F#m',
  '  tentava com uma concha',
  '     G',
  'Colocar o mar',
  '     A             D',
  'num buraquinho na areia',
  'A/C#      Bm       F#m',
  'Logo me aproximei dizendo',
  '      Bm',
  'a ele',
  '              F#m',
  'Que era um trabalho em vão',
  ' G             D/F#',
  'Qual surpresa, era um anjo!',
  ' Em               F#',
  'Que me olhou e então me disse',
  'Bm            F#m          Bm',
  ' “É mais fácil pôr o mar aqui,',
  '            F#m7',
  'que compreenderes',
  'G          A',
  'A Trindade e todo o seu',
  '    Bm     G A',
  'mistério”',
  'Bm             F#m',
  'Caminhando na praia deserta,',
  'Bm         F#m',
  '  me vi a pensar',
  '       G           A     Bm',
  'No mistério da Trindade Santa'
];

export const OndeGrandeESerPequeno = [
  //_________________________________
  'E           G#m          C#m',
  'Às vezes me sinto tão distante,',
  'A                     F#m   B7',
  ' a vergonha não me deixa nem falar.',
  'E           G#m',
  'E sei que em mim',
  '             C#m  A',
  'dói ver-Te pregado.',
  'Mas me esqueço',
  '   F#m           B7',
  'do muito que me amais.',
  ' ',
  'C#m     G#m   A C#m',
  '     Quero voltar,',
  '  G#m      A',
  'a ser-Te fiel.',
  'C#m     G#m   A C#m',
  '     Quero voltar,',
  '  G#m      A     D  B7',
  'a ser-Te fiel, Fiel.',
  ' ',
  'Refrão:',
  'E       G#m           A',
  'Toma de mim o que te sirva,',
  '      B7',
  'para dar-me aos demais.',
  'E       G#m           A',
  'Toma de mim o que te sirva,',
  '     B7',
  'sou Teu e nada mais.',
  'C#m        G#m            A',
  'Hoje quero ser Teu instrumento,',
  '     F#m B7     C#m           G#m',
  'Proclamar a verdade de Tua palavra,',
  '        A         D',
  'de Teu corpo. De Teu amor eterno,',
  '       B7',
  'Onde grande é ser pequeno.',
  ' ',
  'E              G#m              C#m',
  'Procuro encontrar-Te em meus irmãos,',
  'A                F#m        B7',
  'mas parece impossível sem em  amar.',
  'E               G#m           C#m',
  'Sou fraco e Te peço que Tuas mãos,',
  'A               F#m           B7',
  ' abram pouco a pouco o meu coração.',
  ' ',
  'C#m     G#m   A C#m',
  '     Quero voltar,',
  '  G#m      A',
  'a ser-Te fiel.',
  'C#m     G#m   A C#m',
  '     Quero voltar,',
  '  G#m      A     D  B7',
  'a ser-Te fiel, Fiel.',
  ' ',
  'Refrão:',
  'E       G#m           A',
  'Toma de mim o que te sirva,',
  '      B7',
  'para dar-me aos demais.',
  'E       G#m           A',
  'Toma de mim o que te sirva,',
  '     B7',
  'sou Teu e nada mais.',
  'C#m        G#m            A',
  'Hoje quero ser Teu instrumento,',
  '     F#m B7     C#m           G#m',
  'Proclamar a verdade de Tua palavra,',
  '        A         D',
  'de Teu corpo. De Teu amor eterno,',
  '       B7',
  'Onde grande é ser pequeno.'
];

export const PaiNosso = [
  //_________________________________
  '    C            G       C',
  'Pai nosso que estais no céu',
  '        C           G     C',
  'Santificado seja o Vosso nome',
  '         F     C     F',
  'Venha a nós o Vosso reino',
  '     F       G         C',
  'Seja feita a Vossa vontade',
  '          F     G       C',
  'Assim na Terra como no céu',
  '       E',
  'O pão nosso de cada dia',
  '        F G C',
  'nos dai hoje',
  '     E              F G C  C7',
  'Perdoai as nossas ofensas',
  '   F        G       C',
  'Assim como nós perdoamos',
  '    F       G       C',
  'A quem nos tem ofendido',
  '   F',
  'E não nos deixeis',
  '         G    C            G',
  'cair em tentação, em tentação',
  '         F   G      C',
  'Mas livrai-nos do mal.'
];

export const PodesReinar = [
  //_________________________________
  'G',
  'Senhor,',
  '                        D',
  'eu sei que é Teu esse lugar,',
  '                   C',
  'todos querem Te adorar,',
  '                G  D',
  'Toma a Tua direção',
  '        G',
  'Sim, ó vem,ó Santo Espírito',
  '     D',
  'os espaços preencher',
  '     C           Am           D',
  'Reverência à Tua voz vamos fazer.',
  ' ',
  'Refrão:',
  '          G       G7   C     Cm',
  'Podes reinar Senhor Jesus, ó sim.',
  '   G            Em      Am   D',
  'O Teu poder Teu povo sentirá.',
  '             G',
  'Que bom, Senhor,',
  '   G7        C             Cm',
  'saber que estás presente aqui.',
  ' G          D           C G',
  'Reina, Senhor, nesse lugar',
  ' ',
  'G',
  'Visita a cada irmão,',
  '          D',
  'ó meu Senhor,',
  '                 C',
  'dá-lhe paz interior',
  '                    G  D',
  'E razões pra Te louvar.',
  '    G',
  'Desfaz todas tristezas,',
  '     D',
  'incertezas, desamor,',
  '    C      Am',
  'Glorifica o Teu nome,',
  '         D',
  'ó meu Senhor.',
  ' ',
  'Refrão:',
  '          G       G7   C     Cm',
  'Podes reinar Senhor Jesus, ó sim.',
  '   G            Em      Am   D',
  'O Teu poder Teu povo sentirá.',
  '             G',
  'Que bom, Senhor,',
  '   G7        C             Cm',
  'saber que estás presente aqui.',
  ' G          D           C G',
  'Reina, Senhor, nesse lugar'
];

export const PrincipeDaPaz = [
  //_________________________________
  'A9          E/G#',
  'A caminho na noite escura',
  'F#m             B7',
  'brilha a luz no céu de Belém.',
  'A9          E/G#',
  ' Uma estrela guia',
  'F#m           B7',
  'que conduz os reis mais além.',
  'A            E/G#',
  'Não há dor não há mais medo',
  'F#m',
  'Fez-se a paz,',
  '    B7                   A',
  'revelou-se o segredo é Jesus',
  'E/G#  F#m  B7',
  'O, O, O, O',
  '         A    E/G# F#m B7',
  'Viemos adorá-lo',
  ' ',
  'Refrão:',
  'E          G#m        C#m',
  'Príncipe da paz homem Deus',
  '   A',
  'perfeita harmonia,',
  '    B7',
  'verdade, alegria',
  'E         G#m       C#m',
  'Infinito amor somos teus',
  'A                B7',
  'És nossa luz o sentido',
  '          A E/G# F#m B7',
  'da vida aaa',
  '        A     E/G# F#m B7',
  'Viemos adorá-lo.',
  ' ',
  'A9          E/G#',
  'Hoje somos nós teus heróis',
  '  F#m         B7',
  'chamados por ti a santidade.',
  'A9          E/G#',
  'Levando tua cruz pelo mundo',
  'F#m            B7',
  'ressurgirá nova humanidade',
  'A             E/G#',
  'Não há dor, não há mais medo',
  'F#m',
  'Fez-se a paz',
  '      B7',
  'revelou-se o segredo',
  'C#m           G#m',
  ' Um para outro   um com o outro,',
  'A              B7',
  'Juntos no coração de Deus.',
  '            E',
  'Viemos adorá-lo.',
  ' ',
  'Refrão:',
  'E          G#m        C#m',
  'Príncipe da paz homem Deus',
  '   A',
  'perfeita harmonia,',
  '    B7',
  'verdade, alegria',
  'E         G#m       C#m',
  'Infinito amor somos teus',
  'A                B7',
  'És nossa luz o sentido',
  '          A E/G# F#m B7',
  'da vida aaa',
  '        A     E/G# F#m B7',
  'Viemos adorá-lo.'
];

export const QuemPerdeSuaVidaAEncontra = [
  //_________________________________
  '     D          A/C#    Bm',
  'Quem perde sua vida por mim,',
  '    A     G',
  'a encontrará,',
  '           A',
  'a encontrará,',
  '         D  A/C# Bm A G A',
  'a encontrará',
  '      D        A/C#   Bm',
  'Quem deixa seu pai por mim,',
  '    A       G',
  'sua mãe por mim',
  '           A             D',
  'me encontrará, me encontrará',
  '     A/C#  Bm         A     G',
  'Não tenhas medo, não tenhas medo',
  '            A',
  'Eu estou aqui,',
  '          D   A/C# Bm A G A',
  'eu estou aqui',
  ' ',
  '      D         A/C#     Bm',
  'Quem deixa sua terra por mim,',
  '     A        G',
  'seus bens por mim,',
  '                 A',
  'seus filhos por mim,',
  '           D',
  'me encontrará',
  '    A/C#   Bm',
  'Não tenhas medo,',
  ' A     G                 A',
  'eu conheço aqueles que elegi',
  '              D',
  'aqueles que elegi',
  '    A/C#   Bm         A     G',
  'Não tenhas medo, não tenhas medo',
  '            A',
  'Eu estou aqui,',
  '          D   A/C# Bm A G A',
  'eu estou aqui',
  '     D           A/C#   Bm',
  'Quem perde sua vida por mim,',
  '    A     G',
  'a encontrará,',
  '           A',
  'a encontrará,',
  '         D   A/C# Bm A G A',
  'a encontrará'
];

export const QueroMegulhar = [
  //_________________________________
  'E',
  'Quero mergulhar nas',
  '      G#m     A                  E',
  'profunde.....zas do Espírito de Deus',
  'E descobrir suas',
  '  G#m    A              E',
  'rique...zas em meu coração',
  'E descobrir suas',
  '  G#m    A              E',
  'rique...zas em meu coração (2x)',
  ' ',
  '     G#m   A          E',
  'É tão lindo, tão simples',
  '     C#m',
  'Brisa leve tão suave,',
  '        A      B7       E',
  'doce Espírito Santo de Deus.',
  '    C#m',
  'Tão suave, brisa leve,',
  '        A      B7       E',
  'doce Espírito Santo de Deus.'
];

export const QuieroSerSanto = [
  //_________________________________
  '           G',
  'Quiero ser santo Señor',
  '    C         D',
  'me cuesta tanto seguirte.',
  '           G',
  'Quiero ser santo Señor',
  '        C          D',
  'porque vos me lo pediste.',
  ' ',
  'Refrão:',
  '           Em                 Bm',
  'Aunque me cueste, aunque no pueda.',
  '         C      Am',
  'Aunque reviente,',
  '           D    G',
  'aunque me muera',
  '        Em',
  'Sólo lanzado',
  '        C             D   G',
  'a la aventura de tu amor,',
  '        Em       C    D    G',
  'mi vida tiene sentido. (2X)',
  ' ',
  'Con los pies en la tierra',
  'pero los ojos en el cielo.',
  'Necesito tu mano',
  'porque solo no puedo.',
  ' ',
  'Refrão:',
  '           Em                 Bm',
  'Aunque me cueste, aunque no pueda.',
  '         C      Am',
  'Aunque reviente,',
  '           D    G',
  'aunque me muera',
  '        Em',
  'Sólo lanzado',
  '        C             D   G',
  'a la aventura de tu amor,',
  '        Em       C    D    G',
  'mi vida tiene sentido. (2X)'
];

export const SenhorDaVida = [
  //_________________________________
  'G         Bm    C         D',
  'Senhor da vida, ó Dom de amor!',
  'G         Bm      C      D',
  'Ó pão do céu que veio a nós.',
  'Em             C        D  Em',
  ' Vamos receber a nossa paz!',
  '               C            D',
  'Vamos acolher Cristo entre nós.',
  '    C      Bm',
  'adorar o amor,',
  '     C  Am      D',
  'e adorar  o Senhor.',
  ' ',
  'Refrão:',
  ' G            Bm',
  'Viemos para adorar',
  '   C           D',
  'e juntos vamos cantar.',
  '  G         Bm',
  'Viemos para adorar o Senhor',
  '   C               D',
  'e juntos nos entregar,',
  '   C      D     G   Bm C D G',
  'na Aliança de Amor.',
  ' ',
  'Olhar tão puro, Imaculado; Cordeiro Santo,',
  'estás ao nosso lado. Tu estás aqui em meio a nós,',
  'apascenta os lírios com tua voz.',
  'E todas nós te seguiremos, em uma voz te cantaremos.',
  ' ',
  'Refrão:',
  ' G            Bm',
  'Viemos para adorar',
  '   C           D',
  'e juntos vamos cantar.',
  '  G         Bm',
  'Viemos para adorar o Senhor',
  '   C               D',
  'e juntos nos entregar,',
  '   C      D     G   Bm C D G',
  'na Aliança de Amor.',
  ' ',
  'Aurora viva brilha entre nós.',
  'Gerando o filho Santo de Deus.',
  'Ela é a Mãe, flor que nasceu, lírio no deserto,',
  'rosto de Deus. Em ti vivemos e adoramos o amor,',
  'em ti cantamos o nosso canto maior.',
  ' ',
  'Refrão:',
  ' G            Bm',
  'Viemos para adorar',
  '   C           D',
  'e juntos vamos cantar.',
  '  G         Bm',
  'Viemos para adorar o Senhor',
  '   C               D',
  'e juntos nos entregar,',
  '   C      D     G   Bm C D G',
  'na Aliança de Amor.'
];

export const SondaMe = [
  //_________________________________
  ' Em                          Am',
  'Senhor, eu sei que tu me sondas',
  'D                 G',
  'sei também que me conheces',
  'Em                         Am',
  'Se me assento ou me levanto',
  ' B7                   Em',
  'conheces meus pensamentos.',
  'Em                        Am',
  'Quer deitado ou quer andando',
  'D                      G',
  'sabes todos os meus passos.',
  'Em                          Am',
  'E antes que haja em mim palavras',
  'B7                     Em',
  'sei que tudo me conheces',
  ' ',
  'Refrão:',
  'E/G#     E                  Am',
  'Senhor, eu sei que tu me sondas',
  'D7',
  'Senhor,',
  '                    G  D/F#',
  'eu sei que tu me sondas',
  'Em                          Am',
  'Senhor, eu sei que tu me sondas',
  'B7                           Em',
  'Senhor, eu sei que tu me sondas',
  ' ',
  'Deus, tu me cercaste em volta',
  'Tuas mãos em mim repousam.',
  'Tal ciência é grandiosa',
  'não alcanço de tão alta',
  ' ',
  'Refrão:',
  'E/G#     E                  Am',
  'Senhor, eu sei que tu me sondas',
  'D7',
  'Senhor,',
  '                    G  D/F#',
  'eu sei que tu me sondas',
  'Em                          Am',
  'Senhor, eu sei que tu me sondas',
  'B7                           Em',
  'Senhor, eu sei que tu me sondas',
  ' ',
  'Se eu subo até o céu',
  'sei que ali também te encontro.',
  'Se no abismo está minha alma',
  ' ',
  'Refrão:',
  'E/G#     E                  Am',
  'Senhor, eu sei que tu me sondas',
  'D7',
  'Senhor,',
  '                    G  D/F#',
  'eu sei que tu me sondas',
  'Em                          Am',
  'Senhor, eu sei que tu me sondas',
  'B7                           Em',
  'Senhor, eu sei que tu me sondas'
];

export const SoPorTiJesus = [
  //_________________________________
  '        E        A',
  'Só por Ti, Jesus,',
  '               C#m7',
  'quero me consumir',
  '                 A          F#m',
  'Como vela que queima no altar.',
  '                 B',
  'Me consumir de amor.',
  '       E        A             C#m7',
  'Só em Ti, Jesus, quero me derramar.',
  '                  A       F#m',
  'Como o rio se entrega ao mar.',
  '         B            E   E7',
  'Me derramar de amor.',
  ' ',
  'Refrão:',
  '        A',
  'Pois Tu és o meu amparo,',
  '         B/A',
  'o meu refúgio,',
  '                 G#m',
  'és alegria de minh’alma.',
  '       A                       B/A',
  'Só em Ti repouso a minha esperança,',
  '          G#m',
  'não vacilarei.',
  '           C#m',
  'E mesmo na dor.',
  '        F#m         B/A',
  'Quero seguir até o fim.',
  '       E          A',
  'Só por Ti, Jesus.'
];

export const TaoSublimeSacramento = [
  //_________________________________
  'A7      D     A7   D',
  'Tão sublime Sacramento,',
  ' Bm F#m    A7      D',
  'adoremos neste altar.',
  'A7       D     A7   D',
  'Pois o antigo testamento',
  'Bm     F#m   A7    D',
  'deu ao novo seu lugar.',
  'A7       D   A7       D',
  'Venha a fé, por suplemento.',
  ' G     D G    A7   D',
  'Os sentidos completar',
  'A7   D     A7     D      Bm   F#m',
  'Ao eterno Pai cantemos e a Jesus,',
  '  A7    D',
  'o Salvador.',
  'A7    D     A7   D',
  'Ao Espírito exaltemos,',
  'Bm      F#m   A7     D',
  'na trindade eterno amor.',
  'A7      D   A7       D',
  'Ao Deus uno e trino demos',
  'G      D G  A7     D',
  'a alegria   do louvor.',
  'A7 D A7 D',
  'Amém. Amém.'
];

export const TeLouvoEmVerdade = [
  //_________________________________
  ' E           G#m',
  'Mesmo na tempestade,',
  'Bm7          E7      A9',
  'mesmo que se agite o mar.',
  '   E         F#m   B7    E   B7',
  'Te louvo, te louvo em verdade.',
  ' E             G#m',
  'Mesmo longe dos meus,',
  'Bm7      E7   A9',
  'mesmo na solidão,',
  '   E         F#m   B7    E  E7',
  'Te louvo, te louvo em verdade.',
  ' ',
  'Refrão:',
  '       A             B7',
  'Pois somente tenho a Ti,',
  '  G#m           C#m',
  'Tu és a minha herança',
  '   F#m       B7          E',
  'Te louvo, te louvo em verdade (bis)',
  ' ',
  'Mesmo que me faltem palavras,',
  'mesmo que eu não saiba louvar',
  'Te louvo, te louvo em verdade',
  ' ',
  'Refrão:',
  '       A             B7',
  'Pois somente tenho a Ti,',
  '  G#m           C#m',
  'Tu és a minha herança',
  '   F#m       B7          E',
  'Te louvo, te louvo em verdade (bis)'
];

export const ComoAntesMasQueAntes = [
  //_________________________________
  '     D              A        Bm G',
  'Como antes, más que antes, Amor',
  '          D',
  'sopla tu viento,',
  '       A         Bm   G',
  'ven Espíritu de Amor',
  '             D',
  'enciende el Fuego',
  '        A           Bm  G',
  'que da vida en comunión,',
  '           Bm',
  'siembra tu huerto,',
  '     Em    A   D   Asus4 A',
  'inunda mi corazón.',
  ' ',
  'Como antes, más que antes, Amor',
  'sopla tu viento, ven Espíritu de Amor;',
  'alienta el alma, da esperanza, da calor...',
  'Tú me conoces y me amas como soy.',
  ' ',
  '     D     A',
  'Como antes,',
  '   Bm   G D A Bm B7',
  'más que antes...',
  ' ',
  '     E              B',
  'Como antes, más que antes,',
  ' C#m A',
  'Amor,',
  '          E',
  'sopla tu viento,',
  '       B         C#m A',
  'ven Espíritu de Amor;',
  '             E',
  'enciende el Fuego',
  '        B          C#m  A',
  'que da vida en comunión,',
  '           C#m',
  'siembra tu huerto,',
  '    F#m   B7    E   B7',
  'inunda mi corazón.',
  ' ',
  'Como antes, más que antes, Amor',
  'sopla tu viento, ven Espíritu de Amor;',
  'alienta el alma, da esperanza, da calor...',
  'Tú me conoces y me amas como soy.',
  '     E     B',
  'Como antes,',
  '       C#m   A',
  'más que antes,',
  'E B C#m A',
  'Amor…     (2X)'
];
