export const AleluiaAMinhaAlmaEuAbrirei = [
	//_________________________________
	" C  G     F    C",
	"Aleluia, aleluia,",
	"F     Dm    G       G7",
	"a minha alma abrirei.",
	" C  G    F    C   F       G7   C  A7",
	"Aleluia, aleluia, Cristo é meu Rei",
	"D   A    G   D",
	"Aleluia, aleluia,",
	"G     Em     A    A7",
	"a minha alma abrirei.",
	"D   A   G    D    G      A     D",
	"Aleluia, aleluia, Cristo é meu Rei"

];

export const AleluiaAlguemDoPovoExclama = [
	//_________________________________
	"Refrão:",
	"E  F#m   B7  E   C#m   F#m",
	"Aleluia, aleluia, aleluia,",
	"    B7  E",
	"aleluia. (2x)",
	" ",
	"    E",
	"Alguém do povo exclama",
	"        A            E",
	"como és grande, ó Senhor!",
	"  C#m           F#7   B7",
	"Quem te gerou e alimentou.",
	"   E",
	"Jesus responde: ó mulher,",
	"    A          E",
	"pra mim és feliz.",
	"    C#m             F#7",
	"Quem soube ouvir a vós de Deus",
	"  B7        E",
	"e tudo guardou."
];

export const AleluiaAoSantoEvangelho = [
	//_________________________________
	"C         Am       F   C",
	"Aleluia! Aleluia! Aleluia,",
	"     F                         G  A",
	"ao Santo Evangelho vamos aclamar!",
	"D        Bm       G   D",
	"Aleluia! Aleluia! Aleluia,",
	"     G                         A D",
	"ao Santo Evangelho vamos aclamar!"

];

export const AleluiaJumasAberto = [
	//_________________________________
	"Refrão:",
	"F#m   Bm   C#7      F#m",
	"A---leluia, A-----leluia,",
	"     Bm",
	"A---leluia,",
	"C#7               F#m",
	"Jumas aberto a escutar",
	" ",
	"  F#m    C#7  F#m",
	"Vibrando com Maria",
	"  Bm        A",
	"Queremos assumir",
	"     Bm          F#m",
	"A palavra que é missão",
	"      C#7         F#m",
	"Para o mundo transformar"
];

export const AleluiaQuandoEstamosUnidos = [
	//_________________________________
	"Refrão:",
	"E  B    C#m  G#m    A E B7",
	"Aleluia, Aleluia, Aleluia. (bis)",
	"F#m             G#7  C#m",
	" Quando estamos unidos",
	"           G#7",
	"Estás entre nós",
	"A          F#m        A  B7",
	"E nos falarás da tua vida.",
	" ",
	"F#m         G#7 C#m         G#7",
	" Este nosso mundo sentido terá",
	"A       F#m        A  B7",
	"se Tua palavra renovar."
];

export const BuscaiPrimeiro = [
	//_________________________________
	" D         A      Bm       F#m",
	"Buscai primeiro o reino de Deus",
	"G   D       E  A",
	"E a Sua justiça",
	"D        A        Bm       F#m",
	"E tudo mais vos será acrescentado",
	"G  D        A D",
	"Aleluia, Aleluia!",
	" ",
	"Nem só de pão o homem viverá",
	"Mas de toda a palavra",
	"que procede da boca de Deus",
	"Aleluia, Aleluia!"
];

export const ComoSaoBelos = [
	//_________________________________
	" G7       C        D           G  Em",
	"Como são belos os pés do mensageiro",
	"       Am  D  G",
	"que anuncia a paz.",
	"G7       C         D           G  Em",
	"Como são belos os pés do mensageiro",
	"       Am  D  G     G7",
	"que anuncia o Senhor.",
	" ",
	"Refrão:",
	"    C   Cm      G  Em       Am D",
	"Ele vive, Ele reina. Ele é Deus",
	"     G  G7",
	"e Senhor.",
	" ",
	"O meu senhor chegou com toda a glória,",
	"vivo Ele está, Ele está.",
	"Bem junto a nós, seu corpo santo",
	"a nos tocar,",
	"e vivo eu sei, Ele está.",
	" ",
	"Refrão:",
	"    C   Cm      G  Em       Am D",
	"Ele vive, Ele reina. Ele é Deus",
	"     G  G7",
	"e Senhor."
];

export const EuVimParaEscutar = [
	//_________________________________
	"   Dm       A    Dm",
	"Eu vim para escutar...",
	" ",
	"Refrão:",
	"D7   Gm      C     F",
	"Tua palavra, Tua palavra,",
	"Bb    A7        Dm",
	"Tua palavra de amor. (2x)",
	" ",
	"   Dm       A      Dm",
	"Eu gosto de escutar...",
	" ",
	"   Dm          A      Dm",
	"Eu quero entender melhor...",
	" ",
	"   Dm         A     Dm",
	"O mundo ainda vai viver..."
];

export const RendeilheAJave = [
	//_________________________________
	"     G                    C9",
	"Rendei-lhe a Javé, santos do Senhor.",
	"        G                    D",
	"Glória e poder a quem fez a criação.",
	"            G ",
	"Rendei-lhe honra ao glorioso",
	"     C9",
	"nome do Senhor,",
	"      G      D              G  C9",
	"e Louvai em seu Santo esplendor.",
	" ",
	"Refrão:",
	"         G        C9     G",
	"Sobre os mares ressoa a voz de Deus,",
	"                     C9          D",
	"glorioso é Deus, tua voz faz tremer.",
	"       G       C9        G",
	"E poderosa é a voz do Altíssimo,",
	"      C              D",
	"Aleluia! Tua voz desgarra",
	"              G",
	"os cedros do Líbano;",
	"     C               D",
	"Aleluia! A voz do Senhor",
	"                  G",
	"vem em línguas de Fogo;",
	"      C            D",
	"Aleluia! Sacode o monte",
	"           G",
	"a voz do Altíssimo;",
	"      C              D",
	"Aleluia! Em teu Santuário",
	"           G",
	"gritam: “Glória, Glória!!”",
	" ",
	"Sentado está Deus sobre a tempestade,",
	"sentado está Javé, qual rei eterno.",
	"Suas forças dá quem põe sua confiança nele.",
	"Javé abençoa Teu povo, tua paz.",
	" ",
	"Refrão:",
	"         G        C9     G",
	"Sobre os mares ressoa a voz de Deus,",
	"                     C9          D",
	"glorioso é Deus, tua voz faz tremer.",
	"       G       C9        G",
	"E poderosa é a voz do Altíssimo,",
	"      C              D",
	"Aleluia! Tua voz desgarra",
	"              G",
	"os cedros do Líbano;",
	"     C               D",
	"Aleluia! A voz do Senhor",
	"                  G",
	"vem em línguas de Fogo;",
	"      C            D",
	"Aleluia! Sacode o monte",
	"           G",
	"a voz do Altíssimo;",
	"      C              D",
	"Aleluia! Em teu Santuário",
	"           G",
	"gritam: “Glória, Glória!!”"
];

export const ShemaIsrael = [
	//_________________________________
	"   Am             C",
	"Shemá Israel, Adonai Elohenu.",
	"G       Am",
	" Adonai eha!",
	"   Am             C",
	"Shemá Israel, Adonai Elohenu.",
	"G       Am",
	" Adonai eha!",
	" ",
	"  C                    G",
	"Escuta Israel, o Senhor é nosso Deus.",
	" Am          G",
	"Um é o Senhor!",
	"  C                    G",
	"Escuta Israel, o Senhor é nosso Deus.",
	" Am   G     Am",
	"Um é o Senhor!"
];

export const TuaPalavraEAssim = [
	//_________________________________
	"Refrão:",
	"E                  B7",
	"É como a chuva que lava,",
	"F#m       B7        E",
	" é como o fogo que arrasa.",
	" B7",
	"Tua Palavra é assim,",
	"   A          G#m       F#m",
	"não passa por mim sem deixar",
	"    E",
	"um sinal. (bis)",
	" ",
	"       E",
	"Tenho medo de não responder,",
	"                       B7",
	"de fingir que não escutei.",
	"         A                   G#m",
	"/: Tenho medo de ouvir teu chamado,",
	"              F#m",
	"virar do outro lado",
	"      B7          E",
	"e fingir que não sei. (bis).",
	" ",
	"Refrão:",
	"E                  B7",
	"É como a chuva que lava,",
	"F#m       B7        E",
	" é como o fogo que arrasa.",
	" B7",
	"Tua Palavra é assim,",
	"   A          G#m       F#m",
	"não passa por mim sem deixar",
	"    E",
	"um sinal. (bis)",
	" ",
	"Tenho medo de não perceber,",
	"de não ver teu amor passar.",
	"/: Tenho medo de estar distraído,",
	"magoado e ferido e então me fechar. (bis).",
	" ",
	"Refrão:",
	"E                  B7",
	"É como a chuva que lava,",
	"F#m       B7        E",
	" é como o fogo que arrasa.",
	" B7",
	"Tua Palavra é assim,",
	"   A          G#m       F#m",
	"não passa por mim sem deixar",
	"    E",
	"um sinal. (bis)",
	" ",
	"Tenho medo de estar a gritar,",
	"e negar-te o meu coração.",
	"/: Tenho medo do Cristo que passa,",
	"oferece uma graça e eu digo que não. (bis)",
	" ",
	"Refrão:",
	"E                  B7",
	"É como a chuva que lava,",
	"F#m       B7        E",
	" é como o fogo que arrasa.",
	" B7",
	"Tua Palavra é assim,",
	"   A          G#m       F#m",
	"não passa por mim sem deixar",
	"    E",
	"um sinal. (bis)"
];

export const ATiMeuDeus = [
	//_________________________________
	"  E",
	"1. A Ti, meu Deus,",
	"                 F#m",
	"elevo o meu coração,",
	"                  B",
	"Elevo as minhas mãos,",
	"       A          E     B7",
	"meu olhar, minha voz.",
	"           E                   A",
	"A Ti, meu Deus, eu quero oferecer",
	"                     E",
	"Meus passos e meu viver,",
	"        B7               E",
	"meus caminhos, meu sofrer.",
	" ",
	"Refrão:",
	"   E                    A          E",
	"A Tua ternura, Senhor, vem me abraçar",
	"                                   F#m",
	"E a Tua bondade infinita, me perdoar.",
	"     A              Am",
	"Vou ser o Teu seguidor",
	"      E             C#7",
	"e Te dar o meu coração",
	"   F#m               B7          E",
	"Eu quero sentir o calor de Tuas mãos.",
	" ",
	"              E",
	"2. A Ti, meu Deus,",
	"                        F#m",
	"que és bom e que tens amor",
	"                     B",
	"Ao pobre e ao sofredor",
	"        A         E     B7",
	"vou servir e esperar.",
	"           E                      A",
	"Em Ti, Senhor, humildes se alegrarão",
	"                    E",
	"Cantando a nova canção",
	"        B7         E",
	"de esperança e de paz.",
	" ",
	"Refrão:",
	"   E                    A          E",
	"A Tua ternura, Senhor, vem me abraçar",
	"                                   F#m",
	"E a Tua bondade infinita, me perdoar.",
	"     A              Am",
	"Vou ser o Teu seguidor",
	"      E             C#7",
	"e Te dar o meu coração",
	"   F#m               B7          E",
	"Eu quero sentir o calor de Tuas mãos.",
	" ",

];

export const ConsagradoParaAmar = [
	//_________________________________
	"F 		  C/E 			 F",
	"Venho, Senhor, me ofertar.",
	"	   C/E 		  Dm  Dm/C",
	"A minha vida consagrar",
	"Bb 					 C/Bb",
	"Quero renovar o meu sim.",
	"	Am 			   Dm",
	"Que Tua vontade se faça em mim",
	"  Gm 		C 			  F  Bb/C",
	"Renova, Senhor, minha vocação",
	" ",
	"Refrão:",
	"F 			  C/E",
	"Um consagrado para amar.",
	"F 			  C/E",
	"Um consagrado pra se doar.",
	"   Bb/D 			F/C",
	"Um amor que tudo suporta.",
	"	 G/B 		 G 		  C",
	"Um amor que não dá pra improvisar.",
	"F 			  C/E",
	"Um consagrado para amar.",
	"F 			  C/E",
	"Um consagrado pra se doar.",
	"   Bb 					  F/A",
	"Um amor que não busca interesses seus,",
	"Gm 				C",
	"é o mais puro amor,",
	"		   F",
	"o amor de Deus."
];

export const DeMaosEstendidas = [
	//_________________________________
	"Refrão:",
	"Bm 			 	  Em   F#7 	 Bm",
	"De mãos estendidas  ofertamos",
	"		  		 Em  F#7 	 Bm 	 (B7)",
	"o que de graça  recebemos. (2x)",
	" ",
	"				 Em   A",
	"1. A natureza tão bela",
	"						D  Bm",
	"que é louvor, que é serviço.",
	"					 Em     F#7",
	"O sol que ilumina as trevas,",
	"					Bm  B7",
	"transformando-as em luz",
	"					 Em  A",
	"O dia que nos traz o pão",
	"						D   Bm",
	"e a noite que nos dá repouso",
	"				Em  F#7",
	"Ofertemos ao Senhor",
	"				Bm  (B7)",
	"o louvor da criação",
	" ",
	"Refrão:",
	"Bm 			 	  Em   F#7 	 Bm",
	"De mãos estendidas  ofertamos",
	"		  		 Em  F#7 	 Bm 	 (B7)",
	"o que de graça  recebemos. (2x)",
	" ",
	"					  Em   A",
	"2. Nossa vida toda inteira",
	"				D  Bm",
	"ofertamos ao Senhor",
	"				  Em  F#7",
	"Como prova da amizade,",
	"			   Bm B7",
	"como prova de amor",
	"					 Em A",
	"Com o vinho e com o pão,",
	"				D  Bm",
	"ofertemos ao Senhor",
	"				   Em   F#7",
	"Nossa vida toda inteira,",
	"				Bm  (B7)",
	"o louvor da criação.",
	" ",
	"Refrão:",
	"Bm 			 	  Em   F#7 	 Bm",
	"De mãos estendidas  ofertamos",
	"		  		 Em  F#7 	 Bm 	 (B7)",
	"o que de graça  recebemos. (2x)"
];

export const EstePranto = [
	//_________________________________
	"    C    G/B            Am",
	"1. Muito alegre eu te pedi",
	"          C",
	"o que era meu",
	"    F 	   D7 			 G",
	"Partir num sonho tão normal",
	"C 	  G/B",
	"Dissipei meus bens",
	"   Am 		   C",
	"e o coração também",
	"   F 		G 		    C  C7",
	"No fim meu mundo era irreal.",
	" ",
	"Refrão:",
	"F 				 C 		Am",
	"Confiei no teu amor e voltei,",
	" Dm    G 		  C C7",
	"sim aqui é meu lugar",
	"F 					   C",
	"Eu gastei teus bens, ó Pai,",
	"	 A7 Dm 	   G",
	"e te dou este pranto",
	"		   C",
	"em minhas mãos",
	" ",
	"   C 	G/B 	   Am",
	"2. Mil amigos conheci",
	"		  C",
	"disseram adeus",
	"  F 	D7 		   G",
	"Caiu a solidão em mim",
	"C 	 G/B",
	"Um patrão cruel",
	"   Am 			C",
	"levou-me a refletir",
	"    F 		G 				  C C7",
	"Meu pai não trata um servo assim.",
	" ",
	"Refrão:",
	"F 				 C 		Am",
	"Confiei no teu amor e voltei,",
	" Dm    G 		  C C7",
	"sim aqui é meu lugar",
	"F 					   C",
	"Eu gastei teus bens, ó Pai,",
	"	 A7 Dm 	   G",
	"e te dou este pranto",
	"		   C",
	"em minhas mãos",
	" ",
	"	C    G/B 		   Am",
	"3. Nem deixaste-me falar",
	"			C",
	"da ingratidão",
	"	F 	   D7 				  G",
	"Morreu no abraço o mal que eu fiz",
	"C 	  G/B 			 Am",
	"Festa, roupa nova, anel,",
	"			 C",
	"sandália aos pés",
	"    F 	  G 		  C  C7",
	"Voltei à vida, sou feliz.",
	" ",
	"Refrão:",
	"F 				 C 		Am",
	"Confiei no teu amor e voltei,",
	" Dm    G 		  C C7",
	"sim aqui é meu lugar",
	"F 					   C",
	"Eu gastei teus bens, ó Pai,",
	"	 A7 Dm 	   G",
	"e te dou este pranto",
	"		   C",
	"em minhas mãos",
];

export const MaosAbertas = [
	//_________________________________
	"Refrão:",
	" A 	   E       F#m",
	"Nesta prece, Senhor,",
	"A 	   D 	  E",
	"venho Te oferecer",
	"D 		E 		A F#m",
	"O crepitar da chama,",
	"D 	   E 	  A",
	" a certeza de dar",
	" ",
	"A 		  E    F#m",
	"Eu Te ofereço o sol",
	"		   C#m",
	"que brilha forte",
	"  A 		  D 		   E",
	"Te ofereço a dor do meu irmão",
	"D  E A 		 F#m  D",
	"A fé, a esperança e o",
	" E 	  A   E",
	"meu amor.",
	" ",
	"A 		  E 	 F#m",
	"Eu Te ofereço as mãos",
	"		   C#m",
	"que estão abertas",
	"A 		   D 		   E",
	"O cansaço do passo mantido.",
	" D  E  A 		 F#m  D E",
	"Meu grito mais forte de",
	"	A E",
	"louvor.",
	" ",
	"A 		  E  F#m 		  C#m",
	"Eu te ofereço o que vi de belo,",
	"  A 	 D 			  E",
	"No interior dos corações.",
	"D  E A 	 F#m  D   E 	 A",
	"A coragem de me transformar."
];

export const MeuCoracaoEParaTi = [
	//_________________________________
	"E 				    A		 B7",
	"Meu coração é para ti,Senhor.",
	"				    E 		 C#m",
	"Meu coração é para ti, Senhor.",
	"				   F#m 		 B7 ",
	"Meu coração é para ti, Senhor, ",
	"				    E E7",
	"meu coração é para ti.",
	" ",
	"Refrão:",
	"	   A 			 B7",
	"Porque tu me deste a vida,",
	"	   E 			   C#m",
	"porque tu me deste o existir,",
	"	 F#m 				B7",
	"Porque tu me deste o carinho,",
	"		   E 	E7",
	"me deste amor!",
	" ",
	"E 					 A 	  B7",
	"Pão e vinho são pra ti, Senhor.",
	"					  E 	    C#m",
	"Pão e vinho são para ti, Senhor.",
	"					 A		  B7",
	"Pão e vinho são pra ti, Senhor.",
	"					  E E7",
	"Pão e vinho são para ti.",
	" ",
	"Refrão:",
	"	   A 			 B7",
	"Porque tu me deste a vida,",
	"	   E 			   C#m",
	"porque tu me deste o existir,",
	"	 F#m 				B7",
	"Porque tu me deste o carinho,",
	"		   E 	E7",
	"me deste amor!",
	" ",
	"E 					 A		  B7 ",
	"A minha vida é para ti, Senhor.",
	"					E 		   C#m",
	"A minha vida é para ti, Senhor.",
	"					 A		  B7 ",
	"A minha vida é para ti, Senhor.",
	"					 E E7",
	"A minha vida é para ti.",
	" ",
	"Refrão:",
	"	   A 			 B7",
	"Porque tu me deste a vida,",
	"	   E 			   C#m",
	"porque tu me deste o existir,",
	"	 F#m 				B7",
	"Porque tu me deste o carinho,",
	"		   E 	E7",
	"me deste amor!",
	" ",
	"E 				   A		 B7 ",
	"Meu coração é para ti, Senhor.",
	"					 E       C#m",
	"Meu coração é para ti, Senhor.",
	"					A		 B7 ",
	"Meu coração é para ti, Senhor.",
	"					E E7",
	"Meu coração é para ti.",
	" ",
	"Refrão:",
	"	   A 			 B7",
	"Porque tu me deste a vida,",
	"	   E 			   C#m",
	"porque tu me deste o existir,",
	"	 F#m 				B7",
	"Porque tu me deste o carinho,",
	"		   E 	E7",
	"me deste amor!"
];

export const MinhaVidaTemSentido = [
	//_________________________________
	"       D    A7 	  D    Bm",
	"Minha vida tem sentido",
	"	  	 Em 			 A7 		  D",
	"cada vez que eu venho aqui",
	"						 A7 	  D  	 Bm",
	"E te faço o meu pedido",
	"	  			Em 	  A7 	    D",
	"de não me esquecer de Ti.",
	" ",
	"	  	 D 			   			 A7",
	"Meu amor é como este pão",
	"		  		 D  Bm",
	"que era trigo",
	"			   				Em  A7 					 D",
	"que alguém plantou 	depois colheu",
	"						 							A7",
	"E depois tornou-se salvação",
	"		   		 	 D   Bm",
	"e deu mais vida",
	"				 Em  A7 		  	D",
	"e alimentou	  o povo meu.",
	" ",
	"Refrão:",
	" D            G    A7",
	"Eu te ofereço este pão.",
	"				G 	A D",
	"Eu te ofereço o meu amor. (2x)",
	" ",
	"	   		D 	 A7 	  D",
	"Minha vida tem sentido",
	" Bm 	  	 Em 			 A7 	   D",
	"cada vez que eu venho aqui",
	"						 A7 	  D",
	"E te faço o meu pedido",
	"Bm 			 		Em 		 A7      D",
	"de não me esquecer de Ti.",
	" ",
	"	  	 D 			  			 A7",
	"Meu amor é como este vinho",
	"		 			 D   Bm",
	"que era fruto",
	"			   				Em  A7 					 D",
	"que alguém plantou 	depois colheu",
	"												 A7",
	"E depois encheu-se de carinho",
	"						 D   Bm",
	"e deu mais vida",
	"	 	  Em  A7 	   		D",
	"e saciou 	o povo meu.",
	" ",
	"Refrão:",
	"D 						G 				A7",
	"Eu te ofereço vinho e pão.",
	" 								G   A D",
	"Eu te ofereço o meu amor. (2x)"	
];

export const NesteAltar = [
	//_________________________________
	"		 D 		  G",
	"Neste altar onde tudo",
	" ",
	"se renova eu quero",
	"Bm 			 F#m 		 G",
	"toda a minha vida nesta hora",
	" A",
	"ofertar (2x)",
	"		 Bm             A",
	"O meu cansaço, a minha dor,",
	"		  G                A",
	"o meu trabalho, o meu clamor.",
	" ",
	"Refrão:",
	"           Bm         A",
	"Recebe, Senhor, uma oferta de amor",
	"   G",
	"É tudo o que eu tenho,",
	"   A",
	"é tudo o que eu sou",
	"  Bm",
	"Recebe, Senhor,",
	"		A",
	"tudo é para o Teu louvor",
	"  G 						 A",
	"Aceita e transforma a minha vida",
	" 			   Bm     A G A",
	"Como o pão e o vinho.",
	" ",
	"         D        G",
	"Neste altar onde tudo",
	" ",
	"se renova eu quero",
	"Bm 			 F#m 		 G",
	"toda a minha vida nesta hora",
	"  A",
	"ofertar (2x)",
	"         Bm             A ",
	"Minha alegria, o meu cantar,",
	"			G                   A",
	"minhas conquistas, o meu caminhar.",
	" ",
	"Refrão:",
	"           Bm         A",
	"Recebe, Senhor, uma oferta de amor",
	"   G",
	"É tudo o que eu tenho,",
	"   A",
	"é tudo o que eu sou",
	"  Bm",
	"Recebe, Senhor,",
	"		A",
	"tudo é para o Teu louvor",
	"  G 						 A",
	"Aceita e transforma a minha vida",
	" 			   Bm     A G A",
	"Como o pão e o vinho."
];

export const SabesSenhor = [
	//_________________________________
	"Refrão:",
	"D 		   Em",
	"Sabes, Senhor,",
	"	  A 		  A7 		 D",
	"o que temos é tão pouco pra dar.",
	"D 		 Em",
	"Mas este pouco",
	"		A 			   G 			 D",
	"nós queremos com os irmãos compartilhar",
	" ",
	"	  G 		  Em",
	"1. Queremos nesta hora,",
	" F#m 		  Bm",
	"diante dos irmãos",
	"	 G 		  Em",
	"Comprometer a vida,",
	"	 A 		  D  (A)",
	"buscando a união.",
	" ",
	"Refrão:",
	"D 		   Em",
	"Sabes, Senhor,",
	"	  A 		  A7 		 D",
	"o que temos é tão pouco pra dar.",
	"D 		 Em",
	"Mas este pouco",
	"		A 			   G 			 D",
	"nós queremos com os irmãos compartilhar",
	" ",
	"	  G 			Em",
	"2. Sabemos que é difícil",
	"	F#m 		  Bm",
	"os bens compartilhar",
	" 	 G 		 Em",
	"Mas com a Tua graça,",
	"	A 			  D  (A)",
	"Senhor, queremos dar.",
	" ",
	"Refrão:",
	"D 		   Em",
	"Sabes, Senhor,",
	"	  A 		  A7 		 D",
	"o que temos é tão pouco pra dar.",
	"D 		 Em",
	"Mas este pouco",
	"		A 			   G 			 D",
	"nós queremos com os irmãos compartilhar",
	" ",
	"	  G 		Em",
	"3. Olhando Teu exemplo,",
	"   F#m 			  Bm",
	"Senhor, vamos seguir",
	"   G 			Em",
	"Fazendo o bem a todos,",
	"	A 		 D  (A)",
	"sem nada exigir.",
	" ",
	"Refrão:",
	"D 		   Em",
	"Sabes, Senhor,",
	"	  A 		  A7 		 D",
	"o que temos é tão pouco pra dar.",
	"D 		 Em",
	"Mas este pouco",
	"		A 			   G 			 D",
	"nós queremos com os irmãos compartilhar"
];

export const SobeAJerusalem = [
	//_________________________________
	" D 			  Bm",
	"Sobe a Jerusalém,",
	"		  G 	A7 	  D",
	"Virgem oferente sem igual.",
	" F#7 			  Bm",
	"Vai apresenta ao Pai",
	"		    E 		   E7 		A7",
	"teu menino: Luz que chegou no Natal.",
	"D 			   Bm",
	"E Junto à tua cruz",
	"			   G 	  A7 	D",
	"quando Deus morrer fica de pé.",
	"F#7 		   Bm",
	"Sim Ele te Salvou,",
	"			E7 		 A7",
	"mas O ofereceste por nós",
	"		  D",
	"com toda fé.",
	" ",
	"Nós vamos renovar",
	"este sacrifício de Jesus:",
	"Morte e ressurreição,",
	"vida que brotou de sua oferta na cruz",
	"Mãe vem nos ensinar",
	"a fazer da vida uma oblação",
	"Culto agradável a Deus",
	"é fazer a oferta do próprio coração."
];