export let CristoJovem = [
    //_________________________________
    "C                        Em",
    "Ven hermano y cántale a Cristo, a",
    "           F",
    "ese Cristo joven que un día nos",
    "      G  C",
    "redimió. Haz de tu amor una",
    "      Em                    F",
    "plegaria o un simple canto alegre",
    "                     G",
    "que el Señor escuchará.",
    " ",
    "Refrão:",
    "       C         Em         F",
    "Ven aquí, canta ya, no te olvides",
    "        G",
    "tu de Cristo.",
    "        C         Em",
    "Piensa que en la cruz, por",
    "   F            G",
    "nosotros El se dio.",
    " ",
    "       C                     Em",
    "No te alejes del camino marcado,",
    "                   F",
    "que Cristo ha señalado para",
    "              G       C",
    "acercarnos a El. Devuélvele con fe",
    "           Em",
    "inquebrantable ese amor",
    "           F",
    "incuestionable que nos ha ofrecido",
    " G",
    "El."
];

export let ConstrutoresDeHistoria = [
    "Refrão:",
    "Bm      A      D  G       A",
    "Dá-nos um coração grande para",
    "  D",
    "amar,",
    "Bm      A       D G       A",
    "Dá-nos um coração jovem para",
    "   Bm",
    "lutar.",
    "Bm      A           D",
    "Homens novos, criadores da",
    " 		 A ",
    " história,",
    "D       G       A            D ",
    "Construtores da nova humanidade",
    "        G         A",
    "Homens novos que vivem a",
    "        D",
    " existência",
    "Bm      G                     F# ",
    "Como o risco de um longo caminhar ",
    " ",
    "Refrão:",
    "Bm      A      D  G       A",
    "Dá-nos um coração grande para",
    "  D",
    "amar,",
    "Bm      A       D G       A",
    "Dá-nos um coração jovem para",
    "   Bm",
    "lutar.",
    " ",
    "2. Homens novos, lutando em esperança, Caminhantes, sedentos da verdade Homens novos, sem freios nem corrente, Homens livres que exigem liberdade",
    " ",
    "Refrão:",
    "Bm      A      D  G       A",
    "Dá-nos um coração grande para",
    "  D",
    "amar,",
    "Bm      A       D G       A",
    "Dá-nos um coração jovem para",
    "   Bm",
    "lutar.",
    " ",
    "3. Homens novos herdeiros da missão, portadores do fogo dos primeiros Homens novos construindo história instrumentos para um mundo melhor",
    " ",
    "Refrão:",
    "Bm      A      D  G       A",
    "Dá-nos um coração grande para",
    "  D",
    "amar,",
    "Bm      A       D G       A",
    "Dá-nos um coração jovem para",
    "   Bm",
    "lutar.",
    " ",
    "4. Homens novos amando sem fronteiras, Muito cima de raça e lugar Homens novos ao lado dos pobres, Partilhando com eles teto e pão.",
    " ",
    "Refrão:",
    "Bm      A      D  G       A",
    "Dá-nos um coração grande para",
    "  D",
    "amar,",
    "Bm      A       D G       A",
    "Dá-nos um coração jovem para",
    "   Bm",
    "lutar.",
];

export let DeixaALuzDoCeuEntrar = [
    "       D",
    "Tu anseias , eu bem sei , por",
    "       A",
    "salvação",
    "       Em         A            D",
    "tens desejo de banir a escuridão",
    "       D7",
    "abre, pois, de par em par teu",
    " G   Gm",
    " coração",
    "  D      Bm       Em A D A7",
    "e deixa a luz do céu entrar",
    "  D                   A",
    " ",
    "Refrão:",
    "Deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " Em             A       D ",
    "deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " D7                       G    Gm",
    "abre bem as portas do teu coração",
    " D         Bm     Em A   D",
    "e deixa a luz do céu entrar",
    " ",
    "Cristo a luz do céu , em ti quer habitar para as trevas do pecado dissipar, teu caminho e coração iluminar e deixa a luz do céu entrar",    " ",
    " ",
    "Refrão:",
    "Deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " Em             A       D ",
    "deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " D7                       G    Gm",
    "abre bem as portas do teu coração",
    " D         Bm     Em A   D",
    "e deixa a luz do céu entrar",
    " ",
    "Que alegria andar ao brilho dessa luz vida eterna e paz no coração produz Oh! Aceita agora o salvador Jesus",    " ",
    "Refrão:",
    "Deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " Em             A       D ",
    "deixa a luz do céu entrar (deixa a luz do céu entrar)",
    " D7                       G    Gm",
    "abre bem as portas do teu coração",
    " D         Bm     Em A   D",
    "e deixa a luz do céu entrar",
];

export let DeusTrino = [
    "Refrão:",
    "           G G7             C  Am",
    "Em nome do Pai, em nome do Filho,",
    "                G    D",
    "Em nome do Espírito Santo",
    "           G  (G7)",
    "estamos aqui (bis)",
    " ",
    "         C           D        G",
    "Para louvar e agradecer bendizer",
    "D/F# Em",
    "e adorar",
    "           C         D",
    "Estamos aqui, Senhor, ao teu",
    "    G      Dm",
    "dispor.",
    "G7       C           D        G",
    "Para louvar e agradecer bendizer",
    "D/F#  Em",
    "e adorar",
    "         C D                G",
    "Te aclamar, Deus trino de amor",
];

export let Emaus = [
    "     D 	              G",
    "Caminhando no horizonte vemos",
    "     D	           A",
    "um vazio por não ver a ti",
    "     Bm	      G",
    "Impossível caminhar se não",
    "	Em   A",
    "estás aqui.",
    "Nossos pés estão cansados,",
    "nossos braços sem forças pra lutar.",
    "Nossas almas com esperança de te",
    "encontrar.",
    " ",
    "Refrão:",
    "D           A",
    "Fica conosco Senhor,",
    "Bm         C  A   A7",
    "faz tua morada em nós.",
    "D         G",
    "Incendeia nossos corações",
    "         Em                 A",
    "e nos dá um espírito de paz (Bis)",
    "    D",
    " ",
    "Senhor.",
    "Obrigado Jesus por estar aqui,",
    "no altar reunidos com os irmãos.",
    "Na partilha do pão, no abraço e em",
    "união.",
    " ",
    "Refrão:",
    "D           A",
    "Fica conosco Senhor,",
    "Bm         C  A   A7",
    "faz tua morada em nós.",
    "D         G",
    "Incendeia nossos corações",
    "         Em                 A",
    "e nos dá um espírito de paz (Bis)",
    "    D",
    "Senhor.",
];

export let EsAguaViva = [
    "E",
    "Eu te peço desta água que Tu tens,",
    "        E/G#         F#m",
    "és água viva meu Senhor.",
    "                              B",
    "Tenho sede e tenho fome de amor",
    "                                E",
    "e acredito nesta fonte de onde vens.",
    " ",
    "Vens de Deus, está em Deus,",
    "                         E/G#",
    "também és Deus e Deus contigo faz",
    "    F#m",
    "um só.",
    " ",
    "Eu, porém, que vim da terra e volto ao pó,",
    "         B",
    "quero viver eternamente",
    "         E",
    "ao lado Teu.",
    " ",
    "Refrão:",
    "        F#m B7        E",
    "És água viva, és vida nova.",
    "      F#m        B7          E",
    "E todo dia me batizas outra vez.",
    "        F#m      B7         E",
    "Me fazes renascer, me fazes reviver.",
    "        F#m         B7            E",
    "Eu quero água desta fonte de onde vens.",
];

export let Estandarte = [
    "Intro.: G Em Am G",
    " ",
    " G",
    "Señor que vas delante,",
    "               D/F#",
    "me invitas a seguirte",
    "        Em",
    "una vez más en todas partes.",
    "                     D      Am",
    "Transforma mis caídas en un fuego que",
    "Am7+         Am7          Bm",
    "levante las fuerzas de mi alma,",
    "          Am           Am7+",
    "Y que se eleve el Estandarte",
    "   C          D",
    "de tu sonrisa en",
    "       G",
    "mi Corazón.",
    " ",
    "Camino en la Sorpresa, seguro de Victoria",
    " ",
    "porque creo sin certezas",
    " ",
    "Que siempre has sido Tú, y siempre tocarás",
    " ",
    "mi puerta, amándome por todo;",
    " ",
    "y no sólo por mi entrega. Hoy vengo a regalarme",
    " ",
    "como Soy",
    "C        G/B        Am G",
    "Y cuando dude te veré",
    " ",
    "en los niños que confían sin temer,",
    " ",
    "En un hombre, un mujer, en un hogar.",
    "C    G/B              Am",
    "En la juventud que al mundo",
    "          D B7",
    "quiere cambiar.",
    " ",
    "Refrão:",
    "E              F#m",
    "Caminar sin mirar atrás,",
    "      A            E C#m B7 E",
    "caminar sobre el mar.",
    " ",
    "Caminar para regalar una nueva oportunidad.",
    " ",
    "Caminar y por fin soltar lo que no me deja volar.",
    "E                    F#m",
    "Todo es posible si delante vas,",
    "      A            C D G",
    "el camino vas a mostrar.",
    " ",
    "Saldremos a anunciarte, llevamos con nosotros",
    " ",
    "tres colores admirables.",
    " ",
    "Es ella nuestra estrella, nuestro sello",
    " ",
    "imborrable, milagro silencioso,",
    " ",
    "nuestro faro en este viaje, la Mater nos conducirá",
    " ",
    "hacia vos",
];

export let EuVenhoDoSulEDoNorte = [
    "   Dm",
    "Eu venho do Sul e do Norte",
    "                A",
    "Do Oeste e do Leste,",
    "Dm",
    "de todo o lugar.",
    " ",
    "Estrada da vida eu percorro,",
    "             A              Dm D7",
    "levando socorro a quem precisar.",
    "   Gm",
    "Assunto de paz é meu forte,",
    " ",
    "eu cruzo montanhas",
    "          Dm    D7",
    "e vou aprender.",
    " Gm                 Dm",
    "O mundo não me satisfaz,",
    "                    A",
    "o que eu quero é a paz",
    "                   Dm D7 ",
    "o que eu quero é viver.",
    "  Gm                 Dm",
    " ",
    "Refrão:",
    "No peito eu levo uma cruz,",
    "  Gm      Dm          A      Dm",
    "no meu coração, o que disse Jesus. (2x)",
    " ",
    "1- Eu sei que eu não tenho idade da maturidade",
    "de quem já viveu, mas sei que eu já tenho a",
    "idade de ver a verdade o que eu quero é ser eu.",
    "O mundo ferido e cansado de um negro passado",
    "de guerras sem fim, tem medo da bomba que",
    "fez, a fé que desfez mas aponta pra mim.",
    " ",
    "Refrão:",
    "No peito eu levo uma cruz,",
    "  Gm      Dm          A      Dm",
    "no meu coração, o que disse Jesus. (2x)",
    " ",
    "2- Eu venho trazer meu recado, não tenho",
    "passado mais sei entender. Um jovem foi",
    "crucificado por ter ensinado a gente a viver.",
    "Eu grito ao meu mundo descrente que eu",
    "quero ser gente, que eu creio na cruz. Eu",
    "creio na força do jovem que segue o caminho",
    "de Cristo Jesus",
    " ",
    "Refrão:",
    "No peito eu levo uma cruz,",
    "  Gm      Dm          A      Dm",
    "no meu coração, o que disse Jesus. (2x)",
];

export let FicaSempre = [
    "Refrão:",
    "     C                     F",
    "Fica sempre um pouco de perfume",
    "     G",
    "nas mãos que oferecem rosas",
    "                             C   G",
    "Nas mãos que sabem ser generosas.",
    " ",
    " C",
    "Dar o pouco que se tem",
    "                  F",
    "ao que tem menos ainda",
    "                G",
    "Enriquece o doador.",
    "                        C     G",
    "Faz sua alma ainda mais linda.",
    " ",
    "Refrão:",
    "     C                     F",
    "Fica sempre um pouco de perfume",
    "     G",
    "nas mãos que oferecem rosas",
    "                             C   G",
    "Nas mãos que sabem ser generosas.",
    " ",
    " C",
    "Dar ao próximo alegria parece",
    "                F",
    "coisa tão singela",
    "G",
    "Aos olhos de Deus, porém,",
    "                     C    G",
    "é das artes a mais bela.",
];

export let FicoFeliz = [
    "C              F",
    "Fico feliz em vir em tua casa,",
    "    C                  G",
    "erguer minha voz e cantar (aleluia)",
    "C              F",
    "Fico feliz em vir em tua casa,",
    "    C          G         C  (G)",
    "erguer minhas mãos e adorar",
    "    C                  F",
    "Bendito é o nome do Senhor",
    "    C                  G",
    "Bendito é o nome do Senhor",
    "    C                  F",
    "Bendito é o nome do Senhor",
    "    G    C    (G)",
    "Pra sempre",
    "    F    C",
    "Pra sempre",
];

export let HojeETempoDeLouvarADeus = [  
    //_________________________________
    "D            G  A         D  G A",
    "Hoje é tempo de louvar a Deus",
    "D               G          A",
    "Em nós agora habita Seu Espírito",
    "     G     A     D",
    "E então é só cantar",
    "       G   A     D",
    "e a Cristo exaltar",
    "       G            Em       C A",
    "E Sua glória encherá esse lugar.",
    "         D      G    D  A",
    " ",
    "Refrão:",
    "Vem louvar (vem louvar). (2x)",
    " ",
    "    D            G A",
    "No meio dos louvores",
    "        D      G A",
    "Deus habita.",
    "   D              G              A",
    "É Seu prazer cumprir o que nos diz.",
    "      G    A      D",
    "E então é só cantar,",
    "      G    A     D",
    "e a Cristo exaltar",
    "       G           Em",
    "E sua glória encherá",
    "         C   A",
    "esse lugar",
    " ",
    "Refrão:",
    "         D      G     D A",
    "Vem louvar (vem louvar)(2x)",
    "         D        G      D A",
    "Glória a Deus (glória a Deus)(2x)",
    "   D",
    "Amém.",
];

export let PovoDeDeus = [
    //_________________________________
    "           E                 B7",
    "O povo de Deus no deserto andava",
    "          F#m    B7           E",
    "Mas à sua frente alguém caminhava",
    "          E                 B7",
    "O povo de Deus era rico de nada",
    "             F#m     B7",
    "Só tinha esperança e ",
    "           E    E7",
    "o pó da estrada",
    " ",
    "Refrão:",
    "                A          B7",
    "Também sou teu povo, Senhor,",
    "                 E     C#m",
    "e estou nessa estrada",
    "              F#m  B7",
    "Somente a tua graça",
    "                E       E7",
    "me basta e mais nada. (bis)",
    " ",
    "O povo de Deus também vacilava",
    "Às vezes custava a crer no amor.",
    "O povo de Deus, chorando, rezava",
    "Pedia perdão e recomeçava",
    " ",
    "Refrão:",
    "                A          B7",
    "Também sou teu povo, Senhor,",
    "                 E     C#m",
    "e estou nessa estrada",
    "              F#m  B7",
    "Somente a tua graça",
    "                E       E7",
    "me basta e mais nada. (bis)",
];

export let OracaoPelaFamilia = [
    //_________________________________
    "       C",
    "Que nenhuma família",
    "                         G",
    "comece em qualquer de repente.",
    "       Dm",
    "Que nenhuma família",
    "    G7                  C",
    "termine por falta de amor.",
    "         C",
    "Que o casal seja um para o outro",
    "                G",
    "de corpo e de mente.",
    "      Dm",
    "E que nada no mundo",
    "   G7                  C",
    "separe um casal sonhador!",
    " ",
    "Refrão:",
    "      C",
    "Que nenhuma família",
    "                       G",
    "se abrigue debaixo da ponte.",
    "         Dm               G7",
    "Que ninguém interfira no lar",
    "                 C",
    "e na vida dos dois.",
    " ",
    "Que ninguém os obrigue a viver",
    "                G",
    "sem nenhum horizonte.",
    "          Dm",
    "Que eles vivam do ontem,",
    "   G7                      C",
    "do hoje em função de um depois!",
    "          C               Am",
    "Que a família comece e termine",
    "              Dm",
    "sabendo onde vai.",
    "        G                  G7",
    "E que o homem carregue nos ombros",
    "               C     G7",
    "a graça de um pai.",
    "          C                    Am",
    "Que a mulher seja um céu de ternura,",
    "               Dm",
    "aconchego e calor",
    "          C                G7",
    "E que os filhos conheçam a força",
    "               C   G7",
    "que brota do amor!",
    "     C                          G",
    "Abençoa, Senhor, as famílias. Amém.",
    "            Dm      G7       C",
    "Abençoa, Senhor, a minha também. (2x)",
    " ",
    "Que marido e mulher tenham força de amar sem medida.",
    "Que ninguém vá dormir sem pedir ou sem dar seu perdão.",
    "Que as crianças aprendam no colo, o sentido da vida.",
    "Que a família celebre a partilha do abraço e do pão!",
    " ",
    "Refrão:",
    "      C",
    "Que nenhuma família",
    "                       G",
    "se abrigue debaixo da ponte.",
    "         Dm               G7",
    "Que ninguém interfira no lar",
    "                 C",
    "e na vida dos dois.",
    " ",
    "Que ninguém os obrigue a viver",
    "                G",
    "sem nenhum horizonte.",
    "          Dm",
    "Que eles vivam do ontem,",
    "   G7                      C",
    "do hoje em função de um depois!",
    "          C               Am",
    "Que a família comece e termine",
    "              Dm",
    "sabendo onde vai.",
    "        G                  G7",
    "E que o homem carregue nos ombros",
    "               C     G7",
    "a graça de um pai.",
    "          C                    Am",
    "Que a mulher seja um céu de ternura,",
    "               Dm",
    "aconchego e calor",
    "          C                G7",
    "E que os filhos conheçam a força",
    "               C   G7",
    "que brota do amor!",
    "     C                          G",
    "Abençoa, Senhor, as famílias. Amém.",
    "            Dm      G7       C",
    "Abençoa, Senhor, a minha também. (2x)",
    "",
    "Que marido e mulher não se traiam nem traiam seus filhos.",
    "Que o ciúme não mate a certeza do amor entre os dois.",
    "Que no seu firmamento a estrela que tem maior brilho",
    "Seja a firme esperança de um céu aqui mesmo e depois!",
    " ",
    "Refrão:",
    "      C",
    "Que nenhuma família",
    "                       G",
    "se abrigue debaixo da ponte.",
    "         Dm               G7",
    "Que ninguém interfira no lar",
    "                 C",
    "e na vida dos dois.",
    " ",
    "Que ninguém os obrigue a viver",
    "                G",
    "sem nenhum horizonte.",
    "          Dm",
    "Que eles vivam do ontem,",
    "   G7                      C",
    "do hoje em função de um depois!",
    "          C               Am",
    "Que a família comece e termine",
    "              Dm",
    "sabendo onde vai.",
    "        G                  G7",
    "E que o homem carregue nos ombros",
    "               C     G7",
    "a graça de um pai.",
    "          C                    Am",
    "Que a mulher seja um céu de ternura,",
    "               Dm",
    "aconchego e calor",
    "          C                G7",
    "E que os filhos conheçam a força",
    "               C   G7",
    "que brota do amor!",
    "     C                          G",
    "Abençoa, Senhor, as famílias. Amém.",
    "            Dm      G7       C",
    "Abençoa, Senhor, a minha também. (2x)",
];

export let SenhorERei = [
    //_________________________________
    "Refrão:",
    "Em",
    "O Senhor é Rei,",
    "G                        D",
    "o Senhor é meu Pastor e Rei (2x)",
    " ",
    "Em",
    "O Senhor está no céu,",
    "G",
    "o Senhor está no mar,",
    "D                   Em",
    "na extensão do infinito.",
    " ",    
    "Refrão:",
    "G           D            Em",
    "Está no céu, está no mar,",
    "            C          D",
    "na extensão do infinito. (2x)",
    " ",
    "Quando eu vacilar, eu não temerei,",
    "pois o Senhor está comigo",
];

export let PorqueEleVive = [
    //_________________________________
    "D7       G  G7          C",
    "Deus enviou seu Filho amado",
    "        G Em          Am D7",
    "Para morrer no meu lugar",
    "           G G7              C",
    "Na cruz pagou por meus pecados",
    "         G        Em   Am",
    "Mas o sepulcro vazio está",
    "       D7   G   D7",
    "porque Ele vive",
    "            G  G7",
    "Porque Ele vive,",
    " ",
    "Refrão:",
    "                  C",
    "eu posso crer no amanhã.",
    "            G  Em          Am D7",
    "Porque Ele vive, temor não há.",
    "            G G7            C",
    "Mas eu bem sei que o meu futuro",
    "          G       Em    Am",
    "Está nas mãos do meu Jesus,",
    "     D7     G  D7",
    "que vivo está.",
    " ",
    "D7         G         C",
    "Um dia eu vou cruzar os rios",
    "            G Em           Am D7",
    "E verei então, um céu de luz",
    "             G G7             C",
    "E verei que lá, em plena glória,",
    "       G   Em",
    "Vitorioso, vive",
    "  Am       D7    G  D7",
    "e reina o meu Jesus",    
    " ",
    "Refrão:",
    "                  C",
    "eu posso crer no amanhã.",
    "            G  Em          Am D7",
    "Porque Ele vive, temor não há.",
    "            G G7            C",
    "Mas eu bem sei que o meu futuro",
    "          G       Em    Am",
    "Está nas mãos do meu Jesus,",
    "     D7     G  D7",
    "que vivo está.",
];

export let QuieroCantar = [
    //_________________________________
    " A                  D       E",
    "Quiero cantar y elevarte mi voz",
    "  A                 D       E",
    "Quiero llegar hasta tu corazón",
    "            F#m",
    "Porque el tiempo",
    "                    C#m",
    "ha encontrado sus caminos,",
    "         D               E",
    "Porque llega la noche y tengo frio",
    "       A                   E",
    "Porque has renovado las promesas",
    "       C#7                 F#m",
    "Porque has escogido mis flaquezas",
    "       D",
    "Porque en el desierto",
    "       C#7",
    "No te alaban los muertos",
    "      F#m",
    "Solamente los vivos",
    "    D         E       A   D  E",
    "Los vivos te alaban Señor",
    "  A                 D        E",
    "Vuelvo a cantar con toda mi voz",
    "  A",
    "Vuelvo a entregar",
    "      D       E",
    "mi ofrenda de amor",
    "F#m              C#m",
    "Soy peregrino y camino",
    " D               E",
    "Soy mensajero para tu pueblo."
];

export let ReunidosAqui = [
    //_________________________________
    "  F",
    "Reunidos aqui ",
    "                  Bb",
    "só pra louvar o Senhor,",
    "            C7        F  C",
    "novamente aqui, em união.",
    "     F",
    " ",
    "Refrão",
    "Algo bom vai acontecer,",
    "     F7            Bb",
    "algo bom Deus tem para nós.",
    "         C7",
    "Reunidos aqui",
    "              F",
    "só pra louvar o Senhor.",
    " ",
    "    F",
    "O Pai uniu-nos aqui,",
    "                  Bb",
    "pra celebrar seu amor",
    "                 C7           F C",
    "Para pedirmos perdão e agradecer."
];

export let SalmoDeLaCreacion = [
    //_________________________________
    "Intr. A E F#m C#m D A E",
    " ",
    "A        E      F#m D",
    "Por tu océano azul",
    "                 E",
    "y las aguas Del mar,",
    "A        E        F#m  D",
    "por todo el continente",
    " ",
    "y los ríos que van",
    "F#m              D   F#m",
    "Por el fuego que dice,",
    "               D",
    "como arbusto ardiente",
    "Bm              E    Bm",
    "por el ala del viento,",
    "        E",
    "quiero gritar:",
    " ",
    "Refrão:",
    "    A        E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                   F#m",
    "Dios viviente e inmenso,",
    "D                    E ",
    "Tú eres el Dios de amor.",
    "    A         E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                  F#m	",
    "Dios viviente e inmenso,",
    "E                           A E",
    "Dios presente en toda creación.",
    "F#m C#m D A E",
    " ",
    "Y por los animales de la tierra y el agua",
    "por el canto del ave y el cantar de la vida.",
    "Por el hombre que hiciste semejante a Ti",
    "y por todos sus hijos, quiero gritar:",    
    " ",
    "Refrão:",
    "    A        E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                   F#m",
    "Dios viviente e inmenso,",
    "D                    E ",
    "Tú eres el Dios de amor.",
    "    A         E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                  F#m	",
    "Dios viviente e inmenso,",
    "E                           A E",
    "Dios presente en toda creación.",
    "F#m C#m D A E",
    " ",
    "Por la mano tendida que te invita a la danza",
    "por el beso que brota al surgir la esperanza,",
    "La mirada de amor que levanta e reanima",
    "por el vino y el pan, quiero gritar:",
    " ",
    "Refrão:",
    "    A        E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                   F#m",
    "Dios viviente e inmenso,",
    "D                    E ",
    "Tú eres el Dios de amor.",
    "    A         E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                  F#m	",
    "Dios viviente e inmenso,",
    "E                           A E",
    "Dios presente en toda creación.",
    "F#m C#m D A E",
    " ",
    "Y por los animales de la tierra y el agua",
    "por el canto del ave y el cantar de la vida.",
    "Por el hombre que hiciste semejante a Ti",
    "y por todos sus hijos, quiero gritar:",    
    " ",
    "Refrão:",
    "    A        E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                   F#m",
    "Dios viviente e inmenso,",
    "D                    E ",
    "Tú eres el Dios de amor.",
    "    A         E",
    "Mi Dios (Mi Dios),",
    "                    F#m D",
    "Tú eres grande y hermoso,",
    "                  F#m	",
    "Dios viviente e inmenso,",
    "E                           A E",
    "Dios presente en toda creación.",
    "F#m C#m D A E"
];

export let SenhorQuemEntrara = [
    //_________________________________
    " ",
    "Refrão:",
    "C Am Dm",
    "Senhor, quem entrará no Santuário",
    "G C",
    "pra te louvar? (bis)",
    " ",
    "C7 F",
    "Quem tem as mãos limpas",
    "G Em Am",
    "e o coração puro,",
    "Dm G C C7",
    "Quem não é vaidoso e sabe amar. (bis)",
    " ",
    "Refrão:",
    "C Am Dm",
    "Senhor, eu quero entrar no Santuário",
    "G C",
    "pra te louvar! (bis)",
    " ",
    "C7 F G Em Am",
    "Oh! Dá-me mãos limpas e um coração puro,",
    "Dm G C C7",
    "Arranca a vaidade, ensina-me a amar (bis)",
    " ",
    "Refrão:",
    "C Am Dm",
    "Senhor, já posso entrar no Santuário",
    "G C",
    "pra te louvar! (bis)",
    " ",
    "C7 F G Em Am",
    "Teu sangue me lava, teu fogo me queima",
    "Dm G C C7",
    "O Espírito Santo inunda meu ser. (bis)"
];

export let VamosAdoralo = [
    //_________________________________
    "A     E     F#m       C#m",
    "De mãos dadas como irmãos",
    "D        Bm      E",
    "ao teu encontro vamos Senhor",
    " C#7                     F#m",
    "Cada grão de trigo oferecido",
    "        D      Bm         E",
    "será o pão da nossa comunhão.",
    " C#m         D     Bm         E",
    "A força do amor entrega, compaixão,",
    "  C#m                     D",
    "o canto que alegra o coração",
    "        E",
    "é para ti.",    
    " ",
    "Refrão:",
    "C#7       F#m E D",
    "  Vamos adorá–lo temos",
    "      C#7     F#m E  D  C#7 ",
    "um tesouro para dar.",
    "       A  E          F#m C#m",
    "Que Maria seja nossa estrela",
    "    D     G       E",
    "e guie nosso caminhar.",
    "C#7       F#m E D",
    " Somos a terra",
    "    C#7      F#m E  D ",
    "que ela escolheu.",
    "C#7          A    E      F#m C#m ",
    "Vamos ser fiéis a nossa missão",
    "          D               E",
    "que este fogo que todos levamos,",
    "     C#7          F#m",
    "arda sempre, arda mais,",
    "       D           E         A",
    "arda imenso para o mundo iluminar",
    "       D    E",
    "arda imenso",
    "                 A E F#m C#m D E A",
    "para o mundo iluminar.",
];
