export const HinoDoPeregrino = [
  //_________________________________
  'Refrão:',
  'G           Em        D     G',
  'De todos os cantos do nosso país,',
  '              Em',
  'mãos dadas com o Pai',
  '      Bm     Em',
  'vamos peregrinar.',
  'Dm G7    C        D         G',
  'Unidos à Mãe na Aliança de Amor,',
  '    Em          Am',
  'juventude de Schoenstatt',
  '   D         G D',
  'do Brasil Tabor.',
  ' ',
  'G          Em       G',
  'Vem vamos juntos ao Lar,',
  '        Em       G',
  'a nossa Terra Natal,',
  '        Em        G',
  'onde se forjam heróis.',
  ' C       D           G',
  'Olha a estrela a brilhar.',
  ' ',
  'Vem vamos juntos ao Lar,',
  'juntos com Pai – Fundador,',
  'viemos para adorar',
  'Cristo o Rei e Senhor.',
  ' ',
  'Refrão:',
  'Em    C',
  'Ô, Brasil Tabor',
  'D              G',
  'Juventude de Schoenstatt.',
  'Em    C         D        G',
  'Ô, Brasil Tabor estamos aqui.',
  ' ',
  'Vem, vamos juntos ao Lar.',
  'Vem Lírios presentear.',
  'Filhas heróicas do Pai,',
  'pura Ver Sacrum de Amor.',
  ' ',
  'Vem, vamos juntos ao Lar.',
  'Vamos nos passos do herói.',
  'Fogo ardente que',
  'faz um novo homem surgir.'
];

export const IeIeIeDeJesus = [
  //_________________________________
  'Intr: (D G A G)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)',
  ' ',
  'D G A G D G / A / G',
  'Reza, Reza, Reza. Nós Rezaremos (2x)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)',
  ' ',
  'Louva, Louva, Louva, Nós Louvaremos (2x)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)',
  ' ',
  'Corre, Corre, Corre, Nós Correremos (2x)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)',
  ' ',
  'Pula, Pula, Pula, Nós Pularemos (2x)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)',
  ' ',
  'Grita, Grita, Grita, Nós Gritaremos (2x)',
  ' ',
  'Refrão:',
  ' D           G        A',
  'Iê, Iê, Iê, Iê, Iê, Iê,',
  '         G',
  'Iê, Iê, Iê, Lê, Iê, Iê...',
  'D       G        A       G',
  'Uou, Ou, Ou, Uou, Ou, Uou,',
  'Uou, Ou, Ou, Uou, Ou, Uou... (2x)'
];

export const MadreRemix = [
  //_________________________________
  'C',
  'Madre hoy quiero hablarte',
  '         G',
  'una vez más,',
  '                      F  G',
  'estar cerca de tu corazón',
  'C                            G',
  'Y quiero contarte que ya estoy',
  'en la lucha diaria',
  '         F G         C G F G',
  'por lograr   la santidad.',
  '  C G F G',
  'O, o, o, o',
  'C',
  'El ma va dejando',
  '                G',
  'huellas tras de si,',
  '                               F G',
  'pero Schoenstatt quiero construir',
  '          C G F G',
  'el mundo nuevo.',
  '  C G F G',
  'O, o, o, o'
];

export const MarAdentro = [
  //_________________________________
  'D      G                D',
  'É hora de partir, mar adentro,',
  '                A',
  'eu não vou esperar.',
  'D         G',
  'Ele virá para ir,',
  '       D            A       D',
  'mar à dentro eu não vou esperar.',
  'D       G',
  'Ele está junto a mim e',
  ' D                     A',
  'seus olhos derramam ternura.',
  ' D        G',
  'Ele espera meu sim e eu não',
  'D        A        D',
  'quero fazê-lo esperar.',
  ' ',
  'Refrão:',
  '          D        G',
  'Quero sentir teu amor',
  '        D      A',
  'e voltar a nascer.',
  '        Bm     G',
  'Quero dizer-te vem,',
  '               A',
  'minha barca é tua.',
  '        D       G',
  'É tão imenso o mar',
  '           D     A',
  'mas eu vou com você,',
  '         Bm    G      A',
  'não temo navegar se está',
  '     D   G D A D',
  'meu Deus.',
  ' ',
  'Quero ser como você e ser',
  'pão que se deixa comer.',
  'Quero que os demais vejam',
  'em mim teu sorriso, Senhor.',
  'Quero ser manancial e dar',
  'vida onde quer que eu vá.',
  'Quero levar tua luz a este',
  'mundo que não fala de Deus.',
  ' ',
  'Refrão:',
  '          D        G',
  'Quero sentir teu amor',
  '        D      A',
  'e voltar a nascer.',
  '        Bm     G',
  'Quero dizer-te vem,',
  '               A',
  'minha barca é tua.',
  '        D       G',
  'É tão imenso o mar',
  '           D     A',
  'mas eu vou com você,',
  '         Bm    G      A',
  'não temo navegar se está',
  '     D   G D A D',
  'meu Deus.'
];

export const Misionero = [
  //_________________________________
  'Refrão:',
  'A',
  'Cuando la alegría,',
  '    F#4/E         F#m/E',
  'llega desde arriba',
  '     E',
  'No existen las fronteras,',
  '    D',
  'sólo hay que',
  '        E         G E E7',
  'compartirla (2X)',
  ' ',
  'C#m      G#m  A',
  ' Conoces bien todo lo',
  '    B',
  'que te quiero dar.',
  'C#m        G#m A',
  ' Sabes también  cuál',
  '           B',
  'es mi gran debilidad.',
  'F#m       B',
  ' Hoy me levanto de',
  '    G#m            A',
  'mis miedos por tu amor,',
  'F#m        B',
  ' Es tu mirada y pide',
  '   G#m          A',
  'un nuevo aquí estoy,',
  '   D                C9',
  'Y así descubrir ese fuego',
  '               Bb7+',
  'que grita en el alma:',
  '    E4 E  F#m* G#m*',
  'SOY MI SIONE RO',
  ' ',
  'Refrão:',
  'A',
  'Cuando la alegría,',
  '    F#4/E         F#m/E',
  'llega desde arriba',
  '     E',
  'No existen las fronteras,',
  '    D',
  'sólo hay que',
  '        E         G E E7',
  'compartirla (2X)',
  ' ',
  'C#m      G#m  A',
  ' Toma mi Ser,',
  '           B',
  'y dale sentido al caminar.',
  'C#m      G#m   A',
  ' Quédate aquí,',
  '            B',
  'junta mis manos que no se rezar.',
  'F#m           B',
  ' Cambian los pueblos',
  '     G#m             A',
  'y las calles pero el Sol,',
  'F#m           B',
  '  Sigue alumbrando',
  '          G#m         A',
  'a los que dan su corazón,',
  '   D                   C9',
  'Y quieren vivir de ese fuego',
  '               Bb7+',
  'que grita en el alma:',
  '    E4 E  F#m* G#m*',
  'SOY MI SIONE RO',
  ' ',
  'Refrão:',
  'A',
  'Cuando la alegría,',
  '    F#4/E         F#m/E',
  'llega desde arriba',
  '     E',
  'No existen las fronteras,',
  '    D',
  'sólo hay que',
  '        E         G E E7',
  'compartirla (2X)',
  ' ',
  'F#4/E = 044400',
  'F#m*  = 202200',
  'F#m/E = 044200',
  'G#m*  = 404400',
  'E4    = 022200'
];

export const MissaoJovem = [
  //_________________________________
  '     D                F#m',
  'Chamados a ser instrumento',
  '         G',
  'da Mãe se não formos nós',
  '      A',
  'ninguém mais será.',
  ' D               F#m',
  'Jovens dispostos com alegria',
  '       G           A',
  'o Brasil inteiro a missionar.',
  'Bm                 F#m',
  'A peregrina nos braços levar,',
  '     G                         A',
  'heróis de Schoenstatt a se entregar.',
  ' ',
  'Refrão:',
  '        D Bm',
  'Missão Jovem,',
  '   G           A       D Bm',
  'de jovens que querem amar,',
  '    G         A    F#m    Bm',
  'De jovens que evangelizam jovens',
  '    Em       A7          D A7',
  'e o reino de Deus crescerá',
  ' ',
  'D               F#m',
  'Atrairei os corações juvenis',
  'G                    A',
  'em minhas mãos os educarei.',
  ' D             F#m',
  'No santuário escola de amor,',
  ' G           A',
  'missionários do Tabor.',
  'Bm',
  'Ela é a grande missionária,',
  'F#m   G                  A',
  '  ela milagres realizará.',
  ' ',
  'Refrão:',
  '        D Bm',
  'Missão Jovem,',
  '   G           A       D Bm',
  'de jovens que querem amar,',
  '    G         A    F#m    Bm',
  'De jovens que evangelizam jovens',
  '    Em       A7          D A7',
  'e o reino de Deus crescerá',
  ' ',
  '       D            F#m',
  'Juventude heroica pronta a lutar',
  '  G                      A',
  'com sacrifício homens novos formar.',
  ' D                     F#m',
  'Os caminhos do Pai iremos seguir',
  '    G           A',
  'com liberdade vamos partir.',
  '   Bm',
  'Um filho de Schoenstatt',
  '    F#m',
  'não foge a luta,',
  '    G                 A',
  'confia e se entrega a MTA',
  ' ',
  'Refrão:',
  '        D Bm',
  'Missão Jovem,',
  '   G           A       D Bm',
  'de jovens que querem amar,',
  '    G         A    F#m    Bm',
  'De jovens que evangelizam jovens',
  '    Em       A7          D A7',
  'e o reino de Deus crescerá'
];

export const NaoMeCansoDeCaminhar = [
  //_________________________________
  'F            Bb',
  'Não me canso de caminhar',
  '     F              C',
  'se vou a casa de Jesus.',
  'F            Bb',
  'Não me canso de caminhar,',
  '    F        C         F   D7',
  'se vejo brilhar a Tua Luz.',
  ' ',
  'G            C',
  'Não me canso de caminhar',
  '   G               D',
  'se vou a casa de Jesus.',
  'G            C',
  'Não me canso de caminhar,',
  '   G        D          G  E7',
  'se vejo brilhar a Tua Luz.',
  ' ',
  'A            D',
  'Não me canso de caminhar',
  '   A               E',
  'se vou a casa de Jesus.',
  'A            D',
  'Não me canso de caminhar,',
  '   A        E          A',
  'se vejo brilhar a Tua Luz.'
];

export const NovasTodasAsCoisas = [
  //_________________________________
  'Refrão:',
  ' A                           D',
  'Eis que faço novas todas as coisas,',
  'A',
  'que faço novas todas as coisas,',
  'D',
  'que faço novas todas as coisas.',
  ' ',
  '   A',
  'É vida que brota da vida,',
  '   D',
  'é fruto que cresce do amor,',
  '   A',
  'É vida que vence a morte,',
  '   D',
  'é vida que vem do Senhor.',
  ' ',
  'Refrão:',
  ' A                           D',
  'Eis que faço novas todas as coisas,',
  'A',
  'que faço novas todas as coisas,',
  'D',
  'que faço novas todas as coisas.',
  ' ',
  'Deixei o sepulcro vazio,',
  'a morte não me segurou.',
  'A pedra que então me prendia',
  'no terceiro dia rolou.',
  ' ',
  'Refrão:',
  ' A                           D',
  'Eis que faço novas todas as coisas,',
  'A',
  'que faço novas todas as coisas,',
  'D',
  'que faço novas todas as coisas.',
  ' ',
  'Eu hoje lhe dou vida nova,',
  'renovo em ti o amor.',
  'Lhe dou uma nova esperança,',
  'tudo o que era velho passou.',
  ' ',
  'Refrão:',
  ' A                           D',
  'Eis que faço novas todas as coisas,',
  'A',
  'que faço novas todas as coisas,',
  'D',
  'que faço novas todas as coisas.'
];

export const OMeuLugarEOCeu = [
  //_________________________________
  'Refrão:',
  '                 G',
  'O meu lugar é o céu.',
  '                     D',
  'É lá que eu quero morar.',
  '                 Em  D C',
  'O meu lugar é o céu.',
  '                    Cm',
  'É lá que eu quero morar. (2x)',
  ' ',
  '    Em',
  'Eu sei, não vale a pena tanta grana,',
  'D                       C',
  ' poder, fama, pois isso tudo',
  'aqui vou deixar.',
  '  Em',
  'E sei que lá no céu só chega',
  '     D',
  'aquele que na Terra seus bens',
  'C',
  'soube compartilhar.',
  '    Em              D',
  'Por isso todo o dia, dia-a-dia,',
  'a cada hora eu sei,',
  '  C',
  'com Deus eu posso contar.',
  '    Em',
  'E a cada passo certo que eu der',
  'D',
  'aqui na Terra mais perto',
  'C',
  'd’Ele eu vou ficar.',
  ' ',
  'Refrão:',
  '                 G',
  'O meu lugar é o céu.',
  '                     D',
  'É lá que eu quero morar.',
  '                 Em  D C',
  'O meu lugar é o céu.',
  '                    Cm',
  'É lá que eu quero morar. (2x)',
  ' ',
  '    Em',
  'Eu sei, não vale a pena tanta grana,',
  'D                       C',
  ' poder, fama, pois isso tudo',
  'aqui vou deixar.',
  '  Em',
  'E sei que lá no céu só chega',
  '     D',
  'aquele que na Terra seus bens',
  'C',
  'soube compartilhar.',
  '    Em              D',
  'Por isso todo o dia, dia-a-dia,',
  'a cada hora eu sei,',
  '  C',
  'com Deus eu posso contar.',
  '    Em',
  'E a cada passo certo que eu der',
  'D',
  'aqui na Terra mais perto',
  'C',
  'd’Ele eu vou ficar.',
  ' ',
  'Am                      D',
  'Buscar, bater, saber pedir',
  'Am                G',
  'E até mesmo suplicar',
  'Am                D',
  'Eu tenho um endereço',
  '    G         F   C',
  'No céu vou morar',
  '    G          F  C',
  'Eu tenho um lugar.'
];

export const ONossoGeneral = [
  //_________________________________
  '        Am',
  'Pelo Senhor marchamos sim.',
  'Seu exército poderoso é.',
  '      F          G             Am',
  'Sua glória será vista em toda Terra.',
  ' ',
  '       Am',
  'Vamos cantar o canto da vitória.',
  'Glória a Deus! Vencemos a batalha.',
  '     F          G          Am',
  'Toda arma contra nós perecerá.',
  ' ',
  'Refrão:',
  '   F                C',
  'O nosso general é Cristo,',
  '    F             C',
  'seguimos os seus passos.',
  '     F          G          Am',
  ' ',
  'Nenhum inimigo nos resistirá.',
  'Com o Messias marchamos sim.',
  'E m sua Mão, a chave da vitória.',
  'Nos leva a possuir a terra prometida.'
];

export const SenhorTuaBondade = [
  //_________________________________
  ' G            Bm',
  'Senhor Tua bondade',
  '        Am            D7',
  'se espalhou por toda parte',
  '    G         Bm',
  'Porque acreditamos',
  '      Am          D7',
  'que você é o Salvador.',
  '      G           Bm',
  'Nossa Fé nos dá coragem',
  '       Am                D7',
  'para seguirmos com mais amor.',
  ' ',
  'Refrão:',
  'G       Bm     Am  D7',
  'Cristo, Cristo é você.',
  'G          Bm',
  'Rei do Universo,',
  'Am     D7   G  Bm  Am  D7',
  'Rei do Infinito. Ô, ô, ô, ô,',
  'G            Bm',
  'Quero te Louvar',
  'Am      D7        G',
  'neste encontro de Paz,',
  '   Bm    Am     D7',
  'porque você me deu',
  '   G        Bm   Am  D7',
  'alegria de amar. Ô, ô, ô, ô,',
  '    G        Bm   Am  D7',
  'alegria de amar. Ô, ô, ô, ô,',
  'G  Bm     Am D7',
  'Ô, ô, ô...     (2X)',
  ' ',
  'Senhor nossa alegria',
  'se encontra em Maria,',
  'porque acreditamos',
  'que Ela é fonte da vida.',
  'Teus caminhos nos dão mais fé',
  'para seguirmos com mais amor.',
  ' ',
  'Refrão:',
  'G       Bm     Am  D7',
  'Cristo, Cristo é você.',
  'G          Bm',
  'Rei do Universo,',
  'Am     D7   G  Bm  Am  D7',
  'Rei do Infinito. Ô, ô, ô, ô,',
  'G            Bm',
  'Quero te Louvar',
  'Am      D7        G',
  'neste encontro de Paz,',
  '   Bm    Am     D7',
  'porque você me deu',
  '   G        Bm   Am  D7',
  'alegria de amar. Ô, ô, ô, ô,',
  '    G        Bm   Am  D7',
  'alegria de amar. Ô, ô, ô, ô,',
  'G  Bm     Am D7',
  'Ô, ô, ô...     (2X)'
];

export const SenhoraDeLaLoma = [
  //_________________________________
  'Intro. E F#m G#m A G#m F#m E (2X)',
  ' ',
  '   E            F#m        G#m',
  'Señora estoy aquí en tu morada,',
  '      A               E',
  'una flor traigo en mi alma para',
  '    F#m        B7',
  'entregártela a vos.',
  '       E           E7',
  'Del jardín de mis anhelos',
  '  A             Am',
  'juveniles la corté,',
  '       G#m     C#m    F#m',
  'y es el regalo que quiero',
  '     B7   E   (Intro.)',
  'ofrecerte hoy.',
  ' ',
  'Con ella yo te traigo me pobreza,',
  'mi pequeñez, mi flaqueza,',
  'mi compromiso también.',
  'Cada pétalo cargado',
  'de esperanzas vos verás,',
  'que en el mañana quiero',
  'ser lo que sueñas.',
  ' ',
  'Inútil es huir a tu llamado',
  'cuando hay todo un pasado',
  'que me conduce hacia a vos.',
  'En el mundo ya no puedo hallar',
  'la ruta del amor,',
  'sin tu presencia,',
  'si tu apoyo y tu calor.',
  ' ',
  'Señora, en mi flor te manifestó',
  'con el corazón abierto',
  'que quiero ser para vos.',
  'Generosa renovaste toda tú',
  'confianza en mí,',
  'y consecuente, te digo',
  'como ayer sí.'
];

export const SoltaOCaboDaNau = [
  //_________________________________
  'D',
  'Oh porque duvidar',
  '         G',
  'sobre as ondas do mar',
  '       D         Bm        C   A',
  'quando Cristo o caminho abriu.',
  '       D',
  'Quando forçado és',
  '          G',
  'contra as ondas lutar',
  '      D Bm      Em  A   D  A',
  'seu amor a ti quer revelar',
  ' ',
  'Refrão:',
  '                D',
  'Solte, solte o cabo da nau',
  '        G',
  'toma o remo nas mãos',
  '    D        Bm       C  A',
  'e navega com fé em Jesus',
  '    D',
  'e então tu verás',
  '      G        Gm',
  'que bonança se faz',
  '        D  Bm  Em A    D',
  'pois com Ele seguro estás',
  ' ',
  'Trevas vêm te assustar',
  'tempestades no mar',
  'Da montanha o mestre te vê',
  'E na tribulação',
  'Ele vem socorrer',
  'Sua mão bem te pode suster',
  ' ',
  'Refrão:',
  '                D',
  'Solte, solte o cabo da nau',
  '        G',
  'toma o remo nas mãos',
  '    D        Bm       C  A',
  'e navega com fé em Jesus',
  '    D',
  'e então tu verás',
  '      G        Gm',
  'que bonança se faz',
  '        D  Bm  Em A    D',
  'pois com Ele seguro estás',
  ' ',
  'Podes tu recordar',
  'maravilhas sem par',
  'No deserto o povo fartou',
  'E o mesmo poder',
  'Ele sempre terá',
  'Pois não muda e não falhará',
  ' ',
  'Refrão:',
  '                D',
  'Solte, solte o cabo da nau',
  '        G',
  'toma o remo nas mãos',
  '    D        Bm       C  A',
  'e navega com fé em Jesus',
  '    D',
  'e então tu verás',
  '      G        Gm',
  'que bonança se faz',
  '        D  Bm  Em A    D',
  'pois com Ele seguro estás',
  ' ',
  'Quando pedes mais fé',
  'ele ouve, o crê',
  'Mesmo sendo em tribulação',
  'Quando a mão de poder',
  'o teu ego tirar',
  'Sobre as ondas poderás andar',
  ' ',
  'Refrão:',
  '                D',
  'Solte, solte o cabo da nau',
  '        G',
  'toma o remo nas mãos',
  '    D        Bm       C  A',
  'e navega com fé em Jesus',
  '    D',
  'e então tu verás',
  '      G        Gm',
  'que bonança se faz',
  '        D  Bm  Em A    D',
  'pois com Ele seguro estás'
];

export const SomosJMSomosIglesia = [
  //_________________________________
  ' E',
  'Dicen que el mundo',
  '    D',
  'perdió su sentido,',
  '       A',
  'que el odio es más grande',
  '       F#m  E/G#  A  B',
  'y la muerte ha vencido.',
  ' E',
  'Dicen que nadie',
  '  D',
  'ayuda al que sufre,',
  '     A',
  'que Dios se ha dormido',
  '      F#m   E/G#  A B',
  'y la Iglesia se hunde.',
  ' C#m                  G#m',
  'Pero aquí estamos y no nos asustamos',
  '   F#                 A        B',
  'la noche no puede apagar esta luz.',
  ' ',
  'Refrão:',
  ' E F#m  A     B',
  'Discípulos de Cristo en la tierra,',
  'E  F#m    A           B',
  'con la misión de marcar una era,',
  'C#m G#m    A',
  'hay que pelear',
  '         B',
  'como guerreros de Ella.',
  '   C#m      G#m',
  'La iglesia espera',
  'A         B                E',
  'ya lo que Kentenich vino a dar.',
  ' ',
  '  E',
  'Cristo nos guía,',
  '  D',
  'vamos con María,',
  '      A',
  'En Schoenstatt',
  '         F#m   E/G#  A B',
  'buscamos la santidad.',
  ' E',
  'Hoy anunciamos',
  '      D',
  'a un padre y profeta',
  '      A',
  'que amó a la Iglesia',
  '      F#m E/G#  A  B',
  'y fundó nuestro hogar.',
  'C#m                 G#m',
  'Aún somos pocos nos falta de todo',
  '         F#',
  'y sin embargo sabemos',
  '        A       B',
  'que la Mater está'
];

export const TresCosas = [
  //_________________________________
  'Refrão:',
  'A                    D7+ A',
  'Tres cosas tiene el amor,',
  '                 D7+',
  'que no pueden olvidar,',
  'Bm                   E   Bm',
  ' Que Dios nos amó primero,',
  '                E',
  'que darse por entero.',
  'A            G   D E',
  ' Y ponerse a caminar.',
  ' ',
  'A        D       E',
  'En medio de su pueblo',
  '              A D E',
  'Jesús va caminando',
  'A         D      E',
  'en todos tus hermanos',
  '                A D E',
  'hay señas de su paso',
  'D                 A',
  'Si escuchas en silencio',
  'Bm                E',
  'su amor está cantando.',
  ' ',
  'Refrão:',
  'A                    D7+ A',
  'Tres cosas tiene el amor,',
  '                 D7+',
  'que no pueden olvidar,',
  'Bm                   E   Bm',
  ' Que Dios nos amó primero,',
  '                E',
  'que darse por entero.',
  'A            G   D E',
  ' Y ponerse a caminar.',
  ' ',
  'A            D      E',
  'Señor, tú me has llamado',
  '              A  D E',
  'a ser tu peregrino,',
  'A            D      E',
  ' si un paso yo entregado',
  '                 A D E',
  'tu cien haces conmigo',
  'D                 A    Bm',
  ' Para anunciar tu nueva',
  '               E',
  'la dicha de ser hijos.',
  ' ',
  'Refrão:',
  'A                    D7+ A',
  'Tres cosas tiene el amor,',
  '                 D7+',
  'que no pueden olvidar,',
  'Bm                   E   Bm',
  ' Que Dios nos amó primero,',
  '                E',
  'que darse por entero.',
  'A            G   D E',
  ' Y ponerse a caminar.',
  ' ',
  'A       D      E',
  'Tu mano me conduce',
  '           A  D E',
  'de noche y día,',
  'A          D       E',
  'llevando tu Evangelio',
  '                  A D E',
  'me llenas de alegría.',
  'D                A',
  ' Me alumbra tu palabra,',
  'Bm             E',
  ' me sanas las heridas.',
  ' ',
  'Refrão:',
  'A                    D7+ A',
  'Tres cosas tiene el amor,',
  '                 D7+',
  'que no pueden olvidar,',
  'Bm                   E   Bm',
  ' Que Dios nos amó primero,',
  '                E',
  'que darse por entero.',
  'A            G   D E',
  ' Y ponerse a caminar.'
];

export const TuEsAVencedora = [
  //_________________________________
  'Refrão:',
  'E',
  'Tu és a vencedora,',
  '  C#m',
  'Rainha e Educadora,',
  'A              B',
  'Maria és nossa Mãe',
  'E',
  'Como o Sol és brilhante,',
  'C#m',
  ' contigo adiante',
  'A             B',
  'lutaremos pro bem',
  'E                C#m',
  'Tu és a mãe do Senhor,',
  'A              B',
  'ensina-nos a rezar',
  'E               C#m',
  'A dizer sim ao amor,',
  'A                    B',
  'a viver sempre a cantar.',
  '       A B7 E',
  'Mãe Tu vencerás',
  ' ',
  ' A             B7',
  'Como o Sol foi feito',
  '       E         C#m',
  'para a terra aquecer,',
  ' A           B7',
  'Como o candeeiro',
  '      E        C#m',
  'não é para esconder,',
  'A            B7',
  'A luz do Santuário',
  '         E          C#m',
  'por mim queres irradiar,',
  'A             F#m       B7',
  'todos vão em Ti acreditar',
  ' ',
  'Refrão:',
  'E',
  'Tu és a vencedora,',
  '  C#m',
  'Rainha e Educadora,',
  'A              B',
  'Maria és nossa Mãe',
  'E',
  'Como o Sol és brilhante,',
  'C#m',
  ' contigo adiante',
  'A             B',
  'lutaremos pro bem',
  'E                C#m',
  'Tu és a mãe do Senhor,',
  'A              B',
  'ensina-nos a rezar',
  'E               C#m',
  'A dizer sim ao amor,',
  'A                    B',
  'a viver sempre a cantar.',
  '       A B7 E',
  'Mãe Tu vencerás',
  ' ',
  'Como uma torre',
  'até longe já se vê,',
  'Como o alto monte',
  'se enxerga no sopé.',
  'A luz do Santuário',
  'por mim queres irradiar,',
  'Todos poderão te contemplar',
  ' ',
  'Refrão:',
  'E',
  'Tu és a vencedora,',
  '  C#m',
  'Rainha e Educadora,',
  'A              B',
  'Maria és nossa Mãe',
  'E',
  'Como o Sol és brilhante,',
  'C#m',
  ' contigo adiante',
  'A             B',
  'lutaremos pro bem',
  'E                C#m',
  'Tu és a mãe do Senhor,',
  'A              B',
  'ensina-nos a rezar',
  'E               C#m',
  'A dizer sim ao amor,',
  'A                    B',
  'a viver sempre a cantar.',
  '       A B7 E',
  'Mãe Tu vencerás',
  ' ',
  'Reina Imaculada,',
  'com teu filho em meu ser',
  'Todo mal em mim,',
  'só tu com ele vais vencer.',
  'Brilha em minha fronte,',
  'ó Rainha teu esplendor,',
  'Vou levar a todos o Teu amor!',
  ' ',
  'Refrão:',
  'E',
  'Tu és a vencedora,',
  '  C#m',
  'Rainha e Educadora,',
  'A              B',
  'Maria és nossa Mãe',
  'E',
  'Como o Sol és brilhante,',
  'C#m',
  ' contigo adiante',
  'A             B',
  'lutaremos pro bem',
  'E                C#m',
  'Tu és a mãe do Senhor,',
  'A              B',
  'ensina-nos a rezar',
  'E               C#m',
  'A dizer sim ao amor,',
  'A                    B',
  'a viver sempre a cantar.',
  '       A B7 E',
  'Mãe Tu vencerás'
];

export const VamosCantar = [
  //_________________________________
  'E  B/D#   C#m',
  'Vamos cantar,',
  '                 A             B',
  'cantar na paz do meu Senhor Jesus.',
  'E   B/D#       C#m',
  'Deixar que o amor de Deus',
  '            A    B',
  'se torne em nossa vida luz.',
  '(Amar, Dançar, Pular...)',
  ' ',
  '           G#m   C#m',
  'É tão bom estar aqui,',
  ' A                     B',
  'juntos louvando ao Senhor.',
  '               G#m     C#m',
  'Soltar a nossa voz e assim.',
  'A                   B',
  'Exaltar o Deus de amor.'
];

export const ViveOSenhor = [
  //_________________________________
  'G         Em   C       D    G',
  'Nós temos uma Boa Nova para dar,',
  '    Em  C D',
  'uma Boa Nova.',
  'G       Em',
  'A morte já foi',
  '    C        D         G',
  'vencida por nosso Senhor,',
  '  Em      C D',
  'já foi vencida.',
  'G      Em       C  D        G',
  'E esta vida também é pra você,',
  'Em     C D',
  'é pra você.',
  ' ',
  'Refrão:',
  'G   Em    C    D           G',
  'Vive o Senhor, entre nós todos.',
  '    Em     C   D        G',
  'Vive o Senhor, em cada um.',
  '    Em     C  D',
  'Vive o Senhor.',
  'Esta alegria profunda,',
  'que nunca se acaba,',
  'esta alegria profunda.',
  'Venha logo segui-lo,',
  'Ele nunca falha.',
  'Venha logo segui-lo.',
  'Porque vale a pena',
  'entregar-se pro Ele,',
  'vale a pena.'
];

export const AleluiaCristoTabor = [
  //_________________________________
  'Braçadeira na 2ª casa',
  'Intro: Dm C G (2x)',
  ' ',
  'Dm      C         G',
  ' No despertar da aurora',
  'Sobre o chão, o manto',
  'Sobre a morte, a vitória',
  'Ao pranto vence o canto',
  ' ',
  'C   G   Dm    G   C  G    Dm  G',
  'A – le – lu – ia, A – le – lu – ia',
  ' ',
  'Dm       C      G',
  ' Tua presença traz',
  'Ao coração, minha paz',
  'E com amor, me envias',
  'Como o fez o Pai',
  ' ',
  'C   G   Dm    G   C  G    Dm  G  G7',
  'A – le – lu – ia, A – le – lu – ia',
  ' ',
  'F    G',
  ' Emanuel',
  '        Am      G       F',
  'Parte o pão e então te verei',
  'Dm      G G7 F        G',
  ' Sobe ao Céu  Ressuscitou!',
  '       Am          G       F',
  'És Jesus, Senhor nosso e Rei',
  ' ',
  'Dm      G G7',
  ' O Salvador',
  'Dm C G (2x)',
  'Dm        C       G',
  ' Ascende ao Pai e reina',
  'Fico em adoração',
  'E permanece em tudo',
  'Do tempo à imensidão',
  ' ',
  'Aleluia, Aleluia',
  ' ',
  'F    G           Am',
  ' Emanuel Parte o pão',
  '      G       F ',
  ' e então te verei',
  'Dm      G G7 F        G',
  ' Sobe ao Céu  Ressuscitou!',
  '       Am          G       F',
  'És Jesus, Senhor nosso e Rei',
  'Dm      G G7 F             G',
  ' O Salvador    Mestre e Senhor,',
  '       Am        G       F',
  'Em teu Fogo, por ti, arderei',
  'Dm          G G7',
  ' Cristo Tabor',
  ' ',
  'F   G   Am    G  F   G    Am  G F',
  'A – le – lu – ia, A – le – lu – ia',
  ' ',
  'Refrão',
  'C   G   Dm    G  C   G    Dm  G G7',
  'A – le – lu – ia, A – le – lu – ia',
  'F   G   Am  G  F C',
  'A – le – lu – ia,',
  '    G   Dm  G   G7 C',
  'A – le – lu – ia'
];

export const AlgumDiaMoveremosAsMontanhas = [
  //_________________________________
  '          A',
  'O sol se pôs,',
  '     D          A     A7',
  'pela noite caminhamos',
  'D        E',
  'Vimos da dor,',
  '       A      A7',
  'mas sorrimos',
  'D         E        A         F#m',
  'Somos a semente do dia que começa',
  '      D         E             A',
  'e forjamos com Deus, nosso destino.',
  ' ',
  'Tornaremos a nascer de nossas cinzas',
  'Plantaremos a flor onde não há nada',
  'Falaremos do amor onde haja ódio',
  'e algum dia,',
  'algum dia, moveremos as montanhas.',
  ' ',
  'Porque somos partidários da vida',
  'e levamos no peito esperança',
  'Porque somos caminhantes',
  'da noite destes tempos',
  'e, na noite, revivemos a manhã.',
  ' ',
  'Construiremos a paz sobre a guerra',
  'Encheremos as casas de alegria',
  'Chamaremos de irmão a cada homem,',
  'será então,',
  'quando os homens serão uma família.'
];
