export const EnviaiOVossoEspiritoSenhor = [
  //_________________________________
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)',
  '    C                        G',
  'Bendize, ó minha alma ao Senhor!',
  'F',
  ' O meu Deus e meu Senhor',
  '         G',
  'como sois grande!',
  'C',
  ' De majestade e esplendor',
  '          G',
  'vos revestis',
  'F',
  'e de luz vos envolveis',
  '         G     G7',
  'como num manto.',
  ' ',
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)',
  ' ',
  'A terra vós firmastes em suas bases,',
  'ficará firme pelos séculos sem fim.',
  'Os mares a cobriram como um manto',
  'e as águas envolviam as montanhas.',
  ' ',
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)',
  ' ',
  'Fazeis brotar em meio aos vales as nascentes,',
  'que passam serpeando entre as montanhas.',
  'Às suas margens vem morar os passarinhos,',
  'entre os ramos eles erguem o seu canto.',
  ' ',
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)',
  ' ',
  'De vossa casa as montanhas irrigais,',
  'com vossos frutos saciais a terra inteira.',
  'Fazeis crescer verdes pastos para o gado',
  'e as plantas que são úteis para o homem.',
  ' ',
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)',
  ' ',
  'Quão numerosas, ó Senhor, são vossas obras',
  'e que sabedoria em todas elas!',
  'Encheu-se a terra com as vossas criaturas!',
  'Bendize, ó minha alma ao Senhor!',
  ' ',
  'Refrão:',
  '  C          Am        Dm',
  'Envia teu Espírito Senhor,',
  '     G7             C',
  'e renova a face da terra (2x)'
];

export const EuNavegarei = [
  //_________________________________
  ' Am',
  'Eu navegarei',
  '               G',
  'no oceano do Espírito',
  '             F',
  'E ali adorarei',
  '                 E',
  'ao Deus do meu amor. (2x)',
  ' ',
  'Refrão:',
  '           Am',
  'Espírito, Espírito,',
  '                 G',
  'que desce como fogo',
  '              F',
  'Vem como em Pentecostes',
  '      E',
  'e enche-me de novo. (2x)',
  ' ',
  'Am',
  'Eu adorarei',
  '                G',
  'ao Deus da minha vida,',
  '                F',
  'Que me compreendeu',
  '                 E',
  'sem nenhuma explicação. (2x)',
  ' ',
  'Refrão:',
  '           Am',
  'Espírito, Espírito,',
  '                 G',
  'que desce como fogo',
  '              F',
  'Vem como em Pentecostes',
  '      E',
  'e enche-me de novo. (2x)',
  ' ',
  'Am                   G',
  'Eu servirei ao meu Deus fiel',
  '              F',
  'Ao meu libertador,',
  '               E',
  'aquele que venceu. (2x)',
  ' ',
  'Refrão:',
  '           Am',
  'Espírito, Espírito,',
  '                 G',
  'que desce como fogo',
  '              F',
  'Vem como em Pentecostes',
  '      E',
  'e enche-me de novo. (2x)'
];

export const Cenaculo = [
  //_________________________________
  'C9',
  'Maria, entre nós,',
  ' D         D4',
  'cheia de poder',
  'C9',
  'Roga ao Espírito',
  '      D        D4',
  'o seu sopro descer',
  'Em                      C',
  'Para que Deus nos transforme',
  '      G               D  D4',
  'E no mundo o amor vencer',
  'C9                      D',
  'Abre as almas dos que a ti',
  '        D4',
  'se consagram',
  'C9                D         D4',
  'Para o Espírito vir nos renovar',
  'Em               C',
  'Ó, vem, Espírito Santo',
  '     G          D  D4',
  'Para nos incendiar',
  ' ',
  'Refrão:',
  'C9                D  D4',
  'Me fortalece e ilumina',
  'G                B7',
  ' Me guia e me consola, para eu ver',
  'Em               C',
  'O plano do Amor Eterno',
  '         G          D  D4',
  'na minha vida acontecer',
  'C9              D   D4',
  'Me ajuda a entender',
  'G               B7        Em',
  'O que eu devo fazer e sofrer',
  '                     C',
  'E o meu SIM seja perpétuo',
  '       G             D',
  'Aos desejos e ao querer',
  '(1ª. vez)',
  '  D4        C9 D D4',
  'Espírito de Deus',
  ' ',
  'Refrão:',
  'C9                D  D4',
  'Me fortalece e ilumina',
  'G                B7',
  ' Me guia e me consola, para eu ver',
  'Em               C',
  'O plano do Amor Eterno',
  '         G          D  D4',
  'na minha vida acontecer',
  'C9              D   D4',
  'Me ajuda a entender',
  'G               B7        Em',
  'O que eu devo fazer e sofrer',
  '                     C',
  'E o meu SIM seja perpétuo',
  '       G             D',
  'Aos desejos e ao querer',
  '   D4        C9  D  D4',
  'Do meu Eterno Pai... (2x)',
  '             C9',
  'Espírito de Deus'
];

export const Vuela = [
  //_________________________________
  ' A                    D',
  'Nada de lo mío te es ajeno',
  'Bm                            E',
  ' y ya nada puede separarme de Ti',
  'A                   D',
  'el temor ha sido vencido',
  'Bm                         E',
  ' todo lo que soy sucede en Ti',
  'Bm                           E',
  ' todo lo que soy me habla de Ti.',
  ' ',
  'Refrão:',
  'A        D             A',
  'Vuela tu voz sobre mis aguas',
  '         F#m',
  'es una paloma',
  '       D          E',
  'que me roza al volar',
  '    A           D',
  'me elevas, mi inundas,',
  '       A',
  'me traspasas',
  '         F#m',
  'eres esa fuerza',
  '          D          E',
  'que me abraza al llegar.',
  ' ',
  'Mi fuerza no está en lo que quiero',
  'ni en mi oscuridad me oculto de Ti',
  'mi fuerza es un canto que amanece',
  'que se levanta sólo por Ti',
  'sólo por amor a Ti.',
  ' ',
  'Refrão:',
  'A        D             A',
  'Vuela tu voz sobre mis aguas',
  '         F#m',
  'es una paloma',
  '       D          E',
  'que me roza al volar',
  '    A           D',
  'me elevas, mi inundas,',
  '       A',
  'me traspasas',
  ' ',
  'Ya nada busco, nada quiero',
  'sólo tu amor dámelo a mí',
  'envuélveme con tu viento de fuego',
  'y cantaré mi canción para Ti',
  'sólo por amor a Ti.',
  ' ',
  'Refrão:',
  'A        D             A',
  'Vuela tu voz sobre mis aguas',
  '         F#m',
  'es una paloma',
  '       D          E',
  'que me roza al volar',
  '    A           D',
  'me elevas, mi inundas,',
  '       A',
  'me traspasas',
  'D          A',
  ' Eres esa fuerza',
  'Bm         E        A  D  A',
  ' que me ama sin preguntar.',
];

export const AEscolhida = [
  //_________________________________
  'E                      B7',
  'Uma entre todas foi a escolhida:',
  'C#m                     G#m',
  'foste tu Maria, serva preferida,',
  ' A             E',
  'Mãe do meu Senhor,',
  ' F#              B7',
  'Mãe do meu Salvador.',
  ' ',
  'Refrão:',
  '  E C#m  A        B7',
  'Maria, cheia de graça',
  '       E C#m',
  'e consolo,',
  'A           B7        E   C#m',
  'venha caminhar com teu povo,',
  'A         B7        E',
  'Nossa Mãe sempre serás.',
  ' ',
  'E                      B7',
  'Roga pelos pecadores desta terra.',
  'C#-                  G#',
  'Roga pelo povo que em seu Deus espera,',
  ' A                E',
  'Mãe do meu Senhor,',
  ' F#              B7',
  'Mãe do meu Salvador.',
  ' ',
  'Refrão:',
  '  E C#m  A        B7',
  'Maria, cheia de graça',
  '       E C#m',
  'e consolo,',
  'A           B7        E   C#m',
  'venha caminhar com teu povo,',
  'A         B7        E',
  'Nossa Mãe sempre serás.'
];

export const AlzaMiPaz = [
  //_________________________________
  'C        G/B         Am     Em',
  'Bajo tu amparo nos ponemos Reina',
  'F       G              C   C7',
  'no desprecies nuestro canto',
  'F          G      C        Am',
  'transforma cada pedazo de mí',
  'F         Fm',
  'en signo victorioso',
  'Dm     G     G7',
  'en tus manos.',
  ' ',
  '  Am         Em',
  'Y alza tú mi paz,',
  '    F          G',
  'con tu mirada clara,',
  '  Am         Em',
  'y alza tú mi paz,',
  '    F           G',
  'en medio de tormentas,',
  '  Am         Em',
  'y alza tú mi paz,',
  '    F          G',
  'con tu mirada clara,',
  '  Am        Em',
  'y álzate bandera,',
  '  C7+ F7+ C7+ F7+',
  'María.'
];

export const AoPezDaCruz = [
  //_________________________________
  'F#m* = 044200',
  'G#m* = 066400',
  ' ',
  'E',
  'Aos pés da Cruz,',
  '         F#m*',
  'o teu silêncio a contemplar',
  '        G#m*',
  'Rosto sereno,',
  '                   F#m*',
  'dor profunda em teu olhar',
  'E                      F#m*',
  ' Teu pranto tece tua angústia',
  'a torturar-te',
  '      G#m*',
  'A tua vida parte para junto',
  'F#m*   E F#m* G#m* F#m*',
  ' ao Pai',
  ' ',
  'E',
  'O Amor Eterno',
  '     F#m*',
  'fita terno teu clamor',
  '     G#m*',
  'Tua missão é grande',
  '            F#m*',
  'na Aliança de Amor',
  'E',
  'E dos apóstolos,',
  '     F#m*',
  'transforma o coração',
  '        G#m*',
  'Coroa entregam-te',
  '             F#m*',
  'ao cantarem a cançãov',
  ' ',
  'Refrão:',
  '    E  F#m*            A9',
  'Mulher,   eis aí o teu filho',
  '         F#m*',
  'Que te entoa a canção',
  '   E F#m*          A9',
  'Tu és    sua Mãe e Rainha',
  '          F#m*',
  'Reina em seu',
  '     E F#m* G#m* F#m*',
  'coração',
  ' ',
  'Sentes em ti a mesma dor',
  'ao transpassar-lhe',
  'A lança ao peito,',
  'água viva a jorrar',
  'Com tuas mãos,',
  'guarda o tesouro em um cálice',
  'Perfeita unidade a se forjar',
  ' ',
  'Refrão:',
  'Mulher, eis aí o teu filho',
  'Que te entoa a canção',
  'Tu és sua Mãe e Rainha',
  'Reina em seu coração',
  ' ',
  'Refrão:',
  'Mulher, eis aqui o teu filho',
  'Que te entoa a canção',
  'Tu és minha Mãe e Rainha',
  'Reina em meu coração'
];

export const AvanzaReina = [
  //_________________________________
  'Intro: A D Bm E',
  ' ',
  '    A          D',
  'Despierta ante nosotros,',
  '   Bm           E',
  'la luz de tu mañana,',
  '    A          D',
  'Cerrada ya la noche,',
  '  Bm              E',
  'irrumpe tu esperanza,',
  '   A           D',
  'En Tí hoy se posan',
  'Bm            E',
  'todas las miradas,',
  ' D                E',
  'Avanza Reina, avanza!',
  ' ',
  'Al pie del Santuario,',
  'estamos tu aliados,',
  'Delante de nosotros,',
  'se abre nuestro campo,',
  'Confiados de tu mano,',
  'buscamos la victoria,',
  'Avanza Reina, avanza!',
  ' ',
  '   D',
  'Irradie tu alegría',
  '         E',
  'mi canción,',
  '     D',
  'Se encienda en nosotros',
  'E',
  'tu misión.',
  ' ',
  'Refrão:',
  '              A E',
  'Que nuestros pasos',
  'D             E',
  'sean las huellas,',
  '     A E      D',
  'Que lleven el mundo',
  '      E',
  'hacia Tí,',
  '         A  E',
  'Y que el mundo',
  '   D          E',
  'De nuevo se encienda',
  '        D  E A',
  'en tu Amor.'
];

export const ConsagracaoJumas = [
  //_________________________________
  'Em           D    G          A Em',
  'Oh, minha Senhora, oh minha Mãe,',
  '       D           C',
  'me ofereço  todo a ti,',
  '     G    D              G',
  'e em prova do meu filial afeto,',
  'C D      G   D       G',
  '  te consagro neste dia,',
  '     Em            D',
  'meus olhos, meus ouvidos,',
  '      G              A  Em',
  'minha boca, meu coração,',
  '          D               C',
  'em uma palavra todo  meu ser.',
  '  G               D   Em',
  'E já que sou todo teu,',
  '           B7',
  'oh bondosa Mãe,',
  'C             D           G',
  'guarda-me, defenda-me, utiliza-me,',
  'C D          G   C   D',
  ' como instrumento de possessão',
  'Em  C D Em C D Em',
  ' tua. Amém.  Amém'
];

export const ConsagracaoJufem = [
  //_________________________________
  'C        G            Am',
  'Ó minha Mãe, minha senhora.',
  '   F     G       C  G',
  'É teu o meu coração!',
  '   C          G',
  'É teu o meu pensar,',
  '    Am           Em',
  'meu agir e meu falar,',
  '      F  G         C   C7',
  'o meu ser o meu viver.',
  '  F          G',
  'Aceita-me o Mãe,',
  '         C        Am',
  'com toda minha pequenez.',
  '      F              G',
  'Te entrego tudo que sou',
  '         C   C7',
  'tudo que tenho.',
  '       F        G',
  'Te confio cada passo,',
  '     C          Am',
  'cada pedra no caminho',
  '      F         G',
  'como prova de amor',
  '        C   G Am Em F G C',
  'e sacrifício.',
  ' ',
  'E agora como sua propriedade,',
  'eu posso exclamar com ardor:',
  '“Eu pertenço à Mãe e ela me pertence”',
  'é a nossa Alinça de Amor.',
  'Incomparável Mãe, amparai-me e defendei-me,',
  'guardai-me sob o seu manto protetor.',
  'Tú és o caminho que me guia',
  'e conduz ao teu divino filho Jesus.',
  'Amém'
];

export const EisAiTuaMae = [
  //_________________________________
  'G9          D/F#',
  'João era o discípulo',
  ' Em7        Bm7',
  'amado de Jesus',
  'C9               Bm7',
  'Em seu coração havia grande',
  'Am               D',
  ' necessidade do seu amor.',
  '   G9',
  'Aos pés da cruz,',
  '          D/F#',
  'vendo seu mestre partir.',
  'Em7',
  'Quanta solidão,',
  '       Bm7',
  'já não sabia aonde ir',
  'Am7',
  'Disse Jesus:',
  '      Bm7',
  '“mulher, eis aí o teu filho.',
  'Am7   C     D',
  'Filho, eis aí tua Mãe.”',
  ' ',
  '        G',
  'Se a saudade aperta ainda o teu coração',
  '      Em7',
  'E a estrada deserta',
  '      Bm7',
  'não parece ter fim',
  '     C9',
  'Hoje deixo contigo',
  '    Bm7',
  'força e direção.',
  'Am7',
  'Olha pra ela',
  '   Bm7',
  'e espera por mim',
  'Am7',
  'Não temas',
  '        C          D',
  'em recebê-la por Mãe.',
  ' ',
  'Refrão:',
  '   G         D/F#',
  'Será o teu consolo,',
  '   Em7     Bm7',
  'teu colo materno',
  '     C9          Bm7',
  'Pois lá está o Esposo.',
  'Am7    Bm7    C9  D',
  'Ama-a, ama-a, ama-a!'
];

export const LaDeSiempre = [
  //_________________________________
  'E6                      F#/E',
  'Ya no encuentro la manera de decir,',
  '   A9                 E',
  'que mi vida es para vos,',
  'E6                      F#/E',
  'Ya no encuentro la manera de cantar,',
  '    A9                       E',
  'algo que pueda explicar.',
  'E6                  F#/E',
  'Tanta lucha, tanta vida, tanto amor,',
  '    A9                  E',
  'por mi Alianza te entregas,',
  'E6                         F#/E',
  'Y aunque intente nunca puedo superar,',
  '     A9           D B7',
  'tu generosidad.',
  ' ',
  'G          C',
  'Voy a volver atrás',
  '  D                   G',
  'y fijarme sin dudar',
  'Em7            C',
  'Que en cada paso que di,',
  '   D                    G',
  'estuviste junto a mí',
  'Em7         C',
  'Gracias una vez más,',
  '  D                       G',
  'por un mundo que cambiar',
  'Em7         C  D',
  'No voy a descansar,',
  '                        G  B7',
  'tengo un nombre que gritar',
  ' ',
  'Refrão:',
  'E G#m7/5b  A A#5b/7',
  'Es,  es la Mater,',
  'C#5b/7     F#m7   A9       B7',
  '   la de Siempre, la de Ayer',
  'E G#m7/5b  A A#5b/7',
  'Es,  es la Mater,',
  'C#5b/7    F#m7  C  D       E',
  '   que me dice  “Ahí estaré”',
  ' ',
  'A la sombra de Santuario me esperas',
  'para contarme una verdad',
  'Que mi historia está implantada en tu jardín,',
  'cada día la regás',
  'Desde el cuadro siempre es nuevo tu mirar,',
  'hoy me quieres educar',
  'La aventura de saber que pides más,',
  'y no me puedo negar',
  ' ',
  'E6 042400',
  'F#/E 044300',
  'G#m7/5b 4x443x',
  'A#5b/7 x12120',
  'C#5b/7 x45450'
];

export const Madre = [
  //_________________________________
  'E                  B7',
  'Madre hoy quiero hablarte',
  '   C#m                  G#m',
  'una vez más y estar cerca de',
  '       A          B7',
  'tu corazón, junto a vos.',
  'E           B7           C#m',
  'Y quiero contarte que ya estoy',
  '            G#m           A',
  'en la lucha diaria por lograr',
  '        B7',
  'la santidad.',
  'A             B7         E',
  'Quiero que tu me vayas guiando',
  '           B7          C#m',
  'por este camino que escogí,',
  '          A',
  'ser como el Padre,',
  'E          B7      C#m',
  'Pero tengo miedo de caer',
  '       G#m          A  Am',
  'en la oscuridad no ver,',
  '                          B7',
  'pero que tu Madre estará allí.',
  ' ',
  'El mal va dejando huellas tras de si,',
  'pero Schoenstatt quiero construir un mundo nuevo.',
  'En el que el hombre tenga que luchar',
  'para que Cristo pueda reinar junto a su Padre.',
  'Ser respuesta para el mundo es la misión,',
  'y yo Madre me consagro a vos entero,',
  'Soy la reina de mi corazón,',
  'madre humilde esclava del Señor.',
  'Hazme fuerte en la alianza de amor.',
  'E                  B7',
  'Madre hoy quiero hablarte',
  '       C#m',
  'una vez mas,',
  '           G#m         A',
  'estar cerca de tu corazón,',
  '    B7',
  'junto a vos.',
  'E           B7             C#m',
  'Y quiero contarte que ya estoy',
  '           G#m           A',
  'en la lucha diaria por lograr',
  'B7      A  Am   E',
  '  la santidad.'
];

export const MaeAdmiravel = [
  //_________________________________
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.',
  ' ',
  '          A7',
  'Por nossa Judéia,',
  '            D',
  'ó mãe, com carinho,',
  '             A7',
  'tu vens apressada,',
  '          D      D7',
  'estás a caminho.',
  '          G',
  'E onde tu chegas',
  '            D   Bm',
  'a paz faz morada,',
  '               Em',
  'as portas se abrindo',
  'A7            D',
  '  em cada chegada.',
  ' ',
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.',
  ' ',
  'De teu Santuário, tu vens peregrina.',
  'A graça trazendo que lá se origina.',
  'Ao dar-nos abrigo, transformas pro bem,',
  'nosso apostolado abençoas também.',
  ' ',
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.',
  ' ',
  'Unida a teu Filho, és co-redentora.',
  'Milagres alcanças, doce intercessora.',
  'A água é mudada em vinho de amor,',
  'também de esperança e de fé no Senhor.',
  ' ',
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.',
  ' ',
  'Rezando e vivendo o Santo Rosário,',
  'será nossa casa e também santuário.',
  'Ó fica conosco, haja o que houver,',
  'faremos contigo o que Cristo disser.',
  ' ',
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.',
  ' ',
  'E assim mãe querida, doce peregrina,',
  'rumamos ao tempo que se descortina.',
  'Vivendo a aliança, teu santo convênio,',
  'será para Cristo o novo milênio.',
  'Refrão:',
  'D                            Em',
  'Mãe admirável, ó mãe peregrina,',
  '        A              D',
  'a tua visita aquece e ilumina',
  '              D7                 G',
  'Pois trazes contigo teu Filho Jesus,',
  '              D          A     D',
  'que é vida, caminho, verdade e luz.'
];

export const MaeDoHomemNovo = [
  //_________________________________
  'G               D',
  'Singela doce e pura,',
  'Em          D',
  ' Maria de José.',
  'G                D   Em',
  'Mãe terna e escolhida',
  '              D',
  'és mãe leal da fé.',
  'Am            Bm C    G   D',
  ' Seu nome é Maria de Deus.',
  ' ',
  'Refrão:',
  'G               Em',
  ' Maria Santa e Fiel,',
  '  C           Am            D',
  'ensina-nos a viver com escolhidos.',
  'G                      Em',
  ' Olhos voltados para o céu',
  '      C        Am           D',
  'e por ele construir a nova vida.',
  ' ',
  'Mãe da obediência,',
  'da graça e do amor.',
  'Que os homens se encontrem',
  'no filho desta flor.',
  'Seu nome é Maria de Deus.',
  ' ',
  'Refrão:',
  'G               Em',
  ' Maria Santa e Fiel,',
  '  C           Am            D',
  'ensina-nos a viver com escolhidos.',
  'G                      Em',
  ' Olhos voltados para o céu',
  '      C        Am           D',
  'e por ele construir a nova vida.'
];

export const Maravilhas = [
  //_________________________________
  '     D            F#m',
  'Maravilhas fez em mim,',
  '     G               A   Bb°',
  'minha alma canta de gozo.',
  '        Bm             F#m',
  'Pois ao ver minha pequenez,',
  '     G            A',
  'se detiveram meus olhos.',
  '       Bm            F#m',
  'O que é Santo e poderoso,',
  '       G             Em',
  'hoje aguarda por meu sim.',
  '     Bm             F#m',
  'Minha alma canta de gozo,',
  '    G       A       D',
  'maravilhas fez em mim.',
  ' ',
  'Maravilhas fez em mim,',
  'minha alma canta de gozo.',
  'O Senhor me tem amado,',
  'mais que aos lírios do campo.',
  'E pelo Espírito Santo,',
  'ele habita hoje em mim.',
  'Não cesse nunca meu canto,',
  'maravilhas fez em mim.'
];

export const MariaDaAlianca = [
  //_________________________________
  ' A                     D',
  'Que silêncio mais delicado,',
  '  E                    A     D E',
  'amor do amor mais escondido,',
  'A                      D',
  'és Tu mulher porta do céu,',
  '  E                      A',
  'três cores enfeitam teu manto.',
  'Bm                     G',
  'Descem as cascatas das árvores,',
  '                 D',
  'que caem até o chão',
  '                 E',
  'e chegam ao Santuário.',
  ' ',
  'Refrão:',
  ' A                 E',
  'Queres dar a mão e eu pedir a Tua,',
  '    F#m',
  'não posso estar sem Ti,',
  '   C#m',
  'sem Teu olhar tão puro,',
  '    D',
  'tua voz enche a minh’alma',
  '  A',
  'Maria da Aliança,',
  '  G           E',
  'palavra feita flor.',
  ' ',
  'Eu mudei todo meu canto,',
  'só pra sonhar com tua brisa,',
  'e não sou mais que pó no cominho,',
  'mesmo não sendo pó esquecido.',
  'Quero ser a ponte até o céu,',
  'feito de barro e fogo',
  'que nasce no Santuário.',
  ' ',
  'Refrão:',
  ' A                 E',
  'Queres dar a mão e eu pedir a Tua,',
  '    F#m',
  'não posso estar sem Ti,',
  '   C#m',
  'sem Teu olhar tão puro,',
  '    D',
  'tua voz enche a minh’alma',
  '  A',
  'Maria da Aliança,',
  '  G           E',
  'palavra feita flor.'
];

export const MariaDeLaAlianza = [
  //_________________________________
  ' A                    D',
  'Que silencio mas delicado,',
  '  E                     A    D E',
  'amor del amor mas escondido.',
  'A                     D',
  'Eres mujer puerta del cielo,',
  '  E                      A    Bb°',
  'tres colores adornan tu manto.',
  ' Bm                        G',
  'Bajan las cascadas de los arboles',
  '                   D',
  'e caen hasta el suelo',
  '                   E',
  'y llegan al Santuario',
  ' ',
  'Refrão:',
  ' A                   E',
  'Quieres dar la mano y yo pedir',
  '           F#m',
  'la tuya no puedo estar sin ti,',
  '    C#m',
  'sin tu mirada pura,',
  '   D',
  'tu voz me llena el alma,',
  '   A',
  'María de la alianza.',
  '  G            E',
  'Palabra hecha flor.',
  ' ',
  'He cambiado todo mi canto,',
  'sólo para soñar tu brisa,',
  'Y no soy más que el polvo en el camino,',
  'aunque no es polvo de tu olvido.',
  'Quiero ser un puente hacia el cielo,',
  'hecho de barro y de fuego',
  'que nace del Santuario.',
  ' ',
  'Refrão:',
  ' A                   E',
  'Quieres dar la mano y yo pedir',
  '           F#m',
  'la tuya no puedo estar sin ti,',
  '    C#m',
  'sin tu mirada pura,',
  '   D',
  'tu voz me llena el alma,',
  '   A',
  'María de la alianza.',
  '  G            E',
  'Palabra hecha flor.'
];

export const MariaDeNazare = [
  //_________________________________
  'Refrão:',
  '  E         F#m    B7         E',
  'Maria de Nazaré, Maria me cativou.',
  '       E              F#m',
  'Fez mais forte a minha fé,',
  '  B7              E',
  'e por filho me adotou.',
  ' ',
  '   Bm        E7      A',
  'Às vezes eu paro e fico a pensar',
  '  Am                E',
  'e sem perceber me vejo a rezar.',
  '  C#m           F#m',
  'E meu coração se põe a cantar,',
  '    B7             E',
  'pra virgem de Nazaré.',
  '  Bm7       E7    A',
  'Menina que Deus amou e escolheu,',
  '    Am                E',
  'pra Mãe de Jesus, o Filho de Deus.',
  ' C#m              F#m',
  'Maria que o povo inteiro elegeu,',
  '   B7             E',
  'Senhora e Mãe do céu.',
  ' ',
  '    F#m   B7       E',
  'Ave Maria, Ave Maria,',
  'C#m  F#m  B7        E',
  'Ave Maria, Mãe de Jesus. (2x)'
];

export const MariaEOAnjo = [
  //_________________________________
  'E',
  'Quem serás tu, criatura bela?',
  '                     Bm7',
  'Que encheu meu quarto com tua luz',
  '                         A',
  'O teu olhar me trouxe a paz,',
  'B       A           E B',
  'tua presença me refaz.',
  '                  E',
  'Eu sou o anjo Gabriel,',
  '                    Bm7',
  'venho em nome do Senhor',
  'E               F#m    B',
  'Darás a luz ao Salvador,',
  '                 E     Bm7 Esus4',
  'serás a Mãe do Emanuel.',
  ' ',
  '      A',
  'Por que teus lábios',
  '                B',
  'tremem tanto assim?',
  '    G#',
  'Por que não tir',
  '               C#m',
  'os seus olhos de   mim?',
  '   F#m                          B',
  'Há tanta graça estar diante de ti',
  '     E            F#m        E/G#',
  'e o céu inteiro espera por teu SIM',
  '     A                     B',
  'Não temas doce anjo do Senhor.',
  '  G#m                       C#m',
  'Escuta o que agora eu vou falar.',
  ' F#m                      B',
  'Sorria e vai ao céu anunciar: SIM,',
  '       A    B      E        A E',
  'eu serei a Mãe do Salvador!',
  ' ',
  'Refrão:',
  '    F#m7  B          G#m  C#m',
  'Ave Maria, quanta alegria',
  '            F#m       B',
  'O céu se encheu de luz',
  '             E         E7',
  'pois vai nascer Jesus.',
  '         A  Amem',
  'Santa Maria,',
  '           E        F#',
  'Deus escolheu-te bem',
  '         F#m7   B         E',
  'E todos os Anjos cantam Amém!'
];
