export const SacramentoDaComunhao = [
  //_________________________________
  '    D           A/C#',
  'Senhor, quando te vejo',
  '       Bm             Bm/A',
  'no sacramento da comunhão.',
  'G                 A',
  'Sinto o céu se abrir',
  '      D            G',
  'e uma luz a me atingir',
  '     Em',
  'esfriando minha cabeça',
  '         G            A',
  'e esquentando meu coração.',
  '   D                D/C#',
  'Senhor, graças e louvores',
  '     Bm              Bm/A',
  'sejam dados a todo momento,',
  'G                   A',
  'quero te louvar na dor,',
  '       D               G',
  'Na alegria e no sofrimento.',
  '        Em           A7',
  'E se em meio à tribulação,',
  '      D            G',
  'eu me esquecer de ti,',
  '    Em                      A7',
  'Ilumina minhas trevas com Tua luz',
  ' ',
  'Refrão:',
  '  D   A/C#              Bm',
  'Jesus, fonte de misericórdia',
  'que jorra do templo.',
  '  Em      G          A',
  'Jesus, O Filho da Rainha',
  'F#m    Bm                G',
  'Jesus, rosto divino do homem.',
  '  D     Em      A7         D',
  'Jesus, rosto humano de Deus',
  ' ',
  'G                          A',
  'Chego muitas vezes em Tua casa,',
  'meu Senhor;',
  '  F#m                Bm',
  'Triste, abatido, precisando de amor.',
  '    Em',
  'Mas depois da comunhão',
  '         C',
  'Tua casa é meu coração.',
  '        Em          C           D',
  'Então sinto o céu dentro de mim.',
  '      G                           A',
  'Não comungo porque mereço isso eu sei,',
  'oh meu Senhor.',
  '   F#m                  Bm',
  'Comungo, pois preciso de Ti.',
  ' Em',
  'Quando faltei à missa,',
  '    C',
  'fugia de mim e de Ti,',
  ' Em              G',
  'mas agora eu voltei,',
  '              A',
  'por favor, aceita-Me.',
  ' ',
  'Refrão:',
  '  D   A/C#              Bm',
  'Jesus, fonte de misericórdia',
  'que jorra do templo.',
  '  Em      G          A',
  'Jesus, O Filho da Rainha',
  'F#m    Bm                G',
  'Jesus, rosto divino do homem.',
  '  D     Em      A7         D',
  'Jesus, rosto humano de Deus'
];

export const PelosPradosECampinas = [
  //_________________________________
  '        D         Bm',
  'Pelos prados e campinas',
  '      G  A    D',
  'verdejantes eu vou',
  '      F#m         G             A',
  'É o Senhor que me leva a descansar',
  '           D             Bm',
  'Junto às fontes de águas puras',
  '      G   A    D',
  'repousantes eu vou',
  '       F#m          G',
  'Minhas forças o Senhor',
  '        A  Am7  D7',
  'vai animar',
  ' ',
  'Refrão:',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em             A7',
  'Por isso nada em minha vida',
  '       D D7',
  'faltará',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em           A7        D',
  'Por isso nada em minha vida faltará',
  '  G        D',
  '(nada faltará)',
  ' ',
  'Nos caminhos mais seguros junto d’Ele eu vou',
  'E pra sempre o Seu nome eu honrarei',
  'Se eu encontro mil abismos nos caminhos eu vou',
  'Segurança sempre tenho em suas mãos',
  ' ',
  'Refrão:',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em             A7',
  'Por isso nada em minha vida',
  '       D D7',
  'faltará',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em           A7        D',
  'Por isso nada em minha vida faltará',
  '  G        D',
  '(nada faltará)',
  ' ',
  'Ao banquete em sua casa muito alegre eu vou',
  'Um lugar em Sua mesa me preparou.',
  'Ele unge minha fronte e me faz ser feliz',
  'E transborda a minha taça em Seu amor.',
  ' ',
  'Refrão:',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em             A7',
  'Por isso nada em minha vida',
  '       D D7',
  'faltará',
  '   G        A    F#m     Bm',
  'Tu és, Senhor, o meu pastor.',
  '          Em           A7        D',
  'Por isso nada em minha vida faltará',
  '  G        D',
  '(nada faltará)'
];

export const SempreFosteTu = [
  //_________________________________
  'A7+ C#m7              Bm7',
  'Jesus, me abriste tua porta',
  '   E                 A7+  C#m7',
  'para que entrasse contigo,',
  '       Bm7      E',
  'na tua casa deixei',
  '            A7+ C#m7 Bm7 E',
  'de ser peregrino.',
  'A7+ C#m7    Bm7     E',
  'Jesus, no amor cheguei',
  '         A7+ C#m7',
  'a conhecer-te,',
  '   Bm7        E',
  'na tua misericórdia',
  '          A7+    C#m7 Bm7',
  'a compreender-te,',
  '          E',
  'na minha cruz a',
  '    A7+   C#m7 Bm7 E',
  'querer-te.',
  '       A        E',
  'Sempre foste tu,',
  '              F#m',
  'quem falou primeiro,',
  'C#7             D',
  ' Companheiro de tantos caminhos,',
  '     A                    E',
  'tuas mãos sempre se ofereceram.',
  ' ',
  'Sempre foste tu, quem amou primeiro,',
  'quem levou minha cruz',
  'para ver que eu não caísse ao chão.',
  ' ',
  'Jesus, tu és irmão no meu irmão',
  'tu és a fonte,',
  'na montanha, és tu quem levas ao Pai,',
  'és tu quem vive no homem.',
  'Jesus, que nosso Santuário',
  'seja fonte de água viva,',
  'vínculos de amor que limpem feridas.',
  ' ',
  'Jesus, que tuas mãos abençoem esta terra',
  'e as nossas espalhem as sementes.',
  'A        C#m7       Bm7 E',
  'Jesus, temos sede de ti,',
  'F#m    C#m7        Bm7  E',
  'Jesus mostra-nos a vida,',
  '             A7+',
  'vida em plenitude,',
  'C#m7  Bm7   E',
  '   Jesus... Porque...'
];

export const SeguraNaMaosDeDeus = [
  //_________________________________
  '      C',
  'Se as águas do mar da vida',
  '    F           C',
  'quiserem te afogar,',
  '  Am              F       G',
  'Segura na mão de Deus e vai.',
  ' ',
  'Refrão:',
  '           C',
  'Se as tristezas desta vida',
  '    F             C',
  'quiserem te sufocar,',
  '  Am              G      C  G',
  'Segura na mão de Deus e vai.',
  '   C',
  'Segura na mão de Deus.',
  '   F              C',
  'Segura na mão de Deus.',
  '     Am                   F G',
  'Pois ela, ela te sustentará.',
  '     C',
  'Não temas, segue adiante',
  '      F            C',
  'e não olhes para trás.',
  '  Am              F       G',
  'Segura na mão de Deus e vai.',
  ' ',
  'Se a jornada é pesada',
  'e te cansas da caminhada,',
  'Segura na mão de Deus e vai.',
  'Orando, jejuando,',
  'confiando e confessando.',
  ' ',
  'Refrão:',
  '           C',
  'Se as tristezas desta vida',
  '    F             C',
  'quiserem te sufocar,',
  '  Am              G      C  G',
  'Segura na mão de Deus e vai.'
];

export const SubidoAlSicomoro = [
  //_________________________________
  'D      Em            F#m',
  'Vas entrando en mi ciudad,',
  '         G',
  'y tanta gente',
  '         D',
  'que se agolpa',
  '     Em            F#m  G',
  'para ver quién es aquel',
  '     D Em F#m G',
  'Eres Tú,',
  '      D Em F#m G',
  'eres Tú.',
  'Tímidamente me reprocho',
  'que hoy tampoco te veré.',
  'Y son embargo encuentro el modo,',
  'de fingir',
  '                           D',
  'que igual no lo quería hacer.',
  'Em F#m      G D',
  '   Igual no lo',
  '            Em F#m',
  'quería hacer.',
  ' ',
  'D       F#m   Bm    A    E',
  'Pero estás pasando por aquí',
  'A7  Em    F#m',
  ' y algo está',
  '   G   F9   D',
  'pasándome a mí.',
  ' ',
  '        Em            F#m',
  'Voy a subirme a mi verdad,',
  '         G',
  'para aceptarme',
  ' A    D           Em',
  'como soy, y así mirarte',
  '      F#m',
  'a los ojos y que me',
  'G      A    D',
  'mires con amor. (2X)',
  ' ',
  'Vas entrando en mi casa, y las cosas',
  'que no quiero que descubras sobre mí',
  'están aquí, están aquí.',
  'Abres con fuerza las ventanas, que antes no',
  'reconocí y todo el sol de la mañana me develan',
  'ante ti, te develan ante mí.',
  ' ',
  'D       F#m      Bm     A',
  'Hoy has vuelto a confiar',
  '    E A7 Em F#m',
  'en mí,',
  '  Em    F#m   G     F9   D',
  'Y quiero regalar todo por ti.',
  '(Final:',
  '          G              F#m',
  'Y que me mires, y que me mires,',
  '          G     A   D',
  'Y que me mires con amor )',
];

export const TeAmarei = [
  //_________________________________
  'G                     C',
  'Me chamaste para caminhar',
  '          G',
  'na vida contigo,',
  '                        C',
  'decidi para sempre seguir-te,',
  '          D7',
  'não voltar atrás',
  '   G                     C',
  'Me puseste uma brasa no peito',
  '               G     Em',
  'e uma flecha na alma,',
  '      Am          D7',
  'é difícil agora viver',
  '                 G',
  'sem lembrar-me de ti',
  ' ',
  'Refrão:',
  '      D7',
  'Te amarei Senhor,',
  '        G    Em',
  'Te amarei Senhor',
  '        Am',
  'eu só encontro a paz e a',
  '  D7          G',
  'alegria bem perto de ti (bis)',
  ' ',
  '    G                       C',
  'Eu pensei muitas vezes calar',
  '                  G',
  'e não dar nem resposta,',
  '                       C',
  'eu pensei na fuga esconder-me,',
  '        D7',
  'ir longe de ti',
  '   G                        C',
  'mas tua força venceu e ao final',
  '                 G  Em',
  'e eu fiquei seduzido',
  '      Am            D7',
  'é difícil agora viver',
  '              G',
  'sem saudades de ti',
  ' ',
  'Refrão:',
  '      D7',
  'Te amarei Senhor,',
  '        G    Em',
  'Te amarei Senhor',
  '        Am',
  'eu só encontro a paz e a',
  '  D7          G',
  'alegria bem perto de ti (bis)',
  ' ',
  'Refrão:',
  '      D7',
  'Te amarei Senhor,',
  '        G    Em',
  'Te amarei Senhor',
  '        Am',
  'eu só encontro a paz e a',
  '  D7          G',
  'alegria bem perto de ti (bis)',
  ' ',
  '  G                   C',
  'Ó Jesus não me deixe jamais',
  '              G',
  'caminhar solitário',
  'pois conheces a minha fraqueza',
  '              D7',
  'e o meu coração',
  '   G                      C',
  'vem ensina-me a viver a vida',
  '             G  Em',
  'na tua presença',
  '    Am                      D7',
  'no amor dos irmãos na alegria',
  '            G',
  'na paz na união',
  ' ',
  'Refrão:',
  '      D7',
  'Te amarei Senhor,',
  '        G    Em',
  'Te amarei Senhor',
  '        Am',
  'eu só encontro a paz e a',
  '  D7          G',
  'alegria bem perto de ti (bis)'
];

export const TudoEDoPai = [
  //_________________________________
  '       C                G',
  'Eu pensei que podia viver',
  '         Am',
  'por mim mesmo',
  '       F                   Dm',
  'Eu pensei que as coisas do mundo',
  '      G',
  'não iriam me derrubar',
  '     C           G           Am',
  'O orgulho tomou conta do meu ser',
  '       F         Dm           G',
  'E o pecado devastou o meu viver.',
  ' ',
  '       F               G',
  'Fui embora, disse ao Pai:',
  '               C G',
  'dá-me o que é meu',
  '        F',
  'Dá-me a parte',
  '        G         C    Gm C',
  'que me cabe da herança.',
  '         F            G',
  'Fui pro mundo, gastei tudo',
  '          C         Am',
  'e me restou só o pecado.',
  '         F               G',
  'Hoje eu sei que nada é meu,',
  '            C G',
  'tudo é do Pai.',
  ' ',
  'Refrão:',
  '           C',
  'Tudo é do Pai,',
  '         G            Am',
  'toda a honra e toda a glória,',
  '             F',
  'É d’Ele a vitória',
  '     Dm             G',
  'alcançada em minha vida.',
  '           C',
  'Tudo é do Pai,',
  '         G         Am',
  'se sou fraco e pecador,',
  '                       F',
  'Bem mais forte é o Senhor,',
  '        G          C  (G)',
  'que me cura por amor. (2x)'
];

export const VemEEuMostrarei = [
  //_________________________________
  ' G            Em',
  'Vem, e eu mostrarei',
  '        Am              D7',
  'que o meu caminho te leva ao Pai,',
  '     G         Em',
  'guiarei os passos teus',
  '        Am            D7',
  'e junto de Ti hei de seguir.',
  '        G        Em',
  'Sim, eu irei e saberei',
  '     Am      D7',
  'como chegar ao fim.',
  '       G         Em',
  'De onde vim, aonde vou:',
  '        Am',
  'por onde irás,',
  ' D7      G Em Am D7 G',
  'irei também.',
  ' ',
  '     G',
  'Vem, e eu te direi',
  'Em             Am           D7',
  'o que ainda estás a procurar.',
  '     G         Em',
  'A verdade é como o sol',
  '      Am          D7',
  'e invadirá o teu coração.',
  '        G          Em',
  'Sim, eu irei e aprenderei',
  '    Am      D7',
  'minha razão de ser.',
  '        G           Em',
  'Eu creio em Ti que crês em mim',
  '       Am     D7',
  'e à Tua luz verei',
  '    G Em Am D7 G',
  'a luz.',
  ' ',
  '     G        Em',
  'Vem, e eu te farei',
  '       Am          D7',
  'da minha vida participar.',
  '     G         Em',
  'Viverás em mim aqui:',
  '       Am         D7',
  'viver em mim é o bem maior.',
  '        G         Em',
  'Sim, eu irei e viverei',
  '         Am     D7',
  'a vida inteira assim',
  '        G         Em',
  'eternidade é na verdade',
  '        Am      D7',
  'o amor vivendo sempre',
  '   G  Em Am D7 G',
  'em nós.',
  ' ',
  ' G                 Em',
  'Vem, que a terra espera',
  '             Am           D7',
  'quem possa e queira realizar,',
  '      G           Em',
  'com amor, a construção',
  '             Am         D7',
  'de um mundo novo muito melhor!',
  '         G        Em',
  'Sim, eu irei e levarei',
  '             Am      D7',
  'teu nome aos meus irmãos.',
  '        G           Em',
  'Iremos nós e o teu amor',
  '          Am     D7',
  'vai construir enfim,',
  '  G  Em Am D7 G',
  ' a paz!'
];

export const AbracoDePai = [
  //_________________________________
  '  E',
  'Quanto eu esperei.',
  'C#m        G#m',
  'Ansioso queria Te ver',
  '  F#m          G#m       A',
  'e Te falar o que há em mim.',
  'F#m           B         B7',
  'Já não podia me conter.',
  '    E',
  'Me decidi, Senhor.',
  'C#m             G#m',
  'Hoje eu quero rasgar meu viver',
  'F#m            G#m    A',
  'e te mostrar meu coração',
  'F#m              D     B',
  'Tudo o que tenho e sou.',
  '        E',
  'E por mais que me falem,',
  '      C#m',
  'não vou desistir!',
  '  F#m',
  'Eu sei que nada sou,',
  '    B            B7',
  'por isso estou aqui.',
  '        E',
  'Mas eu sei que o amor',
  '          C#m',
  'que o Senhor tem por mim',
  '  F#m',
  'É muito mais que o meu.',
  '     B        B7        E B',
  'Sou gota derramada no mar.',
  '       E',
  'Quanto tempo também',
  '     C#m',
  'o Senhor me esperou',
  '    F#m',
  'Nas tardes encontrou',
  '    B              B7',
  'saudade em meu lugar',
  '       E',
  'Mas ao me ver na estrada',
  '    C#m',
  'ao longe voltar',
  '    F#m',
  'Num salto se alegrou',
  '   B           B7        E B',
  'e foi correndo me encontrar',
  '      E',
  'E não me perguntou',
  '        C#m',
  'nem por onde eu andei',
  '    F#m',
  'Dos bens que eu gastei,',
  '      B           B7',
  'mais nada me restou',
  '       E',
  'Mas olhando em meus olhos',
  '  C#m',
  'somente me amor',
  'F#m           A F#m',
  'E ao me beijar,',
  '        B B7                E',
  'me acolheu  num abraço de Pai.'
];

export const AEleAGloria = [
  //_________________________________
  ' E     G#m          A     G#m',
  'Alfa , Ômega, Princípio e Fim,',
  '        A     F#m   B7',
  'sim Ele é, sim Ele é.',
  'E   G#m  C#m             A',
  ' Lírio do Vale, estrela da Manhã.',
  '     F#m          B7           E',
  'Para sempre cantarei o seu louvor.',
  'E  G#m  C#m             A      B7',
  'Lírio do Vale, Estrela da Manhã.',
  '         E   G#m         C#m',
  'A Ele a Glória, a Ele o Louvor,',
  '        A  F#m            D  B7',
  'Ele o Domínio, Ele é o Senhor.',
  '         E   G#m         C#m',
  'A Ele a Glória, a Ele o Louvor,',
  '         A    F#m    B7',
  'a Ele o Domínio, Ele é...'
];

export const AFonte = [
  //_________________________________
  '        G                     C',
  'Há uma fonte em mim, diga ao Senhor',
  'D            G                C',
  'que está brotando, que está fluindo',
  'D           G Em C  D',
  'Que está fluindo   dentro de mim',
  'G              C',
  'É um rio que avança',
  '      D         G   C',
  '(É um rio que avança)',
  'D         G',
  ' em adoração,',
  '          C',
  '(em adoração)',
  '    D         G            C',
  'dirigido para Ti Senhor Jesus,',
  '  D    G',
  'recebe-o.'
];

export const BastaQuerer = [
  //_________________________________
  'G               D         G',
  'Meu pensamento vive em Você,',
  '   D            G       C',
  'a luz do meu viver, Senhor.',
  'G                       D',
  'Basta entrar e eu me abrir',
  '         G',
  'pra Te amar.',
  '        D          G      C',
  'Nem precisa perguntar. Te amo.',
  ' ',
  'G/B Am       C   G/B      D',
  '   Há um clima todo diferente',
  'Am      G/B',
  '  que aquece e mexe com o',
  'C9          D',
  'coração da gente.',
  ' ',
  'G               D',
  'É como um sonho, é como um sonho.',
  '       C         Am             C       D',
  'Eu me dou por inteiro. Teu é o meu coração.',
  'G            D',
  'E ao Teu lado eu sempre sigo.',
  '        C          Am',
  'Já não há mais talvez,',
  '          C          D        Em  D',
  'basta querer pra Te ver outra vez.',
  '     C   G',
  'Outra vez'
];

export const DianteDoRei = [
  //_________________________________
  ' G          D/F#',
  'Vem, Senhor Jesus,',
  '        Em                      Bm',
  'meu coração já bate forte ao te ver,',
  '       C              Am        Bm',
  'A tua benção hoje eu quero receber,',
  '       C           Am        D',
  'sem a benção do Senhor, não sei viver.',
  ' G           D/F#',
  'Vem, Senhor Jesus,',
  '        Em',
  'olhar o povo ao teu redor',
  '           Bm',
  'me faz lembrar,',
  '        C         Am',
  'A multidão lá do caminho',
  '          Bm',
  'a te esperar.',
  '        C         Am',
  'Vem oh santo de Israel',
  '    D',
  'passar também neste lugar.',
  '     C            D',
  'É o rei a nossa frente está,',
  '     Bm           Em',
  'é feliz quem o adorar.',
  '     C           D',
  'É Jesus o nosso mestre rei.',
  '      Bm',
  'Bem aqui,',
  '              Em',
  'tão perto se deixa encontrar.',
  '        C           G',
  'Diante do rei dos reis,',
  '     Am         D    G Em',
  'todo joelho se dobrará.',
  '       C           G',
  'Diante do rei dos reis,',
  '     Am         D    G',
  'todo joelho se dobrará.'
];

export const CristoRey = [
  //_________________________________
  '   G       D/F#',
  'Jesús, te alabo,',
  '      C                 Am     D',
  'pues quiero en ti encontrar la Paz',
  '   G      D/F#',
  'Jesús, te adoro,',
  '      C                 Am',
  'pues por ti es todo el amor',
  '  D',
  'que yo siento',
  '      Em',
  'Por favor regálame,',
  '       Bm',
  'la sencillez de tu alma,',
  'C           Am    D',
  'El fuego de tu amor.',
  ' ',
  'Refrão:',
  '            G      D  Em',
  'Tú eres mi Rey, a ti alabo.',
  '     C',
  'Eres mi Pastor,',
  ' Am      D',
  'a ti me entrego,',
  '    G           Am/F# B7',
  'Tu cuerpo me da vida,',
  '   Em        A7',
  'tu sangre salvación,',
  'C      D           G',
  'Eres mi Señor, mi Dios.',
  ' ',
  'Jesús, te alabo,',
  'pues en ti me hago hijo,',
  'Jesús, te adoro,',
  'déjame cantarte hoy,',
  'El amor que yo',
  'siento por ti,',
  'El amor que hoy',
  'te entrego a ti.',
  ' ',
  'Jesús, te alabo,',
  'pues a ti te pertenece,',
  'Todo lo que puedo dar.',
  'Jesús, te adoro,',
  'hoy te entrego',
];

export const DeusEMaior = [
  //_________________________________
  'Bbm           C#',
  'Não, não há. Não, não há.',
  '       G#',
  'Não há mal',
  '           Fm       Bbm',
  'que eu não possa vencer. (2x)',
  ' ',
  '          F#',
  'Pois tudo posso',
  '   G#          C#   Bbm',
  'naquele que me fortalece',
  '     F#       G#    Bbm',
  'Tudo posso em Jesus Cristo (2x)',
  ' ',
  '   Bbm',
  'Nenhum problema,',
  '     C#               G#     Fm',
  'nem meus pecados poderão superar',
  '          Bbm',
  'o amor de Deus (2x)',
  ' ',
  '          F#',
  'Deus é maior',
  '    G#          C#  Bbm',
  'que tudo que me acontece.',
  '        F#       G#    Bbm',
  'Deus é grande, supremo Rei. (2x)',
  ' ',
  '   Bbm',
  'Nem a tristeza,',
  '    C#              G#     Fm',
  'nem mesmo a dor poderá superar',
  '          Bbm',
  'o amor de Deus. (2x)',
  ' ',
  '          F#',
  'Deus é maior',
  '    G#          C#  Bbm',
  'que tudo que me acontece.',
  '        F#       G#    Bbm',
  'Deus é grande, supremo Rei. (2x)',
  ' ',
  '   Bbm',
  'Nem a vingança,',
  '    C#               G#      Fm',
  'nem mesmo o ódio poderá superar',
  '          Bbm',
  'o amor de Deus. (2x)',
  ' ',
  '         F#',
  'Deus é maior',
  '    G#          C#  Bbm',
  'que tudo que me acontece.',
  '         F#      G#    Bbm',
  'Deus é grande, supremo Rei. (2x)'
];

export const DeusExiste = [
  //_________________________________
  'C                           F',
  'Quero saber porque não acreditas',
  'C                        F',
  'Quero saber porque não o tens',
  'como teu Senhor.',
  '      C',
  'Por que não aceitas',
  '                F',
  'que existe uma força',
  '                     C',
  'que move-nos para o bem.',
  '             G  F  G          C',
  'Que fé você tem? A fé que convém.',
  ' ',
  '        F',
  'Mas não é de conveniência',
  '      G',
  'que vive o Cristão',
  '       F',
  'Sua vivência está naquele',
  '         G',
  'que morreu por nós, irmãos.',
  ' ',
  ' F   G  C            F',
  'Deus existe e Ele está',
  '            G',
  'no meio de nós',
  '                        Am',
  'e por nós se deu numa cruz',
  '       F',
  'Pra pagar os nossos pecados',
  '       G',
  'de incrédulos cristãos.',
  ' F   G  C      F            G',
  'Deus existe e eu o posso tocar',
  '     E        Am',
  'se a Ele entregar o meu coração',
  '         F             G',
  'Pois é n’Ele que se encontra',
  '        C',
  'a salvação.'
];

export const DeusImenso = [
  //_________________________________
  'A           F#m           D',
  'Não sou nada,  eu bem sei',
  '      Bm',
  'Tão pequeno,',
  '             E                A',
  'um grão de areia em Tuas mãos',
  '            F#m                D',
  'Barco à vela   que se abandona',
  '        Bm',
  'Segue o rumo',
  '          E                A',
  'e vai buscando o alto mar.',
  '                 F#m             D',
  'Assim me encontro   diante de Ti',
  '          Bm',
  'Um Deus imenso',
  '          E',
  'que por amor se deixa alcançar',
  'A                     F#m',
  'Te adorarei, meu Deus.',
  '                    D',
  'Enquanto eu existir',
  '       Bm           E',
  'Proclamarei as maravilhas',
  'que fizeste em mim.',
  'A                     F#m',
  'O Teu amor me envolve,',
  '                      D',
  ' o teu olhar me acalma',
  '          Bm',
  'E em Teus braços',
  '         E',
  'o teu calor inflama a minha alma',
  'A                   F#m',
  'Que posso mais dizer',
  '                      Bm E',
  'se o coração ja disse',
  '   A',
  'Te amo.'
];

export const EmTuaPresenca = [
  //_________________________________
  '   G                    Am',
  'É teu este momento de adoração,',
  '     Bm',
  'não tenho nem palavras',
  '     Am           D',
  'para me expressar.',
  '     G',
  'No brilho dessa luz',
  '           Am',
  'que vem do Teu olhar.',
  '   C     G/B   Am',
  'Encontro meu abrigo,',
  '   D     G',
  'o meu lugar.',
  ' ',
  '   G',
  'E quando estamos juntos',
  '      Am',
  'entre nós está,',
  '   Bm',
  'passando em nosso meio',
  '       Am      D',
  'a nos abençoar.',
  '    G',
  'E tocas com ternura',
  '      Am',
  'com a Tua mão,',
  '   C   G/B    Am      D   G  D',
  'a cada um que abre o coração.',
  '        G       E7',
  'Minhas mãos se elevam,',
  '      Am C    D',
  'minha voz Te louva',
  '        Bm      E7',
  'e o meu ser se alegra',
  '          Am C',
  'Quando estou',
  '          D           G',
  'em Tua presença, Senhor!'
];

export const EuSouOQueSou = [
  //_________________________________
  '       G',
  'Eu sou o que sou.',
  '        C9',
  'Sou um Deus de amor.',
  '        G           D/F#',
  'Estou aqui pra te curar. (2x)',
  ' ',
  '      Am            D',
  'Vem a mim, dá-me tuas tristezas,',
  '      Am              D/F#',
  'Tuas dores e o teu coração. (2x)',
  '   G           C   G',
  'Te amo. És precioso.',
  '            Am      C',
  'Teu nome gravado está',
  '          D/F#',
  'em minhas mãos.',
  '   G            C  G',
  'Te amo. És precioso.',
  '            Am      C',
  'Teu nome gravado está',
  'D/F#        G',
  ' em minhas mãos'
];

export const Gratidao = [
  //_________________________________
  'Bb/C  C   F       C/E   Dm',
  'Eu encontrei um amor perfeito.',
  '     Gm        Gm/F',
  'Um tesouro escondido',
  '   C',
  'diante desse altar.',
  'Bb/C C       F    C/E      Dm',
  '     Seu valor é maior que tudo',
  'Gm      Gm/F       C    Bb/C C',
  'Nada poderá se igualar.',
  ' ',
  'F               Dm',
  'Te adorarei com todo o meu ser',
  '                  Gm7      Bb',
  'Quando estou mais perto de ti,',
  '          Dm        C',
  'fortaleces o meu viver',
  'F                  Dm',
  'Te exaltarei com o meu coração',
  '          Gm7      Bb',
  'Majestade, estou aqui',
  '           Dm         C',
  'para te render meu amor,',
  '        F',
  'minha gratidão.',
  ' ',
  'Bb/C   C  F          C/E   Dm',
  'A quem irei, se Tua voz é vida?',
  '       Gm           Gm/F',
  'Tua presença é tão clara',
  '        C',
  'e tão forte como o sol.',
  'Bb/C C     F         C/E',
  '    Sou feliz porque sei',
  '     Dm',
  'que vivo estás.',
  'Gm           Gm/F        C Bb/C C',
  'Tudo o que me resta é te amar.',
  ' ',
  'F               Dm',
  'Te adorarei com todo o meu ser',
  '                  Gm7      Bb',
  'Quando estou mais perto de ti,',
  '          Dm        C',
  'fortalece todo o meu ser.',
  'F                  Dm',
  'Te exaltarei com o meu coração',
  '           Gm7     Bb',
  'Majestade, estou aqui',
  '           Dm        C',
  'para te render meu amor,',
  '        C#',
  'minha gratidão.',
  '        G#',
  'Levantarei minhas mãos.',
  ' C#                    F',
  'Minha adoração irá tocar os céus.',
  'C#              D#',
  'Forte cantarei, Te adorarei,',
  '        C    C7',
  'Pão da vida.'
];
