export const SoEmTiViver = [
	//_________________________________
    "  A7+    Bm7             C#m7",
    "As coisas que o mundo oferecia",
    "Bm7                C#m7        Bm7",
    "  me impediram de Te encontrar",
    "              E            A  D  E",
    "De ver que a vida é só em Ti.",
    "A7+ Bm7           C#m7",
    "Mas, Tu vieste e tocaste",
    "Bm7                 C#m7      Bm7",
    "  bem no fundo do meu coração,",
    "        D          E",
    "Me ensinaste a Te amar.",
    " ",
    "Refrão:",
    "D E A    D         E",
    " Ó Jesus, recebe então",
    "       C#m   F#7",
    "a minha vida",
    "                        Bm         E",
    "Recebe as coisas que de Ti me afastam",
    "            D     E    A  (E)",
    "Pois só em Ti quero viver.",
    " ",
    " A7+ Bm7                C#m7",
    " ",
    "Agora   que meu coração é Teu,",
    "Bm7                C#m7  Bm7",
    " quero sempre Te louvar.",
    "     E            A  D  E",
    "Tua vida transbordar.",
    "A7+ Bm7                    C#m7",
    "Para  que mais gente experimente",
    "Bm7                   C#m7   Bm7",
    "  Teu amor nos transformando,",
    "     D          E",
    "Tua mão a nos tocar.",
    " ",
    "Refrão:",
    "D E A    D         E",
    " Ó Jesus, recebe então",
    "       C#m   F#7",
    "a minha vida",
    "                        Bm         E",
    "Recebe as coisas que de Ti me afastam",
    "            D     E    A  (E)",
    "Pois só em Ti quero viver."
];

export const TeuSou = [
	//_________________________________
    "C          G         Am",
    "Eu não sou nada e do pó nasci",
    " C       Am          Dm         G7",
    "Mas Tu me amas e morreste por mim.",
    " C          G     Am",
    "Diante da cruz só posso exclamar:",
    "     C  Am     F G",
    "Teu sou,  teu sou.",
    " ",
    "Refrão:",
    "             C       C7",
    "Toma minhas mãos, Te peço.",
    "              F         Fm",
    "Toma os meus lábios, te amo.",
    "            C      Am        Dm  G",
    "Toma minha vida, ó Pai, teu sou,",
    "     C  Am      Dm G     C",
    "Teu sou,  teu sou,  teu sou",
    " ",
    "  C         G        Am",
    "Quando de joelhos te olho, ó Jesus.",
    " C          Am       Dm           G7",
    "Vejo Tua grandeza e a minha pequenez.",
    " C         G         Am",
    "Que posso dar-te eu? Só meu ser.",
    "    C  Am      F  G",
    "Teu sou,  teu sou.",
    " ",
    "Refrão:",
    "             C       C7",
    "Toma minhas mãos, Te peço.",
    "              F         Fm",
    "Toma os meus lábios, te amo.",
    "            C      Am        Dm  G",
    "Toma minha vida, ó Pai, teu sou,",
    "     C  Am      Dm G     C",
    "Teu sou,  teu sou,  teu sou"
];

export const UmCoracaoParaAmar = [
	//_________________________________
    "G",
    "Um coração para amar",
    "                 Am",
    "Pra perdoar e sentir",
    " C              D",
    "Para chorar e sorrir",
    "                  G",
    "Ao me criar tu me deste",
    " ",
    "Um coração pra sonhar",
    "Inquieto e sempre a bater",
    "Ansioso por entender",
    "As coisas que Tu disseste",
    " ",
    "Refrão:",
    "  G7                  C",
    "Eis o que eu venho te dar",
    "D                      G",
    "Eis o que eu ponho no altar",
    "Em                    Am",
    "toma Senhor que ele é teu",
    "D                 G",
    "Meu coração não é meu (2X)",
    " ",
    "Quero que o meu coração",
    "Seja tão cheio de paz",
    "Que não se sinta capaz",
    "De sentir ódio ou rancor",
    " ",
    "Quero que a minha oração",
    "Possa me amadurecer",
    "Leve-me a compreender",
    "As consequências do amor",
    " ",
    "Refrão:",
    "  G7                  C",
    "Eis o que eu venho te dar",
    "D                      G",
    "Eis o que eu ponho no altar",
    "Em                    Am",
    "toma Senhor que ele é teu",
    "D                 G",
    "Meu coração não é meu (2X)"
];

export const VenhoSenhor = [
	//_________________________________
    " G                   D/F#      Em",
    "Venho, Senhor, minha vida oferecer",
    " C          G           C      D7",
    "Como oferta de amor e sacrifício",
    " G        D/F#     Em",
    "Quero minha vida a Ti entregar",
    " C          D7             G  Dm G7",
    "Como oferta viva em Teu altar.",
    " ",
    "Refrão:",
    "C           D    G",
    "Pois pra Te adorar",
    "Em  Am  D7       Em",
    "   foi que eu nasci.",
    "Bm              C",
    "Cumpra em mim o Teu querer.",
    "Am           D7",
    "Faça o que está",
    "            G  Dm  G7",
    "em Teu coração",
    "C             D      B7             Em",
    "E que a cada dia eu queira mais e mais",
    "   Am        D7        Am       D7",
    "Estar ao Teu lado, estar ao Teu lado,",
    "   Am        D7        G",
    "estar ao Teu lado, Senhor."
];

export const VouTeOferecer = [
	//_________________________________
    " E                 B",
    "Vou Te oferecer a vida",
    "   E                      B",
    "e tudo o que eu já sei viver",
    " E         E/D      A           Am",
    "Tempo e trabalho, amor que eu espalho,",
    "     E             B B7   E",
    "são coisas que me fazem crer.",
    " E                 B",
    "Vou Te oferecer o pranto,",
    "   E                 B",
    "aquilo que é meu sofrer.",
    " E                E/D    A          Am",
    "Paz que ainda não sei e tudo que errei,",
    "     E             B B7   E  E7",
    "são coisas que me fazem crer.",
    " ",
    "Refrão:",
    " A           B7     E          C#m",
    "Pão e vinho são sinais do Teu amor",
    " A           B7    E",
    "Neles vou saber viver.",
    " E        E/D     A           Am",
    "Alegria e dor eu vou te oferecer.",
    "     E             B B7   E",
    "São coisas que me fazem crer."  
];

export const OSenhorESanto = [
    //_________________________________
    "Refrão:",
    "      E",
    "O Senhor é Santo,",
    "   E/C#m",
    "o Senhor é Santo,",
    "      E/B",
    "o Senhor é Santo",
    " ",
    "      E          C#m",
    "O Senhor é nosso Deus.",
    "     F#m          B",
    "O Senhor é nosso Pai.",
    "         E        C#m",
    "Que Seu reino de amor",
    "     F#m            B  E  (B)",
    "se estenda sobre a Terra.",
    " ",
    "Refrão:",
    "      E",
    "O Senhor é Santo,",
    "   E/C#m",
    "o Senhor é Santo,",
    "      E/B",
    "o Senhor é Santo",
    " ",
    "    E         C#m     E          B",
    "Bendito o que vem em nome do Senhor",
    "    A          B      A    B     E",
    "Bendito o que vem em nome do Senhor",
    " ",
    "Refrão:",
    "   E       C#m     A    B    E",
    "Hosana! Hosana! Hosa...a...na."
];

export const SantoJustoForte = [
	//_________________________________
    "G       Em    Bm",
    "Santo, Santo, Santo é o Senhor.",
    " C            Am           D",
    "Santo é o Senhor Deus poderoso. (2x)",
    " ",
    "Refrão:",
    "    C     B7         Em    D",
    "Que era, que é, e que há de vir.",
    "G      Em     C    D        G",
    "Santo, Santo, Santo é o Senhor.",
    " ",
    "G     Em      Bm",
    "Justo, forte, Santo é o Senhor,",
    " C            Am             D",
    "Santo é o Senhor Deus poderoso (2x)",
    " ",
    "Refrão:",
    "     C   B7         Em    D    G",
    "Que era, e que é, e que há de vir.",
    "      Em      C     D         G",
    "Justo, Forte, Santo é o Senhor."
];

export const SantoDeusDoUniverso = [
	//_________________________________
    "Bm      Em     A            D",
    "Santo, Santo, Santo é o Senhor",
    " Bm         Em",
    "Deus do universo,",
    "    F#7       Bm",
    "do céu e da Terra. (2X)",
    " ",
    "Refrão:",
    "B7  Em   A   D",
    "Hosana, Hosana,",
    "Bm   Em  F#7    Bm",
    "Hosana nas alturas (2x)",
    " ",
    "Bm            Em     A           D",
    "Bendito o que vem em nome do Senhor",
    "  Bm          Em    F#7    Bm",
    "Hosana nas alturas, nas alturas."
];

export const SantoDizemTodosOsAnjos = [
	//_________________________________
    " Em",
    "Santo, Santo, Santo,",
    "                B7",
    "dizem todos os anjos!",
    "Santo,Santo,",
    "                   Em",
    "Santo é o Senhor Jesus!",
    " ",
    "Refrão:",
    "Santo, Santo,",
    "      E7           Am",
    "Santo é quem nos redime:",
    "   Am                Em",
    "/: Porque meu Deus é Santo",
    "          B7",
    "e a Terra cheia de",
    "             Em",
    "sua Glória está! :/",
    "                      B7",
    "/: Céus e Terra passarão,",
    "                         Em",
    "mas tua palavra não passará! :/",
    " Am    Em   B7    Em",
    "Não, não, não passará!",
    "               Am",
    "Não, não, não, não,",
    "Em   B7     Em",
    "não, não passará!",
    " ",
    " Em",
    "Hosana a Jesus Cristo,",
    "             B7",
    "o Filho de Maria!",
    "Bendito o que vem,", 
    "          Em",
    "em nome do Senhor!"
];

export const SantoE = [
	//_________________________________
    " A    C#m       F#m    C#m",
    "Santo, Santo é. Santo, Santo é.",
    " D           A         B7      E",
    "Deus do Universo ó Senhor Javé. (2X)",
    "   D       E ",
    "O Céu e a Terra",
    "        A        F#m",
    "vos proclamam glorioso,",
    "  D       E           A F#m",
    "Hosana, Hosana nas alturas.",
    "    D          E     A         F#m",
    "Bendito o que vem em nome do Senhor,",
    "  D       E           A  F#m",
    "Hosana, Hosana nas alturas.",
    "  D       E        A",
    "Hosana, Hosana ao rei. (2X)"
];

export const APazEstejaContigo = [
	//_________________________________
    " E              A  E",
    "A paz esteja contigo,",
    "                A E",
    "a paz esteja comigo",
    "   E             A",
    "A paz esteja com ele,",
    "    E         F#7         B7",
    "com ela e com todos os irmãos.",
    "   E            A  E",
    "A paz esteja contigo,",
    "                A E",
    "a paz esteja comigo",
    "   E             A",
    "A paz esteja com ele,",
    "    E         A           E",
    "com ela e com todos os irmãos.",
    " ",
    "Am            E",
    "Como Jesus pediu.",
    "Am           E",
    "Como Jesus orou.",
    "Am                  E",
    "Como Jesus nos ensinou.",
    " ",
    "E     A    E            A9",
    "Paz, paz, paz na nossa Igreja.",
    "E      Am",
    "Paz na Terra",
    "                      E",
    "em toda parte e assim seja. (2x)",
    " ",
    "E         A9",
    "Paz pra você",
    "          Am          E",
    "que tem Jesus no coração.",
    "C#m7      F#7           Am7",
    "Paz pra você que é meu amigo",
    "         E",
    "e meu irmão. (2x)"
];

export const AperteAMinhaMao = [
	//_________________________________
    "  G",
    "Aperte a minha mão, irmão,",
    "   Em",
    "quero te dar a paz,",
    "C          D",
    "do meu Senhor.",
    "  G",
    "Me dê um abraço forte,",
    "         Em",
    "bem mais forte do que forte,",
    "     C        D",
    "num gesto de amor.",
    "   C          D",
    "A paz do Senhor",
    "          Bm        Em",
    "quero te dar meu irmão,",
    "     C",
    "com toda alegria",
    "      D               G G7",
    "que existe no meu coração."
];

export const PazPazDeCristo = [
    //_________________________________
    "Refrão:",
    "Em",
    "Paz, paz de Cristo.",
    " D",
    "Paz, paz que vem",
    "     Em        B7     Em",
    "Do amor, te desejo irmão",
    "Em                D",
    "Paz, que é felicidade",
    "            Em",
    "de ver em você",
    "         B7      Em  E7",
    "Cristo, nosso irmão.",
    " ",
    "                Am",
    "Se algum dia na vida",
    "D                  G",
    " você de mim precisar",
    "Em                 Am",
    "Saibas que sou seu amigo,",
    "B7                Em  E7",
    "  podes comigo contar.",
    "                 Am",
    "O mundo dá tantas voltas.", 
    "D                     G",
    " A gente vai se encontrar.",
    "Em                    Am",
    " Quero, nas voltas da vida,",
    "B7               Em",
    "  a sua mão apertar."
];

export const QueroTeDarAPaz = [
    //_________________________________
    "Refrão:",
    " G            Em",
    "Quero te dar a paz,",
    "          C  Am          D",
    "do meu Senhor com muito amor.",
    " ",
    "Na flor vejo o manifestar o poder da criação",
    "nos teus lábios eu vejo estar o sorriso de um irmão.",
    "Toda vez que eu te abraço e aperto a sua mão,",
    "sinto forte o poder do amor dentro do meu coração.",
    " ",
    "Refrão:",
    " G            Em",
    "Quero te dar a paz,",
    "          C  Am          D",
    "do meu Senhor com muito amor.",
    " ",
    "Deus é Pai e nos protege, Cristo é Filho e Salvação,",
    "Santo Espírito consolador na trindade somos irmão.",
    "Toda vez que eu te abraço e aperto a sua mão,",
    "sinto forte o poder do amor dentro do meu coração.",
    " ",
    "Refrão:",
    " G            Em",
    "Quero te dar a paz,",
    "          C  Am          D",
    "do meu Senhor com muito amor."
];

export const Shalom = [
	//_________________________________
    "C                      G",
    "A paz que tenho eu te dou",
    "Am                       G",
    "A paz que tenho vem do amor de Deus.",
    "C                      G",
    "A paz que tenho eu te dou",
    "D                        G",
    "A paz que vem do meu Senhor",
    " ",
    "Refrão:",
    "C                      Am",
    "Shalom! Te amo, meu irmão.",
    "                 F",
    "Jesus é nossa união.",
    "G             C   (G)",
    "A verdadeira paz. (2x)",
    " ",
    "Buscando a graça e oração",
    "Amando a todos os irmãos",
    "Colheremos o perdão",
    "Realizando a salvação",
    " ",
    "Refrão:",
    "C                      Am",
    "Shalom! Te amo, meu irmão.",
    "                 F",
    "Jesus é nossa união.",
    "G             C   (G)",
    "A verdadeira paz. (2x)"
];

export const SonhoDePaz = [
	//_________________________________
    "        D          G",
    "1. Ele veio e ensinou",
    "               Em      A",
    "que o amor conduz à unidade",
    "      D              G",
    "E que repartindo o pão,",
    "         Em       A",
    "a paz se faz realidade",
    "          G          A",
    "Que é preciso muito mais",
    "         F#m          Bm",
    "que um poema e um refrão",
    "      Em         D",
    "É preciso que o homem",
    "     G         A",
    "abra o seu coração.",
    " ",
    "Refrão:",
    "D             A    Bm",
    "A paz que é tão sonhada,",
    "Em          G           A",
    "cantada em canções tão lindas",
    "D        A     Bm",
    "Só chegará até nós",
    " Em       G        A         D",
    "quando ouvirmos a voz do Senhor.",
    " ",
    "2. Há milhares de menores desprezados por aí",
    "E há crianças inocentes que não têm pra onde ir.",
    "“Eu estou presente neles, é a mim que rejeitais.",
    "Se me negais vosso amor, como quereis ter a paz?”",
    " ",
    "Refrão:",
    "D             A    Bm",
    "A paz que é tão sonhada,",
    "Em          G           A",
    "cantada em canções tão lindas",
    "D        A     Bm",
    "Só chegará até nós",
    " Em       G        A         D",
    "quando ouvirmos a voz do Senhor.",
    " ",
    "3. Se hoje fabricais bombas muitas armas e canhões",
    "Tantos mais duros e frios serão vossos corações",
    "Mas é tempo de mudança, de voltar para o Senhor",
    "E de se cantar com a vida que mais forte é o amor.",
    " ",
    "Refrão:",
    "D             A    Bm",
    "A paz que é tão sonhada,",
    "Em          G           A",
    "cantada em canções tão lindas",
    "D        A     Bm",
    "Só chegará até nós",
    " Em       G        A         D",
    "quando ouvirmos a voz do Senhor."
];

export const CordeiroDeDeus = [
	//_________________________________
    "    E       G#m",
    "Cordeiro de Deus",
    "     C#m        A F#m   B",
    "que tirais o pecado do mundo",
    " E      G#m       A",
    "Tende piedade de nós",
    "    E       G#m",
    "Cordeiro de Deus",
    "     C#m        A F#m   B",
    "que tirais o pecado do mundo",
    " E      G#m       A",
    "Tende piedade de nós",
    "    E       G#m",
    "Cordeiro de Deus",
    "     C#m        A F#m   B",
    "que tirais o pecado do mundo",
    "E   G#m    A",
    "Dai-nos a paz.",
    "   E",
    "A paz."
];

export const CordeiroDeDeusShalom = [
	//_________________________________
    "    E",
    "Cordeiro de Deus ",
    "       G#m              A",
    "que tirais o pecado do mundo",
    " B7",
    "Tende piedade",
    "    E",
    "Cordeiro de Deus ",
    "       G#m              A",
    "que tirais o pecado do mundo",
    " B7",
    "Tende piedade",
    "    E",
    "Cordeiro de Deus ",
    "       G#m              A",
    "que tirais o pecado do mundo",
    "           E   G#m",
    "Dai-nos a paz. ",
    "           A  B7",
    "Dai-nos a paz.",
    "           E       G#m",
    "Dai-nos a vossa paz.",
    "           A  B7",
    "Dai-nos a paz.",
    "             E",
    "Cordeiro de Deus"
];

export const CorderioDeDeus2 = [
	//_________________________________
    "       G Am     D",
    "/: Cordeiro de Deus,",
    "     C D     G",
    "cordeiro de Deus",
    "C  Am   D         C Am     D",
    "Tu que tiras o pecado do mundo",
    "        C       G",
    "tem piedade de nós :/",
    " ",
    "    G Am     D",
    "Cordeiro de Deus,",
    "     C D     G",
    "cordeiro de Deus",
    " C Am     D    C D     G",
    "Dá-nos a paz. Dá-nos a paz."
];