export const CantoADeus = [
  //_________________________________
  'Refrão:',
  '  D             A',
  'Grande é Teu carinho,',
  ' Bm           F#m',
  'para com teus filhos.',
  ' G           D',
  'Ternos és o Pai',
  '              E     A',
  'com aqueles que te amam.',
  ' D        A    Bm            F#m',
  'Tu bem o sabes de que somos feito.',
  ' G             D            A D',
  'Tu te lembras de que somos terra.',
  ' ',
  'Bm                  F#m',
  'Deus olha e nos sustenta.',
  'G                    D',
  'Nos acolhe e nos protege.',
  'Am    D7           G',
  'Seu amor nos regozija',
  'E7                    A',
  ' em nossa terrena andança.',
  'Bm                    F#m',
  'O Pai vai nos transformando,',
  ' G                   D',
  'como o oleiro a seu barro.',
  'Am     D7         G    E7',
  'Somos sua voz, semente,',
  '                 A',
  'a terra de seus amores.',
  ' ',
  'Bm                 F#m',
  'E faz com que se elevem,',
  'G                 D',
  ' pelas mãos de Maria,',
  'Am       D7           G E7',
  'Homens cheios de alegria,',
  '                   A',
  'de Sua graça portadores.',
  'Bm                F#m',
  'Ide e inflamai o mundo.',
  'G               D',
  'É divisa e profecia.',
  'Am      D7      G  E7',
  'Pelas mãos de Maria',
  '                 A',
  'é missão de fundadores.'
];

export const AlzarBanderas = [
  //_________________________________
  'C                  G',
  'Vamos a abrir la esperanza Señor',
  'F         G        C        G/B',
  'Vamos que nos falta tiempo',
  'Am               Em',
  'Para tornar nuestras manos en pan',
  'F      C         G',
  'Para forjar cielo nuevo.',
  'C                G',
  'Vamos a juntar espadas de amor',
  'F         G           C  G/B',
  'Para dejar nuestra huella',
  'Am                 Em',
  'Pisando tierra llevando el altar',
  'F      C       G',
  'Y eliminando fronteras...',
  ' ',
  'F        G          Am        G',
  'Y que el cielo se cubra de luz',
  'F        E            Am      G',
  'Y que la tierra se llene de cruz',
  'F     G        C    G/B  Am',
  'Pues venimos tu sueño a cumplir',
  '      F        D/F#      G',
  'Congregante por Cristo a morir',
  ' ',
  'Refrão:',
  'C                A#',
  'Sueña con alzar banderas',
  'C         G',
  'Sueña con Cristo',
  '   Am       G',
  'y ponte en su lugar',
  'Em        E7      Am       D',
  'Y que podamos construir ciudad',
  'Fm         C      G',
  'Con nuestra Reina en ella',
  'C             A#',
  'Vamos a dejar pisadas',
  'C     G        Am      G',
  'Y corazones cambiar con amor',
  'Em         E7        Am    F',
  'Y que lo hecho sea prueba final',
  '        Dm     G        Am  G',
  'De que Cristo habita mi hogar',
  '       F       G        Am  G',
  'De que Cristo habita tu hogar',
  '        F       G',
  'De que Cristo habita (renace)',
  '     C',
  'en nuestro hogar',
  ' ',
  'C                G',
  'Danos las ganas de servir Señor',
  'F        G         C  G/B',
  'Te regalamos los sueños',
  'Am                Em',
  'Para soñar con tu anhelo de paz',
  'F     C         G',
  'Y refundar este tiempo.',
  'F       G           Am        G',
  'Y que podamos tu nombre gritar',
  'F        E          Am      G',
  'Para la tierra poder conquistar',
  'F          G        C    G/B  Am',
  'Porque tus manos ya no tienen fin',
  '      F        D/F#    G',
  'Padre Santo queremos servir.'
];

export const ComoFogoNascemos = [
  //_________________________________
  'Introdução: Fmaj7 C (2x)',
  ' ',
  '  Fmaj7                  C',
  'E o verbo fez-se carne. Faça-se!',
  '  Fmaj7',
  'Cumpriu-se a promessa.',
  '    C                   G',
  'A vitória sobre Eva foi vencida pela',
  ' Am F     C G',
  'Ave   Maria',
  ' Am F   C G',
  'Ave   Maria',
  ' ',
  ' Fmaj7                  C',
  'Um belo vale escolhes. Faça-se!',
  'Fmaj7',
  'O Pai a ti se entrega.',
  '   C',
  'Confiante nessa ideia,',
  '     G',
  'se consagra todo à',
  ' Am F     C G',
  'Ave   Maria',
  ' Am F   C G',
  'Ave   Maria',
  ' ',
  'C D Fmaj7',
  ' ',
  'Fmaj7                C',
  'E como fogo nasce. Faça-se!',
  'Fmaj7                  C',
  'A nova Geração de Missionários,',
  '               G',
  'levam Cristo vinculados pela',
  ' Am F     C G',
  'Ave   Maria',
  ' Am F   C G',
  'Ave   Maria',
  ' ',
  ' D   Bm  A    D   Bm  A',
  'Ave Maria,   Ave Maria',
  ' ',
  'F',
  'Ave Maria,',
  'G                A',
  'nossa alegria é aqui estar',
  '           F               Em',
  'Em teu Santuário envia-nos Tu,',
  '               D',
  'a estrela, nos guiará',
  '  F            G             A',
  'Nossa Rainha, Tua Heroica Coroa faz',
  '       F',
  'Protagonistas,',
  '   Em                D',
  'nós iremos o mundo inflamar'
];

export const ContigoCaminhar = [
  //_________________________________
  '  A                E',
  'Quero contigo caminhar,',
  'F#m                 C#m',
  'porque algo aconteceu',
  'D                 A E',
  'A esperança apareceu',
  ' ',
  'D                    F#m',
  'Não sei bem te explicar,',
  'D                   F#m*',
  'Só sei que o que eu levo',
  '        E        D E',
  'eu preciso espalhar.',
  ' ',
  'D                     F#m*',
  'São sementes em tuas mãos,',
  '       E            D',
  'Que me das no coração',
  '       Bm7',
  'Se perguntas: “Quem Hei de enviar?”',
  '       E D/F# F#m*     E',
  'Eu respondo: “Eis-me aqui!”',
  ' ',
  'Refrão:',
  '       A E F#m*',
  'Com Maria,',
  '   D   E     A  E F#m* D',
  'envia-me Senhor',
  'E      A E F#m*',
  'Com Maria,',
  '   D   E     A  E F#m*',
  'envia-me Senhor',
  'Bm7             C#m7',
  'Mais forte que o medo,',
  '             D',
  'o amor anunciar',
  '                F#m*',
  'Esse amor que eu carrego',
  '    E',
  'é de Ti.',
  ' A                 E',
  'Em carência vejo o mundo,',
  'F#m              C#m',
  ' Terra seca abandonada,',
  'D                  A  E',
  'Inquieto eu me levanto',
  ' ',
  'D                  F#m',
  'Para ser Teu instrumento',
  'D                 F#m*',
  'Passo a passo alegria',
  '    E        D  E',
  'e amor entregar.',
  ' ',
  'D                      F#m*',
  'São sementes em tuas mãos,',
  '        E           D',
  'Que me das no coração',
  '       Bm7',
  'Se perguntas: “Quem Hei de enviar?”',
  '       E D/F# F#m*    E',
  'Eu respondo: “Eis-me aqui!”',
  ' ',
  'F#m* = 044200'
];

export const DuasEspadas = [
  //_________________________________
  'G  D/F#       Em        Bm',
  'Na força da aliança de amor',
  'C        G   C        D',
  'buscamos meios pra conquistar',
  'G    D/F#    Em      Bm',
  'o alto ideal que em nós',
  'C       G   C        D',
  ' faz brotar  o homem novo',
  'G  D/F#   Em     Bm',
  'No Santuário encontramos',
  'C      G     C          D',
  'duas espadas, vamos lutar',
  'G  D/F#   Em       Bm',
  'o mundo precisa de nós',
  'C          G   C         D',
  'santos modernos queremos ser',
  'Em                F#m',
  ' Como aquele que um dia lutou',
  'G                    A',
  ' em meio à guerra se santificou.',
  ' ',
  'D    A',
  'José Engling',
  'Bm               F#m',
  ' tua missão também vive em mim',
  'G                   D',
  ' somos irmãos na Aliança de amor',
  'E            A',
  ' aliados do Pai Fundador. (2X)'
];

export const EleAmouAMaria = [
  //_________________________________
  'Refrão:',
  ' C          Em',
  'Ele amou a Maria,',
  ' F           G',
  'nós amamos também',
  'C            Em',
  'Ele amou a igreja,',
  '  F          G',
  'nós amamos também',
  'C         Em           F',
  'Conhecemos seu segredo,',
  '          G',
  'assumimos a missão',
  'C         Em           F',
  'Sua voz em nós se ouça,',
  '            G        C',
  'seu carisma nossa força',
  ' ',
  '   C           Em',
  '1. Seu carisma nossa força',
  'F               G7',
  'rumo aos tempos que virão',
  'C          Em',
  'Santuário, Mãe, família',
  'F           G7',
  'e ao Pai vinculação.',
  ' C         Dm     G7',
  'Seu amor um compromisso,',
  'C         Dm        G7',
  'seu saber é que nos guia',
  ' C           Em',
  'seu clamor é de profeta,',
  'Dm         G7     C',
  ' um profeta de Maria.',
  ' ',
  'Refrão:',
  ' C          Em',
  'Ele amou a Maria,',
  ' F           G',
  'nós amamos também',
  'C            Em',
  'Ele amou a igreja,',
  '  F          G',
  'nós amamos também',
  'C         Em           F',
  'Conhecemos seu segredo,',
  '          G',
  'assumimos a missão',
  'C         Em           F',
  'Sua voz em nós se ouça,',
  '            G        C',
  'seu carisma nossa força',
  ' ',
  '2. Seu carisma nossa força, construindo um novo mundo',
  'nova ordem social que nasce do mais profundo',
  'do coração que se entrega e que se deixa moldar',
  'pelas mãos de uma Rainha que tem o dom de educar.',
  ' ',
  'Refrão:',
  ' C          Em',
  'Ele amou a Maria,',
  ' F           G',
  'nós amamos também',
  'C            Em',
  'Ele amou a igreja,',
  '  F          G',
  'nós amamos também',
  'C         Em           F',
  'Conhecemos seu segredo,',
  '          G',
  'assumimos a missão',
  'C         Em           F',
  'Sua voz em nós se ouça,',
  '            G        C',
  'seu carisma nossa força',
  ' ',
  '3. Seu carisma nossa força, a família construindo,',
  'berço da humanidade que por ela vem surgindo.',
  'Membros vivos da igreja e fecundos no atuar.',
  'Dando testemunho vivo vão ao mundo abrasar.',
  ' ',
  'Refrão:',
  ' C          Em',
  'Ele amou a Maria,',
  ' F           G',
  'nós amamos também',
  'C            Em',
  'Ele amou a igreja,',
  '  F          G',
  'nós amamos também',
  'C         Em           F',
  'Conhecemos seu segredo,',
  '          G',
  'assumimos a missão',
  'C         Em           F',
  'Sua voz em nós se ouça,',
  '            G        C',
  'seu carisma nossa força',
  ' ',
  '4. Seu carisma nossa força, faz de nós no Santuário',
  'seu presente vivo e puro, nosso dom ao centenário.',
  'Como ele amar Maria, como ele ser profeta.',
  'Refleti-lo em nós, na vida, eis enfim a nossa meta.',
  'Refrão:',
  ' C          Em',
  'Ele amou a Maria,',
  ' F           G',
  'nós amamos também',
  'C            Em',
  'Ele amou a igreja,',
  '  F          G',
  'nós amamos também',
  'C         Em           F',
  'Conhecemos seu segredo,',
  '          G',
  'assumimos a missão',
  'C         Em           F',
  'Sua voz em nós se ouça,',
  '            G        C',
  'seu carisma nossa força'
];

export const EntregaDeAmor = [
  //_________________________________
  'Am            G',
  'A passos largos para encontrar',
  'Dm                G',
  'ansioso pela lembrança',
  'Am                 G',
  'no Santuário vem habitar',
  'Dm                Am',
  ' consagra a esperança',
  '          G      F',
  'E a força para lutar',
  ' ',
  'Em dura marcha a caminhar',
  'fortalecido na Aliança',
  'pela herança, missão do Pai',
  'no coração, confiança',
  'para se entregar',
  ' ',
  '       G                    F',
  'Na batalha, o amor anunciar',
  '         G                 Am',
  'Para o mundo inteiro inflamar',
  ' ',
  'Refrão:',
  'Am',
  ' E o fogo que arde',
  '    G          Dm',
  'lá fora não cessou',
  '               G',
  'A chama que outrora',
  '        G7',
  'a todos incendiou',
  'Am',
  ' Pela missão que',
  '     G         Dm',
  'a Senhora confiou',
  '        G',
  'Aceita agora',
  '        G7       Am G',
  'essa entrega de amor,',
  '            Dm G G7 Am',
  'entrega de amor'
];

export const EnTusManos = [
  //_________________________________
  'C',
  'Pongo en Tus manos hoy',
  'G/B            Am',
  'toda mi vida y todo mi ser,',
  'Am/G   F  G C G',
  '  oh Maria.',
  'C                    G/B',
  'Pongo en Tus manos toda',
  '                 Am         Am/G',
  'mi esperanza y toda mi ilusión,',
  '  F G C C7',
  'oh Maria.',
  ' ',
  'Refrão:',
  '            F                   G',
  'Y aunque caiga en el pozo más hondo,',
  ' C          G/B      Am  Am/G',
  'sé que Vos me vas a levantar,',
  '       F                       G',
  'Porque yo por Schoenstatt doy todo',
  '   C         G/B     Am     Am/G',
  'y sé que el Padre me va a escuchar',
  '    F              G',
  'Por eso hoy me consagro',
  '       C G/B Am Am/G',
  'todo a Vos.',
  '    F             G             C',
  'Por eso hoy me consagro todo a Vos.',
  ' ',
  'Pongo en Tus manos todo mi trabajo',
  'y toda mi labor, oh Maria.',
  'Pongo en Tus manos todo el sacrificio',
  'del dia de hoy, oh Maria.',
  '(após o refrão sobe 1 tom)',
  'A7 D                    A',
  '  Pongo en Tus manos toda mi tristeza',
  '    Bm         Bm/A',
  'y todo mi dolor,',
  '   G A D A',
  'oh Maria.',
  'D                    A',
  'Pongo en tus manos todo el amor',
  '       Bm          Bm/A',
  'que yo tengo por Vos,',
  '   G A D D7',
  'oh Maria.',
  ' ',
  'Refrão:',
  '           G                   A',
  'Y aunque caiga en el pozo más hondo,',
  ' D         A         Bm  Bm/A',
  'sé que Vos me vas a levantar,',
  '        G                      A',
  'Porque yo por Schoenstatt doy todo',
  '   D         A       Bm      Bm/A',
  'y sé que el Padre me va a escuchar',
  '    G              A',
  'Por eso hoy me consagro',
  '       D  A/C# Bm Bm/A',
  'todo a Vos.',
  '    G              A',
  'Por eso hoy me consagro',
  '       D  A/C# Bm Bm/A',
  'todo a Vos.',
  '    A              A',
  'Por eso hoy me consagro',
  '       D',
  'todo a Vos.'
];

export const EuSoSeiTeAmar = [
  //_________________________________
  'A9          D9       E',
  'Ave Maria a Mãe do Senhor',
  '       A9            D9      E',
  'Dentre todas a mais bela mulher',
  '     F#m                  C#m',
  'É Senhora da Aliança e do meu coração',
  '      D',
  'Instrumento de Deus Pai',
  '  E              (D E)',
  'Amor e perfeição',
  ' ',
  'A9                D9      E',
  'Quando em teu santuário entrei',
  '   A9        D9        E',
  'Senti tua presença em mim',
  'F#m               C#m',
  'Quero minha vida a ti entregar',
  '      D',
  'Orgulhar-te como Mãe',
  '       E               (D9/F# E/G#)',
  'E como filho te abraçar',
  ' ',
  'Refrão:',
  'A9      E/G#          F#m',
  'Vou ser herdeiro dessa linda canção',
  'D        Bm             E',
  'E me entregando sua missão assumir',
  'A9      E/G#         F#m',
  'Soltar a voz abrir o meu coração',
  ' D                    Bm',
  'Demonstrar minha confiança',
  '      E        A9  (D9 E)',
  'e dizer Estou aqui',
  ' ',
  'A9                  D9      E',
  'Cheia de graça intercede por mim',
  '    A9             D9          E',
  'Maravilhas fez com apenas um sim',
  'F#m                  C#m',
  'Para a santidade ela sempre conduz',
  '    D',
  'A caminho do seu filho',
  '  E           (D9/F# E/G#)',
  'O Cristo Jesus',
  ' ',
  'Refrão:',
  'A9        E/G#          F#m',
  'Vou ser herdeiro dessa linda canção',
  'D      Bm              E',
  'E me entregando sua missão assumir',
  'A9       E/G#         F#m',
  'Soltar a voz abrir o meu coração',
  'D                   Bm          E',
  'Demonstrar minha confiança e dizer',
  '         A9',
  'Estou aqui',
  'A9      E/G#          F#m',
  'Vou ser herdeiro dessa linda canção',
  'D      Bm             E',
  'E me entregando sua missão assumir',
  'A9       E/G#        F#m',
  'Soltar a voz abrir o meu coração',
  'D                    Bm    E',
  'E olhando nos teus olhos falar',
  '                 A9',
  'Eu só sei te amar.'
];

export const Fiat = [
  //_________________________________
  'Intro: E D G A9 E D A9',
  ' ',
  '      E               D',
  'Com poder soberano continua',
  '  G             A9',
  'a Tua missão de Caná.',
  '   E        D          A9',
  'Fazei o que Ele vos disser.',
  '  E                    D',
  'O filho que a Ti recorrer,',
  ' G                   A9',
  'Deus, sua alma, acolherá.',
  '      E',
  'Teu poder avança',
  '    D         A9  B',
  'a hora do Teu Filho.',
  ' ',
  '    E        G9',
  'Tua força, Rainha,',
  '     A/C#       C D',
  'a serviço desse fogo.',
  '     E',
  'É missão dos Teus servos,',
  '  G9        A/C#           C D',
  'Maria, ser Cristo ao mundo novo.',
  '    E         G9',
  'Tua força, Rainha,',
  '     A/C#       C D',
  'a serviço desse fogo.',
  '   E',
  'Ao Teu lado, Mãe,',
  '      G9               A/C#',
  'por Schoenstatt e pela Igreja',
  '       C D',
  'me dou todo.',
  ' ',
  ' G                D        C',
  'FIAT, faça-se em nós esta chama,',
  '     D E',
  'este amor.',
  '  G                   D',
  'Guia-nos pelo nosso ideal:',
  '             C',
  'ser Cristo Tabor.',
  ' G              D',
  'FIAT, faça-se em nós',
  '     C           D  E',
  'juventude em missão.',
  '  G              D        C',
  'Fica formada uma nova Geração.',
  ' ',
  'Em D G A9 E D A9 B E'
];

export const Fidelidad = [
  //_________________________________
  '       C       G',
  'Pensar que Cristo',
  '      Am    F',
  'murió por nosotros',
  '     C           G',
  'Ofreciendo su vida,',
  '   Am        F',
  'su libertad',
  'C         G',
  'Es un regalo que',
  '       Am  F',
  'nos hace pensar',
  '         Am      G   F',
  'En que todos debemos estar',
  ' Am             G           F',
  'Unidos en un mismo cantar.',
  ' ',
  'Aquella cruz donde Cristo murió',
  'María en su espada, la transformó',
  'Una espada teñida de heroísmo y verdad',
  'Una espada de entrega y de paz',
  'Una espada de fidelidad.',
  ' ',
  '       Am             G',
  'Se esconde un misterio',
  '         F        G',
  'detrás de tu ser',
  '    Am              G',
  'Una luz que nos guía',
  '           F        G',
  'a la cruz de Jesús',
  '      Am          G',
  'Una espada que rompe',
  '          F  G',
  'el camino de mal',
  '         F',
  'Y que acoge',
  '                     G',
  'a los faltos de paz,',
  '        F',
  'Y que acoge',
  '          G         C  G',
  'a los faltos de paz.',
  ' ',
  'Refrão:',
  ' C      G   F      G  C  G',
  'Fidelidad a tu espada jurar',
  'F       G C',
  'Y con fe a tu',
  '  G/B       Am Am/G',
  'Hijo entregar',
  'F',
  'Una respuesta,',
  ' Dm            G',
  'que sea del corazón',
  'C       G  F',
  'Fidelidad a tu',
  '      G       C G',
  'bandera jurar',
  'F       G',
  'Y con fe en tus',
  '   C G/B    Am Am/G',
  'brazos gritar',
  'F                            G',
  'Que eres mi Madre y mi luz,',
  'F',
  'Que eres mi espada y mi cruz.',
  ' ',
  '     C  G',
  'Confiemos en Ella',
  ' Am            F',
  'y no en nuestro plan',
  '   C             G',
  'Dejemos que actúe',
  '   Am       F',
  'su voluntad',
  '           C G',
  'Que su espada de paz',
  '  Am           F',
  'atraviese este mar',
  '     Am        G           F',
  'Corazones deseosos de amar',
  '           Am',
  'Nuestras almas',
  '        G         F',
  'dispuestas a dar.',
  ' ',
  '       Am         G',
  'Dar nuestra misión,',
  '          F       G',
  'dar nuestro ideal',
  '         Am    G',
  'Nuestra vida nuestro',
  '        F           G',
  'querer nuestro ser',
  'Am        G      F          G',
  'Para al fin poder encontrar',
  '         F                    G',
  'Lo que nos hace amar y creer',
  '         F         G',
  'Lo que nos hace amar',
  '          C G',
  'y creer'
];

export const FielAMissaoVem = [
  //_________________________________
  'Refrão:',
  '  Em',
  'Fiel a missão, vem (2x)',
  ' Am            Em',
  'Vem, vem e anuncia! (2x)',
  '       B7      Em',
  'Tua missão é Maria! (2x)',
  ' ',
  '   D                   Em',
  'Os homens nos caminhos seus,',
  '    B7                 Em',
  'se escondem e fogem de Deus.',
  '    D              Em',
  'Mas tens uma nova visão:',
  ' B7              Em  B7',
  'Aliança e vinculação.',
  ' ',
  'Maria, modelo encarnado,do homem por Deus Pai sonhado.',
  'É luz, é grande visão, ao mundo na escuridão.',
  ' ',
  'Refrão:',
  '  Em',
  'Fiel a missão, vem (2x)',
  ' Am            Em',
  'Vem, vem e anuncia! (2x)',
  '       B7      Em',
  'Tua missão é Maria! (2x)',
  ' ',
  '   D                   Em',
  'Os homens nos caminhos seus,',
  '    B7                 Em',
  'se escondem e fogem de Deus.',
  '    D              Em',
  'Mas tens uma nova visão:',
  ' B7              Em  B7',
  'Aliança e vinculação.',
  ' ',
  'Tu tens um Pai educador, que educa na força do amor.',
  'Apóstolo de ti fará, mas tem que deixar-te educar.',
  ' ',
  'Refrão:',
  '  Em',
  'Fiel a missão, vem (2x)',
  ' Am            Em',
  'Vem, vem e anuncia! (2x)',
  '       B7      Em',
  'Tua missão é Maria! (2x)',
  ' ',
  '   D                   Em',
  'Os homens nos caminhos seus,',
  '    B7                 Em',
  'se escondem e fogem de Deus.',
  '    D              Em',
  'Mas tens uma nova visão:',
  ' B7              Em  B7',
  'Aliança e vinculação.',
  ' ',
  'Assume com fé teu lugar, e tua missão de anunciar.',
  'O mundo de hoje precisa, profetas que o sejam na vida.',
  ' ',
  'Refrão:',
  '  Em',
  'Fiel a missão, vem (2x)',
  ' Am            Em',
  'Vem, vem e anuncia! (2x)',
  '       B7      Em',
  'Tua missão é Maria! (2x)',
  ' ',
  '   D                   Em',
  'Os homens nos caminhos seus,',
  '    B7                 Em',
  'se escondem e fogem de Deus.',
  '    D              Em',
  'Mas tens uma nova visão:',
  ' B7              Em  B7',
  'Aliança e vinculação.',
  ' ',
  'A Aliança fiel dia-a-dia, teu grande mistério anuncia.',
  'Mistério que o Pai viveu, e aos filhos como herança deu',
  ' ',
  'Refrão:',
  '  Em',
  'Fiel a missão, vem (2x)',
  ' Am            Em',
  'Vem, vem e anuncia! (2x)',
  '       B7      Em',
  'Tua missão é Maria! (2x)',
  ' ',
  '   D                   Em',
  'Os homens nos caminhos seus,',
  '    B7                 Em',
  'se escondem e fogem de Deus.',
  '    D              Em',
  'Mas tens uma nova visão:',
  ' B7              Em  B7',
  'Aliança e vinculação.'
];

export const FilhoDeSchoenstatt = [
  //_________________________________
  '  A',
  'Quero meu bom Pai,',
  '      C#m',
  'ser exemplo, ser resposta',
  '       D            Bm',
  'pro vazio e a insegurança',
  '    E',
  'daqueles que estão longe de Ti.',
  ' A',
  'Com Teu grande amor,',
  '      C#m',
  'transforma o meu ser,',
  '        D          Bm',
  'o meu agir seja autêntico,',
  ' E    E7     A    D E',
  'Faça-me crescer.',
  ' ',
  'Refrão:',
  '  A          C#m          D',
  'Nessa grande união com o Filho,',
  'E       D           A',
  'tenho somente um pedido:',
  'C#m          D',
  'Ser um verdadeiro,',
  '    E     D         A      C#m D E (E7)',
  'um nobre Filho de Schoenstatt.',
  ' ',
  'Grandes são as metas, elevados ideais',
  'por isso dá-me confiança nas lutas que enfrentarei.',
  'Faça-se pequeno filho, uma singela criança',
  'que possa dizer com segurança: Abba! Querido Pai”',
  ' ',
  'Refrão:',
  '  A          C#m          D',
  'Nessa grande união com o Filho,',
  'E       D           A',
  'tenho somente um pedido:',
  'C#m          D',
  'Ser um verdadeiro,',
  '    E     D         A      C#m D E (E7)',
  'um nobre Filho de Schoenstatt.',
  ' ',
  'Quero aceitar a cruz, quero viver em Unidade',
  'com minha querida Mãe Maria e com o seu Filho Jesus.',
  'Por vezes Te esqueci, senti meu coração culpado,',
  'mas pelo sangue perdoado quero de novo consagrá-lo a Ti.',
  ' ',
  'Refrão:',
  '  A          C#m          D',
  'Nessa grande união com o Filho,',
  'E       D           A',
  'tenho somente um pedido:',
  'C#m          D',
  'Ser um verdadeiro,',
  '    E     D         A      C#m D E (E7)',
  'um nobre Filho de Schoenstatt.',
  ' ',
  'Na Aliança de Amor, eleva-me sempre ao mais alto,',
  'faça-se aceitar Tua vontade, viver em fidelidade.',
  'Peço meu bom Deus viver como o Fundador',
  'E perceber a porta que me abres. Confiar, viver e ser Tabor.',
  ' ',
  'Refrão:',
  '  A          C#m          D',
  'Nessa grande união com o Filho,',
  'E       D           A',
  'tenho somente um pedido:',
  'C#m          D',
  'Ser um verdadeiro,',
  '    E     D         A      C#m D E (E7)',
  'um nobre Filho de Schoenstatt.'
];

export const FuegoDeSuFuego = [
  //_________________________________
  ' D                        A',
  'Fuego que las brasas retuvieron',
  '                    Bm',
  'Por decenios del silencio',
  ' G                       Bm',
  'Hasta que el soplo del espíritu',
  '                 Em     D',
  'Te alzó en uvas rojas',
  '   G                      Bm',
  'Profeta en la más oscura noche',
  '   G                    D F#7 Bm',
  'Profeta en el cruce de ca-minos',
  '      G      A       D',
  'Eres luz reflejo del sol',
  ' ',
  ' D    A     D  Bm      F#7    Bm',
  'Fuego de su fuego, alma de su alma',
  '     G       A     F#7        Bm',
  'Eres grito y voz en la tempestad',
  '     G              A        D',
  'Eres fuego que nos lleva al sol',
  ' ',
  'Fuego que se oculta pero brilla',
  'En el rincón de la lágrima',
  'Fuego de incansables caminantes',
  'Que hace días las tinieblas',
  'Fuego, que nos llega hasta el alma',
  'En la sangre de aquellos que te aceptan',
  '¡Y nos urge al mundo encender!'
];

export const Herencia = [
  //_________________________________
  'Intro. F9 C/E G (2X)',
  ' ',
  'F9             C/E',
  ' Saliste a pelear con la',
  ' G',
  'noche en los ojos,',
  'y en tus cristales',
  'todo el fuego de la guerra.',
  'Dm        Em         F           G',
  ' Tanto dolor y tanta desesperación,',
  'Dm         Em             F',
  ' hoy hacen falta aquellos héroes',
  '          G             F9  C/E G',
  'que aun temiendo digan “Voy!”',
  ' ',
  'Mirando el horizonte vuelves al santuario,',
  'Y puedes abrazar allí a tus hermanos,',
  'y en la distancia el Padre bendice tu valor,',
  'nunca estás solo congregante,',
  'María vive en tu corazón.',
  ' ',
  'Refrão:',
  'Am   G   F       C G/B Am',
  ' José yo voy con vos,',
  '    G   F        E        Am',
  'nos une tanto la misma pasión.',
  'José siempre serás',
  'una luz que renueva el sentido de luchar',
  'Am        G          D',
  'Y así volver a intentar',
  '  Am      G          D',
  'nuestra mayor libertad,',
  '     Dm7        G    F9 C/E G',
  'libertad, libertad',
  '(Final: libertad, para amar)',
  ' ',
  'Corres como un niño que acaba de confiarse,',
  'y en secreto ríes como los audaces.',
  'Pero de repente el mundo desapareció.',
  'Abres los ojos, es tu Madre',
  'que te sonríe y te lleva a Dios.'
];

export const HeroisDeFogo = [
  //_________________________________
  'Intro: E A9',
  ' ',
  'E',
  'Inflama a chama,',
  '  A9',
  'esquenta a minh´alma',
  'C#m             A9',
  'Ilumina o meu ser',
  'E                     A9',
  'Transforma em flama a fleuma da calma',
  'C#m          A9  E A9 E A9',
  'Sofro novo nascer',
  ' ',
  'E                 A9',
  'E lento, arde, aumenta e a alastra',
  'C#m         A9',
  'Toma a direção',
  'E                    A9',
  'O vento sopra e a vontade se afasta',
  'C#m              A9',
  'Teu é o meu coração',
  ' ',
  'F#m      A9        B9',
  ' Santo ardor sinto no teu olhar',
  'A9     F#m       B9',
  'A congregados tornar',
  ' ',
  'Refrão:',
  'E                    A9',
  'Heróis de fogo que hoje batalham',
  'E        A9         C#m      A9',
  'Por tua Aliança, perfeita união',
  'E                 A9',
  'Ao horizonte, Maria, hoje marcham',
  'F#m      A9      B9',
  'Em plena vinculação',
  'E                   A9',
  'Heróis de fogo deixaram-se arder',
  'E    A9             C#m      A9',
  'A consumir-se, entregaram o Amor',
  'E                     A9',
  'Heróis de fogo, na Pira hoje ardem',
  '  F#m      A9      B9',
  'O Fogo do Cristo Tabor',
  '  A9       B9       E  A9 E',
  'O Fogo do Cristo Tabor'
];

export const HinoDeFranzReinish = [
  //_________________________________
  'Em          D        Em',
  'Tú eres el signo grandioso',
  'G       D      G',
  'lleno de luz y de sol',
  '                   Am   C',
  'todo encendido e inundado',
  '       D    Em',
  'por el amor de Dios.',
  'G            D',
  'María Virgen pura,',
  'Em             B',
  ' enciende todo mi ser',
  'C      D      G D Em',
  'en tu pequeño Santuario',
  'Am       B7        Em',
  ' como una llama de amor.',
  ' ',
  'Em       D         Em',
  'Como una rosa doliente',
  '   G      D       G',
  'silente junto a la cruz',
  '                   Am',
  'dices tu Sí al sacrificio',
  ' C        D    Em',
  'pues Dios lo quiere de ti.',
  'G                     D',
  'También hoy llama el Padre',
  'Em              B',
  'héroes para la misión',
  'C       D     G D Em',
  'aquí me tienes  Madre',
  'Am       B7       Em',
  'como una ofrenda de amor.',
  ' ',
  'Em         D        Em',
  'Reina de todos los mundos',
  'G     D      G',
  'vences la tempestad',
  '                      Am',
  'mata el engendro del diablo',
  'C       D      Em',
  'Tú vencedora real',
  ' ',
  'Refrão:',
  '   G                     D',
  '/: Hazme un apóstol de Schoenstatt',
  'Em              B',
  'cual caballero estaré',
  'C    D     G D Em    Am    B7  Em',
  'y moriré sonriendo querida MTA. :/'
];

export const HinoDaEscolaDeLideresDe1997 = [
  //_________________________________
  ' D             A',
  'Aliados a Maria, com a coroa da missão',
  '      Bm                      G',
  'Ao Brasil se encaminha novos tempos,',
  '          A',
  'nossa missão.',
  'D            A',
  'Um novo Tabor, uma nova comunidade.',
  '     Bm',
  'Para isso aqui estamos,',
  '     G              A',
  'reviver os grandes marcos.',
  ' ',
  'Refrão:',
  'Em       D',
  'Líderes, Homens Novos,',
  'C                           Em',
  'a vida é o nosso campo de batalha.',
  'Em      D',
  'Filiais e Heroicos,',
  'C              G      A  D',
  ' 31 de maio, Jovem Tabor.',
  ' ',
  'Aliados a Maria,',
  'marcharemos, lutaremos',
  'Vivendo em harmonia,',
  'santidade no dia-a-dia.',
  'Com o fogo da missão,',
  'consciente, confiantes,',
  'O Brasil incendiaremos,',
  'hoje não amanhã.'
];

export const HinoDosPioneiros = [
  //_________________________________
  '           A',
  'Somos Pioneiros',
  '   D            A',
  'abrindo novas trilhas,',
  '         D',
  'abrindo juntos',
  '                    E',
  'o caminho ao Mundo Novo.',
  '          A',
  'Vamos lutando,',
  '    D            A',
  'saltando mil perigos,',
  '          D',
  'somos vanguarda',
  '             E',
  'da nova juventude.',
  '           D      E',
  'São nossas mãos alegres,',
  '   A              D',
  'criadoras, de iniciativas',
  '                 E',
  'transborda o coração.',
  ' ',
  'Refrão:',
  '            D',
  'Pioneiro irmão,',
  '     E                 A',
  'foi Deus quem te escolheu,',
  '           D',
  'seguindo o Pai',
  '                E',
  'abrirás novo caminho',
  '       D         E',
  'Ama Maria que a tua',
  '           A F#m',
  'entrega espera,',
  '          D       E        A D A',
  'ser responsável pelos que virão.',
  ' ',
  'Somos pioneiros com Cristo aqui na Terra,',
  'nos deu exemplo e abriu novo caminho.',
  'Cristo seguimos, Maria é nossa guia,',
  'pois é sua Mãe e nossa Mãe também,',
  'Cristo Pioneiro a ama intensamente,',
  'e nós também com todo o coração.',
  ' ',
  'Somos Pioneiros alegres, decididos,',
  'com nossos passos fazemos nossa história.',
  'No Santuário surge o Homem Novo,',
  'pois somos líderes dispostos a servir.',
  'Vamos lutando por nossos ideais,',
  'seguindo ao Pai que nos dá a missão.'
];

export const JeitoDeSer = [
  //_________________________________
  'D',
  'Não são os grandes planos',
  ' A',
  'que dão certo,',
  'Bm                 F#m',
  'são os pequenos detalhes',
  'que fazem.',
  'G                      Em',
  'Enquanto os perdedores se justificam',
  '       A',
  'o vencedores comemoram.',
  ' ',
  'Refrão:',
  'C                    G',
  'Ser líder não e ter uma função,',
  '         D',
  'senão um jeito de ser. (2x)',
  ' ',
  'Em           D',
  'Ser líderes, Homens Novos,',
  'C',
  ' e construir uma nova sociedade.'
];
