export const MariaMadre = [
  //_________________________________
  'E        F#m*',
  'Hoy madre,',
  '             E  F#m*',
  'vengo a ofrecerme',
  'E          Eb5b/7   G#m7',
  'Quiero ser un instrumento',
  'C#m7',
  ' de tu Paz,',
  'A7+        B/A   G#m7 C#m7',
  'Guíame en este caminar,',
  'F#7     F#m7    B7/4 B7',
  'Ayúdame a serte fiel.',
  ' E       F#m*',
  'Hoy madre,',
  '             E   F#m*',
  'yo quiero seguirte',
  'E             Eb5b/7 G#m7   C#m7',
  'Quiero estar en ti por siempre,',
  'A7+         B/A',
  'Llévame de la mano,',
  '    A7+            B7  D7',
  'A tu lado hasta el final.',
  ' ',
  'Refrão:',
  '   G           C9',
  'María, yo me entrego a ti,',
  'G          C9',
  'Tómame por siempre,',
  'G                 C9',
  'Todos los miedos humanos',
  '       D',
  'de un lado dejaré,',
  '   Am/F#         B7',
  'Hoy sólo importas Tú,',
  '        Em        A7',
  'pues en ti encontré,',
  '     Am7    Bm7',
  'Encontré lo que',
  '   C7+ C#o D9sus4',
  'buscaba,',
  'Am7      C9      D  G',
  'Nunca me dejes, te amo.',
  ' E       F#m*',
  'Hoy madre listo estoy,',
  '   E        F#m*',
  'La historia comienza,',
  'E         Eb5b/7  G#m7  C#m7',
  'Y sólo pido permanezcas aquí,',
  '     Bm7          E',
  'Y la meta alcanzaré,',
  '       A7+',
  'Para la Gloria de tu amor,',
  'Am7   D7 G',
  ' ayúdame.',
  ' ',
  'F#m* 044200',
  'D9sus4 x55555',
  'Eb5b/7 x67670',
  'C#o x45353'
];

export const MarchaDelBuenViaje = [
  //_________________________________
  'D        F#       Bm',
  'Estamos vivos y vivimos,',
  'G            E         A',
  ' amarte es nuestro destino',
  'D            F#        Bm',
  'Aunque este viaje es distinto,',
  'G             E      A',
  ' sólo hay un solo camino,',
  '          D   F#',
  'Llegar a vos la,',
  '    Bm   G E A',
  'la, la...',
  'D       F#        Bm',
  'Sólo quedó hierba seca',
  'G         E         A',
  'por donde antes pisamos,',
  'D         F#      Bm    G',
  'Hoy hay flores de pureza,',
  '            E        A',
  'pues hacia ti caminamos,',
  '       D   F#',
  'Espéranos la,',
  '    Bm   G E A',
  'la, la...',
  ' ',
  'Refrão:',
  'D  F#    Bm      G  E    A',
  'Dulce Doncella, te seguiré',
  'D  F#      Bm     G     E    A',
  'Eres mi estrella, te alcanzaré',
  '           D',
  'Yo sé que sí,',
  'F#      Bm   G E A',
  'la, la, la...',
  ' ',
  'D        F#       Bm',
  'Por la ruta de mis días,',
  'G           E       A',
  ' el viaje fue muy pesado',
  'D            F#        Bm',
  'Hasta que hallé una doncella,',
  'G          E      A',
  ' y así juntos caminamos',
  '          D',
  'Para llegar,',
  'F#      Bm   G E A',
  'la, la, la...',
  'D        F#          Bm',
  'Me demostró que en la vida',
  'G         E       A',
  ' el amor es necesario,',
  'D              F#       Bm',
  'El que hasta ayer se evadía',
  'G            E          A',
  'Al fin al puente ha llegado,',
  '         D',
  'Lo cruzará,',
  'F#      Bm   G E A',
  'la, la, la...',
  ' ',
  'Refrão:',
  'D  F#    Bm      G  E    A',
  'Dulce Doncella, te seguiré',
  'D  F#      Bm     G     E    A',
  'Eres mi estrella, te alcanzaré',
  '           D',
  'Yo sé que sí,',
  'F#      Bm   G E A',
  'la, la, la...'
];

export const NuestraAlianza = [
  //_________________________________
  'A9      A9/C#',
  'Tu manto es el sol',
  '      D9         D9/F#',
  'que abraza mis heridas',
  'A9          A9/C#',
  'Madre de esperanza',
  '        D9    D9/F#',
  'estoy aquí',
  'E           D9',
  'Porque bajo tu mirada',
  'G          D9',
  'llena de amor',
  '        A9           E/A',
  'Se me abierto tan profundo',
  '        D9',
  'el corazón',
  ' ',
  'Refrão:',
  '        A9    E/A            D9',
  'Junto a mi vivirás mi instrumento',
  '        D9',
  'Y en su nombre',
  'A#dim           Bm   A E',
  'prenderemos de fuego',
  '        A           E',
  'Triunfará nustra alianza',
  '      F#m        E     D9',
  'donde exista la separación',
  '          G       D9',
  'Te he elegido libremente',
  '   E              A9',
  'y no te dejare jamás',
  ' ',
  'A9      A9/C#',
  'No pongo más resistencia',
  'D9             D9/F#',
  'para dejarte forjar',
  'A9            A9/C#',
  'Lo que sueñas como madre',
  '   D9   D9/F#',
  'en mi',
  ' E                  D9',
  'Hoy te agradezco tomar',
  '   G           D9',
  'a esta mi pequeñes',
  '         A9',
  'Para llevarte en las',
  'E/A         D9  E',
  'manos mi bandera',
  ' ',
  'Refrão:',
  '        A9    E/A            D9',
  'Junto a mi vivirás mi instrumento',
  '        D9',
  'Y en su nombre',
  'A#dim           Bm   A E',
  'prenderemos de fuego',
  '        A           E',
  'Triunfará nustra alianza',
  '      F#m        E     D9',
  'donde exista la separación',
  '          G       D9',
  'Te he elegido libremente',
  '   E              A9',
  'y no te dejare jamás'
];

export const PerfeitoEQuemTeCriou = [
  //_________________________________
  ' E',
  'Se um dia um anjo declarou',
  '     F#m',
  'que tu eras cheia de Deus.',
  ' G#m                 C#m',
  'Agora penso: quem sou eu',
  '          F#m      B7',
  'para não te dizer também',
  '         E        C#m',
  'Cheia de graça, ó mãe?',
  '          F#m',
  'Cheia de graça,',
  'B7      E',
  'ó mãe, agraciada.',
  ' ',
  'Se a Palavra ensinou',
  'que todos hão de concordar,',
  'e as gerações te proclamar,',
  'agora eu também direi:',
  'Tu és bendita, ó mãe.',
  'Tu és bendita, ó mãe, bem-aventurada.',
  ' ',
  '    C                G',
  'Surgiu um grande sinal do céu,',
  '  Am             Em',
  'uma mulher revestida de sol.',
  '  C           G',
  'A lua debaixo de seus pés',
  '  A           B7',
  'e na cabeça uma coroa...',
  ' ',
  'Não há como se comparar',
  'Perfeito é quem te criou',
  'Se o Criador te coroou',
  'Te coroamos, ó mãe',
  'Te coroamos, ó mãe',
  'Te coroamos, ó mãe, nossa Rainha'
];

export const QuemEEstaQueAvanca = [
  //_________________________________
  '       E         B',
  'Quem é esta que avança',
  '           C#m',
  'como uma Aurora?',
  '  E           B',
  'Temível como exército',
  '           C#m',
  'em modo de batalha.',
  '    E            B',
  'Brilhante como o Sol,',
  '         C#m',
  'e como a Lua.',
  '    E           B',
  'Mostrando os caminhos',
  '           C#m',
  'aos filhos Teus.',
  ' ',
  'Refrão:',
  '  E         B',
  'Aah, minha alma glorifica',
  '     C#m',
  'ao Senhor.',
  'E       B      C#m',
  ' Meu Espírito exulta',
  'E   B            C#m',
  ' em Deus meu Salvador.'
];

export const ReinaDeLaMission = [
  //_________________________________
  '  F            Bb',
  'Llevo mi mochila al hombro,',
  '  F            Bb',
  'llena de esperanza en vos.',
  ' F          Bb        C',
  'Tengo mi remera de misión',
  ' ',
  ' F             Bb',
  'Quiero llevar mi sonrisa,',
  '  F              Bb',
  'Signo de que estas en mí.',
  ' F            Bb          C',
  'Yo soy instrumento de tu amor.',
  ' ',
  '  G              C',
  'Tengo alma en movimiento,',
  '  G           C',
  'con la sencillez de Cristo.',
  '   G        C             D',
  'Quiero regalarte una canción.',
  ' ',
  ' G          C',
  'Cargo a María en mis brazos,',
  '  G           C',
  'listo para misionar.',
  ' G         C        D',
  'Vamos, es hora de caminar.',
  ' ',
  ' C         G',
  'Juntos queremos',
  '         Am            G',
  'ser instrumentos de María.',
  'C            G          D',
  'Y llevar con Ella La alegría.',
  ' ',
  'Refrão:',
  '     C  G       Am  D    G',
  'Es María, Reina de la Misión.',
  '    C  G          Am  D        G',
  'A María, la llevo en el Corazón.',
  ' ',
  '  G         C',
  'Como Juventud de Schoenstatt,',
  ' G               C',
  'Juntos en nuestro santuario.',
  'G          C          D',
  'Al mundo iremos a cambiar.',
  ' ',
  '   G              C',
  'Sigamos siendo luz de Cristo,',
  'G           C',
  'Para iluminar lo oscuro.',
  '   G        C         D',
  'Quiero ser niño de verdad.'
];

export const HastaQueElMundoArdaPorEl = [
  //_________________________________
  'Intro. G7+/B G/B C9 Bm11 D9/F#',
  ' ',
  'Bm  C  G        D/F#',
  'María, toma todo lo',
  '             Em C',
  'que tengo y soy,',
  '           G     D',
  'te ofrezco mi corazón,',
  'Bm C        G',
  'como aquel niño que hoy',
  '   D/F#       Em  C',
  'se acerca ante ti',
  '           G        D',
  'y te habla de su canción.',
  ' Bm    C       G         D/F#',
  'Gota a gota mi sangre te entrego,',
  'Em    C     G   D      C9',
  'día a día vivir su misión.',
  ' ',
  'Refrão:',
  'Em           C',
  ' Hazme una antorcha',
  '    D         G    D/F#',
  'que arda por Cristo,',
  'Em         C      G        D/F#',
  ' incendiar el corazón, ser hogar',
  'B7                Em  D     C9',
  'como el sol que esparce tu luz',
  'Am           G',
  'hasta que el mundo',
  '         F  G',
  'arda por Él,',
  'Am           G              C9',
  'hasta que el mundo arda por Él.',
  ' ',
  'D#/G            F/A',
  'María, quiero soñar,',
  'Dm       Gm   F     Eb',
  'nuevos caminos comenzar,',
  '           D7',
  'quiero ser santo y,',
  '  Gm  F   C',
  'si debo morir,',
  'D#/G     F/A         G',
  ' mi vida quiero entregar.',
  '(C9 G/B 3x D/F#)',
  ' ',
  'G7+/B   x 2 0 0 3 2',
  'Bm11    x 2 0 2 3 0',
  'G/B     x 2 0 0 3 3',
  'D9/F#   2 x 0 2 3 0',
  ' ',
  'Refrão:',
  'Em           C',
  ' Hazme una antorcha',
  '    D         G    D/F#',
  'que arda por Cristo,',
  'Em         C      G        D/F#',
  ' incendiar el corazón, ser hogar',
  'B7                Em  D     C9',
  'como el sol que esparce tu luz',
  'Am           G',
  'hasta que el mundo',
  '         F  G',
  'arda por Él,',
  'Am           G              C9',
  'hasta que el mundo arda por Él.'
];

export const VemMariaVem = [
  //_________________________________
  'Refrão:',
  ' Am             G',
  'Vem Maria vem! Vem nos ajudar',
  'F                    E7',
  'nesse caminhar tão difícil',
  '       Am',
  'rumo ao Pai (2X)',
  ' ',
  ' Am                   Dm',
  'Vem querida mãe nos ensinar.',
  'G                     C',
  'A ser testemunha do amor',
  '     F                     Dm',
  'Que fez do seu corpo sua morada.',
  '         E7                     Am',
  'Que se abriu pra receber o Salvador',
  ' ',
  'Refrão:',
  ' Am             G',
  'Vem Maria vem! Vem nos ajudar',
  'F                    E7',
  'nesse caminhar tão difícil',
  '       Am',
  'rumo ao Pai (2X)',
  ' ',
  'Am                       Dm',
  'Nós queremos ó mãe responder,',
  ' G                     C',
  'Ao amor do Cristo Salvador.',
  ' F                    Dm',
  'Cheios de ternura colocamos,',
  '     E7',
  'Confiantes em suas mãos',
  '         Am',
  'esta oração.',
  'Refrão:',
  ' Am             G',
  'Vem Maria vem! Vem nos ajudar',
  'F                    E7',
  'nesse caminhar tão difícil',
  '       Am',
  'rumo ao Pai (2X)'
];

export const AlegriaDoSenhorEANossaForca = [
  //________________________________
  'Refrão:',
  'F               Dm          Bb  C',
  'A alegria do Senhor é nossa força.',
  'Gm               D              C',
  'A alegria do Senhor é nossa força.',
  'Am               D',
  'A alegria do Senhor',
  '        Bb      C',
  'é nossa força.',
  '      Am    Dm',
  'Nossa força,',
  '        Bb  C',
  'nossa força',
  '        F',
  'é o Senhor Jesus',
  ' ',
  '    Am           Dm',
  'Ele é a nossa razão de',
  '  Am             Dm',
  'lutarmos até o final',
  'Bb    C  F               C',
  'Sim, Ele é a luz que chegou',
  '     Gm   F  Bb          C',
  'e as trevas não puderam resistir.',
  '         D     Gm   F  Bb       C',
  'Ele é o sol! Nossa canção reluzirá,',
  '            F',
  'resplandecerá!',
  'F        C    F      Bb      C',
  'A nossa força é o Senhor Jesus. (4x)'
];

export const AAlegriaEstaNoCoracao = [
  //_________________________________
  'A',
  'A alegria está no coração',
  '     D                  A   G D',
  'de quem já conhece a Jesus.',
  'AlmaDeCristo',
  'A verdadeira paz só tem aquele',
  '    D               E',
  'que já conhece a Jesus.',
  'A                 A7',
  'O sentimento mais precioso',
  '     D               E',
  'que vem do nosso Senhor',
  '      A D        E',
  'É o amor que só tem quem',
  '                A   E',
  'já conhece a Jesus',
  ' ',
  '         A',
  'Posso pisar numa tropa',
  'e saltar as muralhas.',
  '      D       Dm',
  'Aleluia! Aleluia!',
  '         A',
  'Posso pisar numa tropa',
  'e saltar as muralhas.',
  '      D       E',
  'Aleluia! Aleluia!',
  ' ',
  'A',
  'Ele é a rocha da minha salvação,',
  '     D               Dm',
  'com Ele não há mais condenação',
  '         A',
  'Posso pisar numa tropa',
  'e saltar as muralhas.',
  '      D       Dm',
  'Aleluia! Aleluia!',
  '    A         D Dm',
  'Aleluia! Aleluia!',
  '    A        D  E',
  'Aleluia! Aleluia!',
  'A                 A7',
  'O sentimento mais precioso',
  '     D                E',
  'que vem do nosso Senhor',
  '      A D        E',
  'É o amor que só tem quem',
  '                A',
  'já conhece a Jesus'
];

export const AlmaMissionaria = [
  //_________________________________
  '   G                   Em',
  'Senhor, toma esta vida jovem,',
  'C               G',
  ' antes que a espera desgaste',
  '       D',
  'anos em mim',
  '   G                     Em',
  'Estou disposto ao que quiseres,',
  'C                    G',
  ' não importa o que seja,',
  'D                 G D',
  ' chama-me a servir.',
  ' ',
  'Refrão:',
  '       G           D',
  'Leva-me aonde os homens',
  '      Em           C',
  'necessitam tuas palavras,',
  '     G                   D',
  'necessitam anseios de viver.',
  '       G          D',
  'Onde falta a esperança,',
  '     Em         C',
  'onde tudo seja triste',
  '       G    D',
  'simplesmente por não saber',
  '   G  D',
  'de ti.',
  ' ',
  'Eu dou meu coração sincero,',
  'para gritar sem medo que belo é teu amor.',
  'Senhor, tenho alma missionária,',
  'conduz-me a terra, com sede de Ti.',
  ' ',
  ' ',
  'Refrão:',
  '       G           D',
  'Leva-me aonde os homens',
  '      Em           C',
  'necessitam tuas palavras,',
  '     G                   D',
  'necessitam anseios de viver.',
  '       G          D',
  'Onde falta a esperança,',
  '     Em         C',
  'onde tudo seja triste',
  '       G    D',
  'simplesmente por não saber',
  '   G  D',
  'de ti.',
  'E assim em marcha, irei cantando,',
  'pelos povos pregando, tua grandeza, Senhor.',
  'Terei minhas mãos entre as Tuas,',
  'meus olhos em teus olhos e a força da oração.',
  ' ',
  'Refrão:',
  '       G           D',
  'Leva-me aonde os homens',
  '      Em           C',
  'necessitam tuas palavras,',
  '     G                   D',
  'necessitam anseios de viver.',
  '       G          D',
  'Onde falta a esperança,',
  '     Em         C',
  'onde tudo seja triste',
  '       G    D',
  'simplesmente por não saber',
  '   G  D'
];

export const AveImperatrix = [
  //_________________________________
  'Intro. Em Am G B7 (4x)',
  ' ',
  'Em    Am    G      B7   Em',
  ' Escuche hablar de un lugar',
  '     Am           G        B7   Em',
  'un refugio de infinita tranquilidad',
  '   Am      G         B7   Em',
  'un reino repleto de santidad',
  '      Am          G',
  'con soldados que nunca',
  '  B7   Em Am G B7',
  'perecerán',
  ' ',
  'Escuche hablar de una reina',
  'su mirada corazones sembrara',
  'su legión no muere sin pelear',
  'como águilas los cielos surcaran',
  ' ',
  'Refrão:',
  'E  G#m       B C#m E',
  ' Saluda a tu reina',
  '    G#m         B E',
  'con ansias te espera',
  'corona tu corazón con actos de amor',
  ' ',
  'Moriremos por tu noble causa',
  'tu santuario será nuestra morada',
  'por tu corona saldremos a pelear',
  'y con tu luz la noche cambiara',
  ' ',
  'Y los tambores de guerra latirán',
  'este mundo tu veras cambiar',
  'tu hijo nos llenara de paz',
  'y feliz en buenos aires triunfaras',
  ' ',
  'Refrão:',
  'Corona a tu reina',
  'sus brazos te esperan',
  'contempla sus ojos',
  'sin penas ni odio',
  ' ',
  'Refrão:',
  'E  G#m       B C#m E',
  ' Saluda a tu reina',
  '    G#m         B E',
  'con ansias te espera',
  'corona tu corazón con actos de amor',
  ' ',
  'La argentina será renovada',
  'vale la pena morir en tu batalla',
  'con esperanza construiremos un lugar',
  'refugio de infinita felicidad',
];

export const AViagem = [
  //_________________________________
  'D         A',
  'Eu vim de longe',
  '                     D',
  'pra encontra o meu caminho',
  '         A',
  'tinha um sorriso',
  '                     D',
  'e o sorriso ainda valia,',
  '         G                  D',
  'achei difícil a viagem até aqui',
  '              A',
  'mais eu cheguei,',
  'A7            D G D',
  ' mais eu cheguei.',
  ' ',
  'Eu vim depressa e não vim de caminhão.',
  'Eu vim a jato no asfalto, neste chão.',
  'Achei difícil a viagem até aqui,',
  'mas eu cheguei, mas eu cheguei.',
  ' ',
  'Eu tive ajuda de quem você não acredita,',
  'tive a esperança de chegar até aqui.',
  'Vim caminhando aqui estou'
];

export const ChuvaDeGraca = [
  //_________________________________
  'E                B',
  'Há uma chuva de graça aqui,',
  'C#m                 A',
  ' está chovendo sobre todos nós,',
  'E                     B',
  'e quem mais se entregar',
  '            C#m  A',
  'mais se molhará.',
  'E              B          C#m',
  'Há uma semente pra germinar,',
  '                  A',
  'e muitos frutos a se produzir,',
  'E               B',
  'na terra do coração,',
  '              A  B7',
  'derrama tua graça.',
  ' ',
  'Refrão:',
  '           E              B',
  'Chuva de graça, pedimos a Ti.',
  '         C#m                A',
  'Chuva de graça, derrama em nós.',
  '           E           B',
  'Chuva de graça nesse lugar,',
  '  A  B7',
  'derrama.'
];

export const DerramaOTeuAmorAqui = [
  //_________________________________
  'G                  D     Em',
  'Senhor, eu quero obedecer',
  '       C',
  'a Tua voz',
  'G                D    Em',
  'Derrama o Teu espírito',
  '             C',
  'sobre todos nós',
  'G                 D       Em',
  'Senhor, eu quero mergulhar',
  '           C',
  'e comprometer',
  'G                D Em',
  'Entrar na intimidade do Teu coração.',
  'C            D',
  ' Derrama em nós Tua unção.',
  ' ',
  'Refrão:',
  'G                     D',
  'Derrama o Teu amor aqui,',
  '                    Em',
  'derrama o Teu amor aqui.',
  '                  C        D',
  'Faz chover sobre nós água viva!',
  'Em                      D',
  'Derrama o Teu amor aqui,',
  '                       C',
  'derrama o Teu amor aqui.',
  '                  D',
  'Faz chover sobre nós água viva!',
  ' ',
  'Em             D    Em',
  'Uma Igreja renovada,',
  '                D',
  'povo santo reunido',
  'Em              D   Em',
  'Famílias restauradas',
  '                     C',
  'pelo poder do Teu Espírito.'
];

export const EntregueSeuCaminhoADeus = [
  //_________________________________
  'G            C',
  'Hoje o mundo oferece',
  '   G            C',
  'caminhos demais',
  'G         C      Bm',
  'Você chora, você ri',
  '        C D     G  C',
  'Nem sempre é feliz.',
  '     G  C G C',
  'É feliz.',
  ' ',
  'G        C           G  C',
  'O mundo não te satisfaz',
  'G            C            Bm',
  'Pois sua alma é grande demais.',
  '    C  D         G    C',
  'Só Deus pode enchê-la.',
  '         G    C G C',
  'Pode enchê-la.',
  '           D',
  'Hoje seus passos',
  'C                 G   C G C ',
  ' se perdem na estrada',
  '     D    C',
  'Nem sempre',
  '             G   C G C',
  'você tem chegada.',
  ' ',
  'Refrão:',
  '    G          C        G   C',
  'Entregue seu caminho a Deus (4x)',
  '       D      C',
  'Laialaiala, ôôô... tiro liro',
  '           G  C  G  C',
  'liro liro lá! (2x)'
];

export const EnviaMe = [
  //_________________________________
  '         E',
  'Fui chamado a missionar,',
  '       C#m',
  'e a levar do teu amor,',
  '         A           F#m',
  'Para um mundo que precisa',
  '         D       B7',
  'reencontrar o Senhor.',
  '     E',
  'Falarei das maravilhas,',
  '      C#m',
  'e das graças que fez em mim,',
  '     A             F#m',
  'Eu irei até os confins do mundo',
  '    D               B7',
  'se for pra falar de Ti.',
  '         C#m           G#m',
  'Vou missionar pra evangelizar.',
  '         C#m               G#m',
  'Vou missionar para transformar,',
  '   A           G#m    F#m',
  'Um mundo que vive nas trevas',
  'E        D              B7',
  ' para um mundo cheio de luz.',
  ' ',
  'Refrão:',
  '                E  A',
  'Quem hei de enviar,',
  '         B7    E     A B7',
  'eis me aqui envia-me.',
  '              C#m  A',
  'Quem hei de enviar,',
  '         B7     E',
  'eis me aqui envia-me.',
  ' ',
  '         E',
  'Somos jovens que queremos',
  '       C#m',
  'ser o rosto do Senhor,',
  '       A      F#m',
  'e com Ele nós iremos outros',
  ' D           B7',
  'jovens resgatar.',
  '   E',
  'É jovem missionando jovem,',
  '       C#m',
  'com alegria de viver,',
  '           A         F#m',
  'quem nos envia em missão é Jesus,',
  '             D            B7',
  'por isso eu digo eis me aqui!'
];

export const EsperandoContraTodaEsperanza = [
  //_________________________________
  ' C      G      F           C',
  'Hoy, al fin tenemos que seguir',
  '             Am        F',
  'caminando en paz, esperando contra toda',
  '         G',
  'esperanza.',
  '  C    G     F            C',
  'y es así que todo va a cambiar',
  '        Am      F',
  'resucitarás esperando',
  '                  G',
  'contra toda esperanza',
  ' ',
  'Refrão:',
  '     F            C',
  'Vos sos la vida, sos la paz,',
  '      G',
  'vos sos nuestra esperanza.',
  '     F         C',
  'Sos el camino para andar,',
  '       G',
  'sos fuerza y sos confianza.',
  ' ',
  '  C     G      F              C',
  'No aflojar, seguirte hasta final,',
  '            Am       F',
  'la Cruz abrazar esperando contra toda',
  '         G',
  'esperanza.',
  'C     G     F               C',
  'Esperar también es transformar,',
  '                 Am       F',
  'un sueno en realidad esperando',
  '                  G',
  'contra toda esperanza',
  ' ',
  ' C    G      F             C',
  'Al saber que Vos vas a volver',
  '      Am        F',
  'a resucitar esperamos',
  '                G',
  'contra toda esperanza',
  'C     G       F             C',
  'Al sentir, Jesús que estas aquí,',
  '         Am       F',
  'esperándonos, esperamos contra toda',
  '         G',
  'esperanza.'
];

export const EuCelebrarei = [
  //_________________________________
  'Em           C',
  'Eu celebrarei cantando ao Senhor',
  'B',
  ' e só nele me alegrarei. (2x)',
  'Em        C',
  'Eu o louvo e adoro',
  'Am               B',
  'porque tens triunfado (2x)',
  ' ',
  'Em',
  'Santo é o Senhor Deus do universo.',
  'D',
  'Santo é o Senhor Deus do universo.',
  'Em',
  'Santo é o Senhor Deus do universo.',
  ' B     Am     B',
  'Porque Santo és!',
  ' ',
  'Refrão:',
  'Em',
  'Ô, ô... Hosana nas alturas.',
  'D',
  'Ô, ô... Hosana nas alturas',
  'Em',
  'Ô, ô... Hosana nas alturas.',
  ' B     Am    B',
  'Porque Santo és!',
  ' ',
  'Em',
  'Bendito és, bendito o que vem.',
  'D',
  'Bendito és, bendito o que vem.',
  'Em',
  'Bendito és, bendito o que vem',
  'B    Am     B',
  'em nome de Deus.',
  ' ',
  'Refrão:',
  'Em',
  'Ô, ô... Hosana nas alturas.',
  'D',
  'Ô, ô... Hosana nas alturas',
  'Em',
  'Ô, ô... Hosana nas alturas.',
  ' B     Am    B',
  'Porque Santo és!',
  ' B     Am    B',
  'Porque Santo és!'
];

export const EuSouDeMaria = [
  //_________________________________
  ' G',
  'Eu sou de Maria,',
  '             Em',
  'Maria nossa Mãe e eu a quero.',
  '                  C',
  'Nos traz o bom Jesus',
  '            Am',
  'que nos protege.',
  '                D',
  'Por isso eu te digo:',
  '                              G',
  'não nos deixe, não nos deixe mais.'
];
