export const ConhecoUmCoracao = [
	//_________________________________
	"   C            Em",
	"Conheço um coração tão manso,",
	"    Dm       G7",	
	"humilde e sereno.",
	"     C             Em           Dm",
	"Que louva o Pai por revelar seu nome",
	"      G7",
	"aos pequenos.",
	"    F             G",
	"Que tem o dom de amar,",
    "    C   G/B    Am",
	"que sabe perdoar",
	"  Dm          F          G",
	"e deu a vida para nos salvar.",
    " ",
    "Refrão:",
	" F  G  C     G/B      Am",
	"Jesus, manda teu Espírito,",
	" Dm          F            G",
	"para transformar meu coração.",
	" F  G  C   G/B       Am",
	"Jesus, manda teu Espírito,",
	" Dm          G7          C",
    "para transformar meu coração.",
    " ",
    "Às vezes, no meu peito bate",
    "um coração de pedra,",
    "magoado, frio, sem vida,",
    "aqui dentro ele me aperta.",
    "Não quer saber de amar nem sabe perdoar,",
    "quer tudo e não sabe partilhar.",
    " ",
    "Refrão:",
	" F  G  C     G/B      Am",
	"Jesus, manda teu Espírito,",
	" Dm          F            G",
	"para transformar meu coração.",
	" F  G  C   G/B       Am",
	"Jesus, manda teu Espírito,",
	" Dm          G7          C",
    "para transformar meu coração.",
    " ",
    "Lava, purifica e restaura-me de novo.",
    "Serás o nosso Deus",
    "e nós seremos o teu povo.",
    "Derrama sobre nós a água do amor,",
	"o Espírito de Deus, nosso Senhor.",
    " ",
    "Refrão:",
	" F  G  C     G/B      Am",
	"Jesus, manda teu Espírito,",
	" Dm          F            G",
	"para transformar meu coração.",
	" F  G  C   G/B       Am",
	"Jesus, manda teu Espírito,",
	" Dm          G7          C",
    "para transformar meu coração."
];

export const Compadecete = [
    //_________________________________
    "     D          G",
    "Senhor, tem piedade.",
    "    A           D A/C#    Bm",
    "Senhor, tem piedade   de nós.",
    "        G        Em          A",
    "Compadece-te. Senhor, tende piedade.",
    "  D             G ",
    "Cristo, tem piedade.",
    "  A             D A/C#    Bm",
    "Cristo, tem piedade   de nós.",
    "      G        Em              A     B7",
    "Compadece-te. Cristo, tende piedade.",
    "    E           A",
    "Senhor, tem piedade.",
    "    B7          E B/D#    C#m",
    "Senhor, tem piedade   de nós.",
    "      A         F#m            B7       E",
    "Compadece-te. Senhor, tende piedade de nós.",    
];

export const KyrieEleison = [
    //_________________________________
    "    G                D",
    "1. Como a ovelha perdida,",
    "Em             D",
    "pelo pecado ferida",
    "C                 D             Em   D",
    "Eu te suplico perdão, ó bom pastor.",
    " ",
    "Refrão",
    " G      D      Em      D   C",
    "Kyrie eleison, Kyrie eleison,",
    " G  D  C D  G    D",
    "Kyrie eleison.",
    " ",
    "2. Como o ladrão perdoado,",
    "encontro o paraíso ao Teu lado",
    "Lembra-te de mim pecador, por Tua cruz.",
    " ",
    "Refrão",
    "Christe eleison, Christe eleison,",
    "Christe eleison.",
    " ",
    "3.Como a pecadora caída,",
    "derramo aos Teus pés minha vida.",
    "Vê as lágrimas do meu coração e salva-me.",    
    " ",
    "Refrão",
    "Kyrie eleison, Kyrie eleison,",
    "Kyrie eleison."
];

export const Misericordia = [
    //_________________________________
    "Refrão:",
    "G        D    Em         D",
    "Misericórdia, misericórdia,",
    "C        Am      D",
    "misericórdia Senhor. (2x)",
    " ",
    "Em          D     C      Am      D",
    "Cristo, piedade. Tem piedade de nós. (2x)",
    " ",    
    "Refrão:",
    "G         D   Em         D",
    "Misericórdia, misericórdia,",
    "C        Am      D",
    "misericórdia Senhor.",
    "G         D   Em         D ",
    "Misericórdia, misericórdia,",
    "C         Am D     G",
    "misericórdia Senhor."
];

export const PelosPecados = [
    //_________________________________
    "  G                       Am",
    "1. Pelos pecados, erros passados,",
    "          D            C         G",
    "por divisões na tua Igreja, ó Jesus.",
    " ",
    "Refrão:",
    "G7          C                G",
    "Senhor, piedade. Senhor, piedade.",
    "           Am        D       G  G7",
    "Senhor, piedade, piedade de nós.",
    "            C  Cm            G   Em",
    "Senhor, piedade. Senhor, piedade.",
    "            Am       D     G",
    "Senhor, piedade, piedade de nós.",
    " ",
    "   G                              Am",
    "2. Quem não te aceita, quem te rejeita,",
    "            D               C",
    "pode não crer por ver cristãos",
    "          G",
    "que vivem mal. (Cristo, piedade...)",
    " ",
    "Refrão:",
    "G7          C                G",
    "Senhor, piedade. Senhor, piedade.",
    "           Am        D       G  G7",
    "Senhor, piedade, piedade de nós.",
    "            C  Cm            G   Em",
    "Senhor, piedade. Senhor, piedade.",
    "            Am       D     G",
    "Senhor, piedade, piedade de nós.",
    " ",
    "  G                       Am",
    "3. Hoje, se a vida é tão ferida,",
    "          D              C             G",
    "deve-se a culpa à indiferença dos cristãos.",
    " ",
    "Refrão:",
    "G7          C                G",
    "Senhor, piedade. Senhor, piedade.",
    "           Am        D       G  G7",
    "Senhor, piedade, piedade de nós.",
    "            C  Cm            G   Em",
    "Senhor, piedade. Senhor, piedade.",
    "            Am       D     G",
    "Senhor, piedade, piedade de nós."
];

export const PerdaoDoJumas = [
    //_________________________________
    "Dm               Dm/C             Dm/B",
    "Perdoa-nos, Senhor, pela nossa alma jovem",
    "     Dm/Bb   Dm/B Dm/C",    
    "que sumiu no mar"," ",
    "Perdoa-nos, Jesus,", "",  
    "faz de nós um fogo novo para amar"," ",
    "Perdoa-nos, Senhor,"," ",
    "como jovens queremos renovar"," ",
    "Perdoa-nos, Senhor,"," ",    
    "como jovens queremos renovar",
];

export const PerdaoSenhorTantosErrosCometi = [
    //_________________________________
    "            C         F     G     C",
    "Perdão, Senhor, tantos erros cometi.",
    "           Em         F        G  C   C7",
    "Perdão, Senhor, tantas vezes me omiti.",
    "             F          G           Em",
    "/:Perdão, Senhor, pelos males que causei,",
    "     Am          Dm",
    "pelas coisas que falei,",
    "        G              C  C7",
    "pelo irmão que eu julguei. :/",
    " ",
    "Refrão:",
    "    F       G           Em       Am",
    "Piedade, Senhor. Tem piedade, Senhor.",
    "     Dm           G            C C7",
    "Meu pecado vem lavar com seu amor.",
    "    F       G           Em      Am",
    "Piedade, Senhor. Tem piedade, Senhor.",
    "    Dm          G             C G",
    "E liberta minha alma para o amor.",
    " ",  
    "Perdão, Senhor, porque sou tão pecador.",
    "Perdão, Senhor, sou pequeno e sem valor.",  
    "/:Mas mesmo assim tu me amas quero então", 
    "te entregar meu coração, suplicar teu perdão:/",    
    " ",
    "Refrão:",
    "    F       G           Em       Am",
    "Piedade, Senhor. Tem piedade, Senhor.",
    "     Dm           G            C C7",
    "Meu pecado vem lavar com seu amor.",
    "    F       G           Em      Am",
    "Piedade, Senhor. Tem piedade, Senhor.",
    "    Dm          G             C G",
    "E liberta minha alma para o amor."
];

export const Renovame = [
    //_________________________________
    "   D   G      A    Bm  G",
    "Renova-me Senhor Jesus,",
    "       D           A  A7",
    "já não quero ser igual",
    "     D   G      A    Bm",
    "Renova-me Senhor Jesus,",
    "G        D           A A7",
    "põe em mim teu coração!",    
    "        D     F#m     Bm     F#m G",
    "Porque tudo que há dentro de mim",
    "  Em          G         A  A7",
    "Precisa ser mudado, Senhor",
    "       D   F#m ,",
    "Porque tudo que há dentro",
    "   Bm      F#m G",
    "do meu coração",
    "   A             D",
    "Precisa mais de Ti"
];

export const SenhorEuEstouAqui = [
    //_________________________________
    "   D    A          Bm",
    "Senhor, eu estou aqui.",
    "            G     Em       A",
    "Venho te pedir piedade de mim.",
    "   Am   D           G",
    "Senhor, eu estou aqui.",
    "Gm          D     G  A     D",
    "Venho te pedir piedade de mim.",
    " ",
    "Refrão:",
    "    G A      D  Bm   G A      D  (D7)",
    "Piedade, piedade, piedade de nós (2x)",
    " ",
    "   D    A         Bm",
    "Senhor, estamos aqui.",
    "            G      Em       A",
    "Viemos te pedir piedade de nós.",
    "   Am   D          G",
    "Senhor, estamos aqui.",
    " Gm          D      G A     D  D7",
    "Viemos te pedir piedade de nós.",
    " ",
    "Refrão:",
    "    G A      D  Bm   G A      D  (D7)",
    "Piedade, piedade, piedade de nós (2x)"
];

export const SenhorQueViesteSalvar = [
    //_________________________________
    "   D        A7        D  D7", 
    "Senhor que viestes salvar,",
    "        G           A D  D7",
    "os corações arrependidos.",
    " ",
    "Refrão:",
    "   G        D  Bm    Em A    D",
    "Piedade, piedade, piedade de nós (bis)",
    " ",
    "Ó, Cristo que vieste chamar,",  
    "os pecadores humilhados.",
    " ",
    "Refrão:",
    "   G        D  Bm    Em A    D",
    "Piedade, piedade, piedade de nós (bis)",
    " ",
    "Senhor que intercedeis por nós,",   
    "junto a Deus Pai que nos perdoa",
    " ",
    "Refrão:",
    "   G        D  Bm    Em A    D",
    "Piedade, piedade, piedade de nós (bis)",
    " "
];

export const SenhorTendePiedadeDeNos = [
    //_________________________________
    "   Em   C         D      Em",
    "Senhor, tende piedade de nós. (2x)",
    "   Em   C         D      Em",
    "Cristo, tende piedade de nós. (2x)",
    "   Em   C         D      Em",
    "Senhor, tende piedade de nós. (2x)",
    "   G            C         Em",
    "Eu canto a alegria no Senhor",
    "    C       D        Em",
    "de ser perdoado no amor. (2x)"
];

export const TenhoSaudades = [
    //________________________________________
    "Intro: A A9 A4 A F#m D Bm E E4 E"," ",
    " A                         F#m",
    "Tenho saudades, saudades de Ti.",
    " D                 Bm              E E4 E",
    "Minha vontade é voltar atrás onde caí.",
    "   F#m      E                    D",
    "E recomeçar tudo de novo e nunca mais deixar",
    "    Bm              E",
    "Meu coração se esfriar.",
    "   D/F#   E/G#    Bm      A/C#   D E",
    "Te que----ro. Preciso do Teu calor.",
    " ",
    "Refrão:",
    "           A              F#m",
    "Quero me apaixonar por ti outra vez",
    "         D        Bm7                  E4 E",
    "Quero me entregar a ti mais e mais, Senhor.",
    "D/F#      E/G#              A         ( E )",
    "Leva-me de volta ao meu primeiro amor."
];

export const NoMuerasHermano = [
    //________________________________________
    "   A",
    "Te siento respirar,",
    "     F#m",
    "y te veo ahí en la cruz",
    "  D                         Bm",
    "Y busco en tus ojos, no hay nada de odio",
    "    D                    Bm            E",
    "a pesar de la sangre que cubre tu rostro.",
    " ",
    "Me miras una vez más,",
    "como hiciste junto al mar.",
    "No puedo ocultarte mis miedos humanos,",
    "quisiera que bajes, y seques mi llanto.",
    "Ya sabías de mi andar,",
    "y también de tu final,",
    "sabías que el gallo que canta tres veces,",
    "sería mi lanza que te abre el costado.",
    " ",
    "Refrão:",
    "   A E/G# F#m E   D      E",
    "Perdóname . . . Señor Jesús,",
    "     A E/G# F#m  E D E     A",
    "hoy quiero . conservar tu luz.",
    "Perdóname Señor Jesús,",
    "hoy quiero cargar con tu cruz.",
    " ",
    "Y estoy lejos de tus pies,",
    "en la tarde de mi rey.",
    "Me escondo entre gente",
    "que insulta y te odia,",
    "comieron tus panes y olvidan tu gloria.",
    "Y no puedo levantar ya",
    "mi espada sin pensar",
    "que quieres que todo",
    "se cumpla en su nombre,",
    "mostraste su rostro arriba del monte.",
    "Y María no se va, será siempre tu mamá,",
    "te pierde en secreto y te ama en lo eterno,",
    "un hombre que muere por el mundo entero.",
    " ",
    "Refrão:",
    "Perdóname Señor Jesús,",
    "hoy quiero conservar tu luz.",
    "Perdóname Señor Jesús,",
    "hoy quiero cargar con tu cruz.",
    "F#m Bm D E"," ",
    "F#m      Bm         D           E",
    "Tanto me amas y nunca sabré porqué,",
    " ",
    "si soy débil, y no te alcanzo a comprender,",
    "si me duermo en el huerto de tu fe,",
    "en la noche que te voy a perder.",
    "¿Quién te envía y porqué sólo confías?",
    "¿Quién te pide tu fracaso y soledad?",
    "Si ya curaste y nos diste de comer,",
    "Rey de mi vida, ¿Cuánto más vas a entregar?",
    " ",
    "       A                 F#m",
    "Ya te cuesta respirar y miras a tu papá",
    "    D                 Bm",
    "Y entregas de nuevo tu vida en sus manos.",
    "    F                  G           A",
    "Perdona mis faltas, no mueras hermano.",
];

export const CantoLouvoresAoPai = [
    //________________________________________
    " G                  F",
    "Canto louvores ao Pai. (2x)",
    " ",
    "Refrão:",
    "  G               F",
    "A Ele louvores e glória. (2x)",
    " ",
    " G                 F",
    "Canto louvores ao Filho. (2x)",
    " ",
    "Refrão:",
    "  G               F",
    "A Ele louvores e glória. (2x)",
    " ",
    " G                   F",
    "Canto louvores ao Espírito. (2x)",
    " ",
    "Refrão:",
    "  G               F",
    "A Ele louvores e glória. (2x)",
    " ",
    " G                   F",
    "Canto louvores à Trindade. (2x)",
    " ",
    "Refrão:",
    "  G               F",
    "A Ela louvores e glória. (2x)"
];

export const GloriaADeusNasAlturas = [
    //________________________________________
    "D                    C       G",
    "Glória a Deus nas alturas e paz na Terra",
    "                       D",
    "aos homens por Ele amados",
    "D             C",
    "Senhor Deus, Rei dos céus,",
    " G                 D",
    "Deus Pai todo poderoso",
    "          Am  D                   Am  D",
    "Nós vos louvamos, nós vos bendizemos",
    "            Am D                    Am D",
    "Nós vos adoramos, nós vos glorificamos",
    "               C",
    "Nós vos damos graças",
    "    G            D",
    "por vossa imensa glória",
    "D            C       G          D",
    "Senhor Jesus Cristo, Filho unigênito",
    "D                C",
    "Senhor Deus, cordeiro de Deus,",
    "G                D",
    "Filho de Deus Pai",
    "Am                 G",
    "Vós que tirais o pecado do mundo,",
    " C                D",
    "tende piedade de nós",
    "Am                 G",
    "Vós que tirais o pecado do mundo,",
    "C                 D",
    "acolhei a nossa súplica.",
    "Am                  G",
    "Vós que estais à direita do Pai,",
    "C                D",
    "tende piedade de nós",
    "              Am  D              Am D",
    "Só Vós sois o Santo, só Vós o Senhor",
    "           C               D",
    "Só Vós o Altíssimo, Jesus Cristo",
    " E             A",
    "Com o Espírito Santo",
    "                   G      D",
    "Na glória de Deus Pai. Amém! (4x)"
];

export const GloriaADeusNosAltosCeus = [
    //________________________________________
    " E         A             B7",
    "Glória a Deus nos altos céus,",
    " E      A               B7",
    "paz na Terra aos seus amados.",
    "E       A           B7",
    "A vós louvam Rei Celeste,",
    " E     A          B7",
    "os que foram libertados.",
    " ",
    "Refrão:",
    "C#m    B7 E     A    B7      E",
    "Glória a Deus, Glória a Deus",
    " ",
    "E      A              B7",
    "Deus e Pai nós vos louvamos,",
    "E   A           B7",
    "adoramos, bendizemos.",
    "E    A                B7",
    "Damos glória ao vosso nome,",
    "  E      A         B7 ",   
    "vossos dons agradecemos.",
    " ",
    "Refrão:",
    "C#m    B7 E     A    B7      E",
    "Glória a Deus, Glória a Deus",
    " ",
    "Senhor nosso, Jesus Cristo,",
    "Unigênito do Pai,",
    "Vós, de Deus Cordeiro Santo,",
    "Nossas culpas perdoai.",
    " ",
    "Refrão:",
    "C#m    B7 E     A    B7      E",
    "Glória a Deus, Glória a Deus",
    " ",
    "Vós, que estais junto do Pai,",
    "Como nosso Intercessor,",
    "Acolhei nossos pedidos,",
    "Atendei nosso clamor.",
    " ",
    "Refrão:",
    "C#m    B7 E     A    B7      E",
    "Glória a Deus, Glória a Deus",
    " ",
    "Vós somente sois o Santo,",
    "O Altíssimo, o Senhor,",
    "Com o Espírito Divino,",
    "De Deus Pai no esplendor."    
];

export const GloriaAoPaiCriador = [
    //________________________________________
    "Refrão:",
    "D G D D7  G A7 D     G",
    "Glória, . Glória ao Pai Criador,",
    "   D          Bm          Em      A  D",
    "ao Filho Redentor e ao Espírito, Glória.",
    " ",
    "   D        G     D D7",
    "Ao Pai criador do mundo,",
    "   G           A7      D",
    "ao Filho redentor dos Homens.",
    "      G   A7      D       Bm     G  A D",
    "Ao espírito de amor demos sempre glória"
];

export const GloriaGloriaAleluiaLouvemos = [
    //________________________________________    
    "Refrão:",
    " G",
    "Glória, glória, aleluia.",
    "  C                G",
    "Glória, glória, aleluia.",
    " G                  Em",
    "Glória, glória, aleluia.",
    "   Am7   D7     G",
    "Louvemos ao Senhor!",
    " ",
    "         G",
    "1. Na beleza do que vemos,",
    " ",
    "Deus nos fala ao coração",
    "     C",
    "Tudo canta: Deus é grande,",
    "       G",
    "Deus é bom e Deus é Pai.",
    "      G ",
    "É Seu Filho, Jesus Cristo,",
    "         Em",
    "quem nos une pelo amor.",
    "   Am    D      G",
    "Louvemos ao Senhor!",
    " ",
    "Refrão:",
    " G",
    "Glória, glória, aleluia.",
    "  C                G",
    "Glória, glória, aleluia.",
    " G                  Em",
    "Glória, glória, aleluia.",
    "   Am7   D7     G",
    "Louvemos ao Senhor!",
    " ",
    "2. Deus nos fez comunidade",    
    "pra vivermos como irmãos.",
    "Braços dados, todos juntos,",
    "caminhamos sem parar.",
    "Jesus Cristo vai conosco,",
    "Ele é jovem como nós.",
    "Louvemos ao Senhor!",
    " ",
    "Refrão:",
    " G",
    "Glória, glória, aleluia.",
    "  C                G",
    "Glória, glória, aleluia.",
    " G                  Em",
    "Glória, glória, aleluia.",
    "   Am7   D7     G",
    "Louvemos ao Senhor!",
    " ",
    "3. Jesus Cristo é alegria,",
    "Jesus Cristo é o Senhor.",
    "Da vitória sobre a morte,",
    "deu a todos o penhor.",
    "Venceremos a tristeza,",
    "venceremos o temor.",
    "Louvemos ao Senhor!",
    " ",
    "Refrão:",
    " G",
    "Glória, glória, aleluia.",
    "  C                G",
    "Glória, glória, aleluia.",
    " G                  Em",
    "Glória, glória, aleluia.",
    "   Am7   D7     G",
    "Louvemos ao Senhor!",
    " "
];

export const GloriaGloriaAleluia = [
    //________________________________________
    "Refrão:",
    "E                           B",
    "Glória, glória, glória, Aleluia,",
    "                             E",
    "Glória, glória, glória, Aleluia.",
    "                E7         A",
    "Glória, glória, glória a Deus",
    " ",
    "nos altos Céus.",
    "       E                 B     E",
    "Paz na terra na terra a todos nós!",
    " ",
    "  E                       B",
    "1. Deus e Pai nós vos louvamos:",
    " ",
    "Glória a Deus!",
    "               E",
    "Adoramos, bendizemos. Glória a Deus!",
    "                 E7   A",
    "Damos glória ao vosso nome:",
    "Glória a Deus!",
    "        E     B   E",
    "Vossos dons agradecemos.",
    "E                       B",
    "Senhor nosso Jesus Cristo:",
    " ",
    "Glória a Deus!",
    "               E",
    "Unigênito do Pai, Glória a Deus!",
    "                 E7  A",
    "Vós de Deus Cordeiro Santo,",
    "Glória a Deus!",
    "        E      B   E",
    "Nossas culpas perdoai.",
    " ",
    "Refrão:",
    "E                           B",
    "Glória, glória, glória, Aleluia,",
    "                             E",
    "Glória, glória, glória, Aleluia.",
    "                E7         A",
    "Glória, glória, glória a Deus",
    " ",
    "nos altos Céus.",
    "       E                 B     E",
    "Paz na terra na terra a todos nós!",
    " ",
    "2. Vós que estais junto do Pai,",
    "Glória a Deus!",
    "Como nosso intercessor.",
    "Glória a Deus!",
    "Acolhei nossos pedidos,",
    "Glória a Deus!",
    "Atendei nosso clamor.",
    "Vós somente sois o Santo,",
    "Glória a Deus!",
    "O Altíssimo Senhor. Glória a Deus!",
    "Com o Espírito Divino, Glória a Deus!",
    "De Deus Pai no resplendor.",
    " ",
    "Refrão:",
    "E                           B",
    "Glória, glória, glória, Aleluia,",
    "                             E",
    "Glória, glória, glória, Aleluia.",
    "                E7         A",
    "Glória, glória, glória a Deus",
    " ",
    "nos altos Céus.",
    "       E                 B     E",
    "Paz na terra na terra a todos nós!",
    " "   
];

export const LouvadoSejaOMeuSenhor = [
    //________________________________________
    "Refrão:",
    "G",
    "Louvado seja o meu Senhor",
    "Em",
    "Louvado seja o meu Senhor",
    "C                Am",
    "Louvado seja o meu Senhor",
    "D7",
    "Louvado seja o meu Senhor",
    " ",
    "       G",
    "1. Por todas suas criaturas,",
    "     Em",
    "pelo sol e pela lua,",
    "          C             Am",
    "Pelas estrelas do firmamento,",
    "     D7",
    "pela água e pelo fogo.",
    " ",
    "Refrão:",
    "G",
    "Louvado seja o meu Senhor",
    "Em",
    "Louvado seja o meu Senhor",
    "C                Am",
    "Louvado seja o meu Senhor",
    "D7",
    "Louvado seja o meu Senhor",
    " ",
    "          G",
    "2. Por aqueles que agora são felizes,",
    "     Em",
    "por aqueles que agora choram,",
    "       C              Am",
    "Por aqueles que agora nascem,",
    "      D7",
    "por aqueles que agora morrem.",
    " ",
    "Refrão:",
    "G",
    "Louvado seja o meu Senhor",
    "Em",
    "Louvado seja o meu Senhor",
    "C                Am",
    "Louvado seja o meu Senhor",
    "D7",
    "Louvado seja o meu Senhor",
    " ",
    "          G",
    "3. O que dá sentido à vida",
    "    Em",
    "é amar-Te e louvar-Te.",
    "      C          Am",
    "Para que a nossa vida",
    "     D7",
    "seja sempre uma canção.",
    " ",
    "Refrão:",
    "G",
    "Louvado seja o meu Senhor",
    "Em",
    "Louvado seja o meu Senhor",
    "C                Am",
    "Louvado seja o meu Senhor",
    "D7",
    "Louvado seja o meu Senhor",
];