export const ElQueMuerePorMi = [
	//_________________________________
    'C                    F7+',
    'Todo empezó en una cruz',
    '                   Am',
    'Donde un hombre murió',
    '                   G',
    'y un Dios se entregó',
    '  C                    F7+',
    'Silenciosa la muerte llegó',
    '                 Am',
    'Extinguiendo la luz',
    '                       G',
    'que en un grito se ahogó',
    ' ',
    'C                   F7+',
    'Viendo su faz de dolor',
    '             Am                G',
    'Una madre lloró y su amigo calló',
    '       C                   F7+',
    'Pero siendo una entrega de amor',
    '             Am',
    'Su camino siguió',
    '        G       F7+',
    'y en algún otro lado',
    '     G            C',
    'Una luz se encendió',
    ' ',
    'F                G',
    ' Siendo hombre, amigo,',
    '            Am',
    'esclavo y maestro',
    ' ',
    'Siendo carga pesada,',
    '      G          F',
    'profesor y aprendiz',
    '                    G',
    'Entregó hasta su cuerpo',
    '                    C G Em',
    'en el pan y en la vid',
    ' ',
    'Am       F            C',
    'Desde entonces lo he visto',
    '     G        Am',
    'caminar a mi lado',
    '       F            C',
    'A ese Dios que se humilla',
    '   G         Am',
    'y muere por mi',
    '       F            C',
    'Es la barca en mi playa,',
    '       G        Am',
    'el ruido del silencio',
    '         F         C',
    'Que se acerca a su hijo',
    '        G       Dm',
    'y me abraza feliz',
    'F                      G',
    ' Que se acerca a su hijo',
    '        C',
    'y me abraza feliz',
    ' ',
    'C                      F',
    'Viendo un humilde calvario',
    '               Am               G',
    'Con rostro cansado soporta la cruz',
    '       C                   F',
    'Y al verme rezando a sus pies',
    '             Am',
    'Se olvida de Él,',
    '    G         F',
    'me toma en sus brazos',
    '       G          C',
    'Y me acoge otra vez',
    ' ',
    'F                G',
    'Siendo fuego, paloma,',
    '               Am',
    'el agua y el viento',
    ' ',
    'Siendo niño inocente,',
    '    G          F',
    'un Padre y Pastor',
    '                 G',
    'Hoy acepta mi ofrenda,',
    '              C G Em',
    'es mi vida Señor',
    ' ',
    'Refrão…',
    'F               G',
    'Y si ahora yo acepto esta cruz',
    'Em             Am       G     F',
    'Es por esa persona, ese Dios',
    'G                 C     G Em',
    ' Es por Cristo, Jesús'
];

export const EstasEntreNos = [
    'Refrão:',
    'Em           C',
    'Tu és minha vida,',
    ' D              G',
    'outro Deus não há,',
    'Em              C',
    'Tu és minha estrada,',
    ' D          G',
    'a minha verdade.',
    'Am       D7',
    'Em tua palavra',
    ' G         Em',
    'eu caminharei.',
    'C             D',
    'Enquanto eu viver',
    '      G           B7',
    'e até quando tu quiseres.',
    'Am         D7',
    'Já não sentirei temor,',
    'G         Em',
    'pois está aqui,',
    'C           B7      Em',
    'Tu estás no meio de nós.',
    ' ',
    'Creio em ti Senhor,',
    'vindo de Maria,',
    'Filho eterno e Santo,',
    'Homem como nós.',
    'Tu morrestes por amor,',
    'vive estás em nós.',
    'Unidade trina',
    'com o Espírito e o Pai.',
    'E um dia eu bem sei,',
    'tu retornarás.',
    'E abrirás o Reino dos céus.',
    ' ',
    'Refrão:',
    'Em           C',
    'Tu és minha vida,',
    ' D              G',
    'outro Deus não há,',
    'Em              C',
    'Tu és minha estrada,',
    ' D          G',
    'a minha verdade.',
    'Am       D7',
    'Em tua palavra',
    ' G         Em',
    'eu caminharei.',
    'C             D',
    'Enquanto eu viver',
    '      G           B7',
    'e até quando tu quiseres.',
    'Am         D7',
    'Já não sentirei temor,',
    'G         Em',
    'pois está aqui,',
    'C           B7      Em',
    'Tu estás no meio de nós.',
    ' ',
    'Tu és minha força,',
    'outro Deus não há.',
    'Tu és minha paz,',
    'minha liberdade.',
    'Nada nesta vida',
    'nos separará.',
    'Em tuas mãos seguras',
    'minha vida guardarás.',
    'Eu não temerei o mal,',
    'Tu me livrarás',
    'e no teu perdão viverei.',
    ' ',
    'Refrão:',
    'Em           C',
    'Tu és minha vida,',
    ' D              G',
    'outro Deus não há,',
    'Em              C',
    'Tu és minha estrada,',
    ' D          G',
    'a minha verdade.',
    'Am       D7',
    'Em tua palavra',
    ' G         Em',
    'eu caminharei.',
    'C             D',
    'Enquanto eu viver',
    '      G           B7',
    'e até quando tu quiseres.',
    'Am         D7',
    'Já não sentirei temor,',
    'G         Em',
    'pois está aqui,',
    'C           B7      Em',
    'Tu estás no meio de nós.',
    ' ',
    'Ó Senhor da vida,',
    'creio sempre em ti!',
    'Filho Salvador,',
    'eu espero em Ti!',
    'Santo Espírito de amor,',
    'desce sobre nós.',
    'Tu de mil caminhos',
    'nos conduzes a uma fé.',
    'E por mil estradas',
    'onde andarmos nós,',
    'qual somente nos levarás!',
    'Refrão:',
    'Em           C',
    'Tu és minha vida,',
    ' D              G',
    'outro Deus não há,',
    'Em              C',
    'Tu és minha estrada,',
    ' D          G',
    'a minha verdade.',
    'Am       D7',
    'Em tua palavra',
    ' G         Em',
    'eu caminharei.',
    'C             D',
    'Enquanto eu viver',
    '      G           B7',
    'e até quando tu quiseres.',
    'Am         D7',
    'Já não sentirei temor,',
    'G         Em',
    'pois está aqui,',
    'C           B7      Em',
    'Tu estás no meio de nós.',
];

export const FerroEFogo = [
	//_________________________________
    ' G               D',
    'Dentro do teu santuário',
    '         C9         G',
    'posso sentir o teu amor',
    'G                   D',
    'Sinto e escuto em minha alma',
    '        C9',
    'seu corpo em meu corpo',
    '           G',
    'um só coração.',
    ' ',
    'E              Am',
    'Veja, não estou sozinho.',
    '         C              D',
    'Vamos soldados na mesma missão',
    ' ',
    'Refrão:',
    '  G        C9',
    'Jesus, somos ferro e fogo.',
    '  G        C9',
    'Jesus, uma nova espada',
    '     Em',
    'nas mãos de Maria,',
    '         Am                  D',
    'que por Schoenstatt queremos lutar.',
    '  G          C9                  G',
    'Jesus, pelo sangue derramado na cruz.',
    '        C9',
    'Faz-nos santos modernos,',
    '    Em',
    'na aliança de amor,',
    '         Am            D',
    'nossa vida queremos te dar...Jesus',
    ' ',
    'Toma Senhor em tuas mãos',
    'nossa juventude o jeito de ser',
    'Vem faz morada em nós,',
    'traz com alegria a luz do Tabor.'
];

export const JesusAlimentoQueDaVida = [
	//_________________________________
    'G    D/F#    C     G     D/F#  C',
    'O Senhor está aqui, para me abraçar',
    'G       D/F#   C  Am',
    'Com o Pão e o Vinho',
    '            D',
    'me transformará. (2X)',
    ' ',
    'Refrão:',
    '  G        D/F#        C',
    'Jesus, alimento que dá vida,',
    '  G           D/F#     C',
    'Jesus, sou mais filho do Pai',
    '      Em    D/F# C',
    'Jesus, como água viva',
    '        Am          D',
    'quero levar o Teu amor',
    '  G       D/F#         C',
    'Jesus, alimento que dá vida,',
    '  G            D/F#    C',
    'Jesus, sou mais filho do Pai',
    '      Em    D/F#  C',
    'Jesus, como água viva',
    '        Am         D',
    'quero levar o Teu amor',
    '               G',
    'aos homens, Senhor'
];

export const JesusEstouAqui = [
	//_________________________________
    '  C',
    'Jesus estou aqui,',
    '   C7                 F',
    'Jesus que esperas de mim?',
    '        C            G',
    'Minhas mãos estão vazias',
    '                   C',
    'que posso entregar-te.',
    ' ',
    'Refrão:',
    '     Am        G             C',
    'Eu só sei que quero ser diferente.',
    '  C7',
    'Jesus estou aqui,',
    '                       F',
    'Jesus que esperas de mim?',
    '     C             G G ',
    'Meus olhos temem ao olhar-te.',
    '                     C      D',
    'Queria poder enfrentar-te.',
    '   G          C',
    'Amar como Tu amas,',
    ' G              C',
    'Sentir como Tu sente,',
    ' Am                     D',
    'Olhar através dos teus olhos,',
    '  G C G',
    'Jesus.',
    '    G                   C',
    'Contigo meu caminho é difícil.',
    '    G                       C',
    'Me exiges abrir um novo horizonte.',
    'Am                   D      G C G',
    'Na solidão da minha noite, Jesus.',
    ' ',
    ' C',
    'Não, não posso abandonar-te,',
    ' C7                 F',
    'Jesus em mim Tu entraste,',
    '     C           G',
    'habitaste, triunfaste',
    '            C  D',
    'e vives em mim.'
];

export const JesusEstoyAqui = [
    //_________________________________
    '  C',
    'Jesús estoy aquí,',
    '  C7                  F',
    'Jesús, que esperas de mí,',
    '    C            G',
    'mis manos están vacías',
    '              C',
    'qué puedo ofrecerte,',
    '   Am        G              C',
    'sólo sé que quiero ser diferente',
    'C',
    'Jesús estoy aquí,',
    'C7                   F',
    'Jesús, que esperas de mí,',
    '    C               G',
    'mis ojos temen al mirarte',
    '                      C    D',
    'quisiera poder enfrentarte',
    ' ',
    'Refrão:',
    ' G            C',
    'Amar, como tú amas',
    '     G          C',
    'sentir como tú sientes',
    'Am                   D      G C G',
    'mirar através de tus ojos Jesús.',
    '    G                  C',
    'contigo, mi camino es difícil',
    '     G                        C',
    'me exiges abrir un nuevo horizonte',
    'Am                  D       G C G',
    'en la soledad de mi noche Jesús.',
    ' ',
    'No, no puedo abandonarte',
    'Jesús en mi penetraste Me habitaste,',
    'triunfaste, y hoy vives en mi.'
    
];

export const JoiaRara = [
	//_________________________________
    'C',
    'Este é o momento',
    '        F/C',
    'da mais pura doação',
    '     C',
    'De quem sabe amar',
    '          G',
    'como ninguém jamais amou.',
    'Am              F',
    'Ele nos dá sua vida.',
    '    Dm                   G',
    'Seu plano de amor nos revela.',
    ' ',
    'C              F/C',
    'É alimento da alma.',
    ' C                 G',
    'Pão que desceu do céu.',
    '    Am                     F',
    'Nos dá o Seu corpo e Seu sangue.',
    '      Dm      G    C  C7',
    'Para a nossa comunhão.',
    ' ',
    'Refrão:',
    '   F            G',
    'Jesus, Tú és a joia mais rara.',
    ' E            Am           G   F',
    'Fonte de vida que não se acaba.',
    'Dm',
    'Te entrego',
    '            G           C  C7',
    'todo o meu ser em gratidão.',
    '      F              G',
    'Permanece em mim com Teu amor,',
    ' E          Am     G  F',
    'Teu amor infinito.',
    'Dm             G        C',
    'Sela em mim a Tua salvação.'
];

export const LaSamaritana = [
	//_________________________________
    '   Bm           Bm/A',
    'Llegaste tan de pronto,',
    'Em',
    ' misterio de amor,',
    '    A             Bm',
    'tus ojos negros calaron hondo;',
    '        G',
    'y habitaron oscuros',
    '  D           A',
    'lados de mi cuerpo herido',
    '      G            D       A',
    'y tu luz me asombró…tu luz.',
    ' ',
    'Dame de beber',
    'Tú me dijiste,',
    'al tiempo de mil latidos',
    'de mi corazón.',
    'Si supieras el don',
    'de Dios quién te lo pide,',
    'tú vendrías a buscar mi agua.',
    ' ',
    'Refrão:',
    'G                  A        D    F#m',
    'Porque todo el que beba del agua que',
    '      Bm       G    Em',
    'Yo le dé tendrá vida,',
    '         A',
    'no tendrá sed.',
    'G                  A',
    'Porque todo el que beba',
    '       D     F#m   Bm   G',
    'de la fuente de mi vida limpiará sus',
    '   A              D',
    'heridas no tendrá sed.',
    ' ',
    'El agua que Tú me das',
    'llena mi pozo vacío,',
    'es agua de tu Espíritu',
    'en mi corazón,',
    'colma todos mis cántaros',
    'echos de barro',
    'y tu viento de amor me envuelve.',
    ' ',
    'Refrão:',
    'G                  A        D    F#m',
    'Porque todo el que beba del agua que',
    '      Bm       G    Em',
    'Yo le dé tendrá vida,',
    '         A',
    'no tendrá sed.',
    'G                  A',
    'Porque todo el que beba',
    '       D     F#m   Bm   G',
    'de la fuente de mi vida limpiará sus',
    '   A              D',
    'heridas no tendrá sed.',
    ' ',
    'El agua que Tú me das',
    'lava lo manchado,',
    'hace brotar del mal un bien,',
    'tu fuego quemó mis labios',
    'y me lancé a correr,',
    'tu nombre gritaré, cantaré.',
    ' ',
    'Refrão:',
    'G                  A        D    F#m',
    'Porque todo el que beba del agua que',
    '      Bm       G    Em',
    'Yo le dé tendrá vida,',
    '         A',
    'no tendrá sed.',
    'G                  A',
    'Porque todo el que beba',
    '       D     F#m   Bm   G',
    'de la fuente de mi vida limpiará sus',
    '   A              D',
    'heridas no tendrá sed.'
];

export const Lazaro = [
	//_________________________________
    '   D                 Bm',
    'Jesús, el camino era pesado,',
    '  G        Em             A',
    'Jesús por el viaje te has cansado,',
    '      D   F#           Bm',
    'Sin embargo no te importo,',
    '         G     A',
    'y estás aquí.',
    '  D                   Bm',
    'Jesús, he salido a tu encuentro,',
    '       G            Em            A',
    'Te esperaba con el corazón despierto,',
    '         D',
    'Pero es tarde,',
    '    F#           Bm',
    'para mí se pasó el tiempo…',
    'Bm/A                 G',
    ' Crees en mí me preguntaste,',
    '      Em          A',
    'Y tu mirada se clavó en mis ojos,',
    '            G       Em           A',
    'Yo creo en Ti, Señor, yo creo en Ti…',
    ' ',
    'Refrão:',
    '            G         A',
    'Te entrego todo mi corazón,',
    '          D                  F#',
    'Lo que me duele, lo que te hiero,',
    '          Bm',
    'Lo frágil que soy;',
    '        G         A',
    'Te conmoviste por mí,',
    '      C        Bm',
    'y me lloraste Señor,',
    '          G             Em',
    'Porque me viste solo en mi noche,',
    '       A',
    'En mi dolor.',
    '            G         A',
    'Te entrego todo mi corazón,',
    '          D                   F#',
    'Lo que me duele lo que te hiero,',
    '             Bm',
    'Lo frágil que soy;',
    '         G        A',
    'Te conmoviste por mí,',
    '        C      Bm',
    'y me tocaste Señor,',
    '           G              Em',
    'Porque tus manos lo pueden todo,',
    '           A',
    'si Tú eres Dios',
    '         D G D C9 D G A4 A7 D',
    'vivo por Ti…'
];

export const MajestosaEucaristia = [
	//_________________________________
    'E             B/E        C#m',
    'Ao abrir meus olhos no altar',
    '      E       B/E',
    'Vi o cálice sagrado',
    '       E           B',
    'com o sangue de Jesus.',
    'G#m         A            E',
    'E de dentro dessse mesmo cálice',
    '   A  F#m7              B',
    'subia Majestosa Eucaristia.',
    ' ',
    'E         B/E        C#m',
    'Em Tua presença eu me sinto',
    '       E',
    'Um mendigo',
    '   B/E     E           B',
    'sentado à mesa de um rei.',
    'G#m          A',
    'E sem ter como pagar',
    '   E          A',
    'tamanha refeição',
    '  F#m7                       B',
    'Só posso dar-te eterna gratidão',
    ' F#m7                     B C#m7',
    'O cálice e a hóstia eram um',
    '     F#m7',
    'Meu desejo também',
    '        B',
    'era com eles ser um.',
    ' ',
    'Refrão:',
    '        E      A           B',
    'Ser um só coração, meu Senhor.',
    '       E/G#         A         B',
    'O mesmo sangue nas veias, Senhor.',
    '     E              A         B',
    'Tua carne em minha carne, Senhor.',
    '       E             A     B',
    'O Teu sangue em meu sangue, Senhor',
    '            E    E/G#',
    'E estando unido a Ti,',
    '      A        F#m7',
    'esquecer-me de mim.',
    '      B',
    'Concedei que eu fique',
    '               E',
    'eternamente assim.'
];

export const MariaDeDeusSenhoraDaPaz = [
	//_________________________________
    '   G          D/F#',
    'É bom estarmos juntos',
    '      C   Am      D',
    'nesta mesa do Senhor',
    '        G          D/F#',
    'E sentirmos sua presença',
    '      C Am           D',
    'no calor do nosso irmão.',
    ' G               Bm',
    'Deus nos reúne aqui,',
    '             C     Am          D',
    'em um só Espírito, um só coração',
    ' G                Bm',
    'Toda a família vem,',
    '               C  Am           D',
    'não falta ninguém nesta comunhão.',
    ' ',
    'Refrao:',
    '   G',
    'E vem, cantando entre nós,',
    '          A',
    'Maria de Deus, Senhora da paz.',
    '   C      Am      D',
    'E vem, orando por nós,',
    '            G',
    'a Mãe de Jesus.',
    ' ',
    '  G              D/F#',
    'Maria, nossa mãezinha,',
    '      C    Am   D',
    'nos convida à união.',
    ' G             D/F#',
    'Sua presença une,',
    '         C    Am     D',
    'faz-nos todos mais irmãos.',
    ' G',
    'Nossa Senhora',
    '    Bm             C',
    'escuta o nosso silêncio,',
    'Am           D',
    ' a nossa oração',
    ' G             Bm',
    'E apresenta ao Filho,',
    '             C     Am       D',
    'que se dá no vinho, que se dá no Pão.'
];

export const Mestre = [
	//_________________________________
    'G    D/F#                Em Em/D',
    'Mestre, bom é estarmos aqui,',
    '             Am',
    'reunidos bem perto de ti,',
    'C                  D',
    ' no silêncio e na paz.',
    ' ',
    'Mestre, reunidos no amor,',
    'nós viemos ao Monte Tabor',
    'para em Ti repousar.',
    ' ',
    'Refrão:',
    '   G      D/F#      Am       Em',
    'E nós cantaremos a mesma canção,',
    '  C        Am        D',
    'unidos no mesmo coração.',
    ' ',
    'Mestre, ao sairmos daqui',
    'nós iremos teus passos seguir',
    'com sementes nas mãos.',
    ' ',
    'Mestre, nós queremos plantar',
    'o teu Reino em todo lugar',
    'e crescer como irmãos.',
    ' ',
    'Refrão:',
    '   G      D/F#      Am       Em',
    'E nós cantaremos a mesma canção,',
    '  C        Am        D',
    'unidos no mesmo coração.'
];

export const MeuPai = [
	//_________________________________
    '    G9                D/F#',
    'Meu Pai, que estás em mim',
    '    Emsus            C',
    'seja feita a Tua vontade',
    '   G9             Emsus',
    'Na minha alma, na minha história.',
    '   Am        G/B          C',
    'O pão que me dás, meu alimento.',
    'Em        D/F#  G9',
    'É o que me cura lava-me,',
    'Am       Em       A  D/F#',
    'lava-me com Teu amor',
    '     Em       D/F#',
    'Pois sou Teu servo,',
    'Bm  C C   C#dim   Dsus D',
    'Pai, servo da Tua luz.',
    ' ',
    'Refrão:',
    'G    D/F#  Em7     C9',
    'Santo é Teu nome, Pai.',
    'Am        Em     Dsus  D',
    'Acerca-me ao Teu peito',
    'G     D/F#  Em7    C9',
    'Livra-me de todo o mal',
    '   A       C      Em D/F#     G',
    'Esteja em mim Teu rei........no.',
    ' ',
    '    G9                D/F#',
    'Meu Pai, que estás em mim,',
    '    Emsus            C',
    'seja feita a Tua bondade',
    '   G9            Emsus',
    'Na minha vida, na minha trajetória.',
    '  Am         G/B          C',
    'O pão que me dás, meu sustento.',
    'Em         D/F#  G9',
    'É o que me sara, salva-me.',
    'Am        Em       A  D/F#',
    'Salva-me com Teu amor',
    '     Em      D/F#',
    'Pois sou Teu filho,',
    'Bm  C C   C#dim   Dsus D',
    'Pai, filho da Tua luz.',
    ' ',
    'Refrão:',
    'G    D/F#  Em7     C9',
    'Santo é Teu nome, Pai.',
    'Am        Em     Dsus  D',
    'Acerca-me ao Teu peito',
    'G     D/F#  Em7    C9',
    'Livra-me de todo o mal',
    '   A       C      Em D/F#     G',
    'Esteja em mim Teu rei........no.'
];

export const MilagreDeAmor = [
	//_________________________________
    '   G  D                        Em',
    'Jesus, aqui presente em forma real,',
    '   C       Am',
    'te peço um pouco mais',
    '    F            D',
    'de fé e de humildade.',
    '    G  D                       Em',
    'E assim possa ser digno de partilhar',
    '    C        Am',
    'contigo o maior milagre',
    'F               D',
    'de teu grande amor.',
    ' ',
    'Refrão:',
    '   G         D          Em',
    'Milagre de amor tão infinito,',
    '    Bm                 C',
    'em que tu, meu Deus te fazes',
    '       Am            G',
    'tão pequeno e tão humilde',
    '         D',
    'para entrar em mim.',
    '   G         D           Em',
    'Milagre de amor tão infinito,',
    '        Bm               C',
    'em que tu, meu Deus te esqueces',
    '         Am             G',
    'de tua glória e de tua majestade,',
    '      D',
    'por mim.',
    ' ',
    'E hoje venho,',
    'cheio de alegria',
    'receber-te nessa Eucaristia.',
    'Te dou graças,',
    'por chamar-me a esta ceia',
    'porque mesmo não sendo digno,',
    'tu visitas a minh’alma.',
    ' ',
    'Refrão:',
    '   G         D          Em',
    'Milagre de amor tão infinito,',
    '    Bm                 C',
    'em que tu, meu Deus te fazes',
    '       Am            G',
    'tão pequeno e tão humilde',
    '         D',
    'para entrar em mim.',
    '   G         D           Em',
    'Milagre de amor tão infinito,',
    '        Bm               C',
    'em que tu, meu Deus te esqueces',
    '         Am             G',
    'de tua glória e de tua majestade,',
    '      D',
    'por mim.',
    'FINAL: ',
    '     C         Bm',
    'Obrigado, Senhor,',
    '      C D      G',
    'por esta  comunhão!'
];

export const MissaoDeApostolo = [
	//_________________________________
    ' D              A          Bm',
    'Que missão tão bela é ser apóstolo',
    ' G           Em            A',
    'Seguir ao Senhor onde Ele vai',
    'D            F#           Bm',
    'Anunciar com gozo seu Evangelho',
    'G           D            A            D',
    'Ser para os homens portadores de sua paz.',
    ' ',
    'Tanto nos amou que ao despedir-se,',
    'na Santa Ceia aquela tarde',
    'nos deu como pão seu próprio corpo,',
    'e seu sangue como vinho de fraternidade.',
    ' ',
    'Tanto nos amou que um triste dia',
    'pregado na cruz Cristo morreu.',
    'E em sua morte Ele nos deu a vida,',
    'vida de alegria, vida de filhos de Deus.'
];

export const NinguemTeAmaComoEu = [
	//_________________________________
    ' A       E/G#         F#m',
    'Tenho esperado este momento,',
    'D           Bm        E',
    ' tenho esperado que viesses a mim.',
    'Tenho esperado que me fales,',
    'tenho esperado que estivesses assim.',
    ' ',
    'Eu sei bem o que tens vivido,',
    'sei também que tens chorado.',
    'Eu sei bem que tens sofrido,',
    'pois permaneço ao teu lado.',
    ' ',
    'Refrão:',
    '           A  E/G#  F#m',
    'Ninguém te ama como eu,',
    '           D  Bm     E',
    'ninguém te ama  como eu.',
    'Olhe pra cruz',
    'esta é a minha grande prova',
    'Ninguém te ama como eu.',
    'Ninguém te ama como eu,',
    'Ninguém te ama como eu,',
    'Olhe pra cruz,',
    'foi por ti, porque te amo,',
    'D           Bm E     A',
    ' ninguém te ama como eu',
    ' ',
    'Eu sei o que me dizes',
    'ainda que nunca me fales.',
    'Eu sei bem o que tens sentido',
    'ainda que nunca me reveles.',
    ' ',
    'Tenho andado a teu lado,',
    'junto a ti permanecido.',
    'Eu te levo em meus braços,',
    'pois sou teu melhor amigo.',
    ' ',
    'Refrão:',
    '           A  E/G#  F#m',
    'Ninguém te ama como eu,',
    '           D  Bm     E',
    'ninguém te ama  como eu.',
    'Olhe pra cruz',
    'esta é a minha grande prova',
    'Ninguém te ama como eu.',
    'Ninguém te ama como eu,',
    'Ninguém te ama como eu,',
    'Olhe pra cruz,',
    'foi por ti, porque te amo,',
    'D           Bm E     A',
    ' ninguém te ama como eu'
];

export const PaoDaVida = [
	//_________________________________
    ' A      A7+   A          A7+',
    'Na comunhão Jesus se dá no Pão',
    '     A      A7+            Bm  E',
    'o Cordeiro Imolado é refeição.',
    'A        A7+     A       A7+',
    'Nosso alimento de amor e Salvação',
    '   A         A7+             Bm  E',
    'em torno deste altar somos irmãos.',
    ' ',
    'Refrão:',
    '          A',
    'O Pão da vida és tu,',
    '   D     E       A  D E',
    'Jesus, o Pão do céu.',
    '     A           D    E      A',
    'O caminho, a verdade, via de amor.',
    '         E               A  E',
    'Dom de Deus, nosso redentor.',
    ' ',
    ' A       A7+       A        A7+',
    'Toma e come, isto é o meu corpo',
    '       A            A7+         Bm  E',
    'que do trigo se faz pão e refeição.',
    'A        A7+      A          A7+',
    'Na Eucaristia o vinho se torna Sangue',
    '   A        A7+             Bm   E',
    'Verdadeira bebida, nossa alegria.'
];

export const NoHayAmorMasGrande = [
	//_________________________________
    'C        G/B     Am',
    'Te doy mis manos Señor',
    '  F        Dm        G',
    'Para construir el mañana,',
    ' E               Am',
    'Me das tus rayos de sol',
    '         F  Dm      G',
    'Para abrigar mi esperanza.',
    ' ',
    '  D       A/C#    Bm',
    'Tienes mi canto y mi voz',
    '    G       Em      A',
    'Para encender corazones,',
    '  F#m             Bm',
    'Te tengo dentro de mí,',
    '            G      Em        A',
    'Voy a llevarte muy lejos de aquí...',
    ' ',
    'Refrão',
    'Am                 B7',
    'Que todo el mundo se entere Jesús',
    '      Em              A7',
    'Que eres vida, que eres la luz.',
    'D     A/C#',
    'No hay amor,',
    '   Bm    Bm/A      G',
    'No hay amor más grande,',
    'F#m          Bm G',
    'Nos diste tu vida',
    '   Em        A7',
    'en cruz y en dolor.',
    '  D     A/C#   Bm          G',
    'Por mi hoy, te entregas de nuevo,',
    'F#m         Bm   Bm/A      G    Em',
    'Te haces pequeño te olvidas de Ti,',
    '    A7',
    'mi Señor,',
    'Am              B7',
    'Dame tu Espíritu Santo',
    '       Em        A',
    'Para gritarlo más alto:',
    '        D         C',
    'Que no haya un lugar',
    '       G                  D C G',
    'en la tierra donde faltes Tú.',
    ' ',
    'C         G/B       Am',
    ' Quiero llegar al que sufre',
    '  F    Dm        G',
    'Para darle mi consuelo',
    'E                   Am',
    ' Quiero entregarle tu paz,',
    '          F Dm       G',
    'La buena nueva del Reino.',
    ' ',
    ' D     A/C#     Bm',
    'Tienes mi risa Señor,',
    '    G    Em       A',
    'Que transmite tu alegría',
    '  F#m           Bm',
    'Úsame como instrumento',
    '          G Em       A',
    'Hazme ser sal y fermento.'
];

export const ProvaDeAmor = [
    //_________________________________
    'Refrão:',
    'Dm                      Gm',
    'Prova de amor maior não há',
    'C                      Dm',
    'Que doar a vida pelo irmão.',
    ' ',
    '  Gm                C',
    '1. Eis que eu vos dou',
    '      F         Dm',
    'o meu novo mandamento:',
    ' Gm              C',
    'Amai-vos uns aos outros',
    '     F            Dm',
    'como Eu vos tenho amado',
    ' ',
    'Refrão:',
    'Dm                      Gm',
    'Prova de amor maior não há',
    'C                      Dm',
    'Que doar a vida pelo irmão.',
    ' ',
    '         Gm            C',
    '2. Vós sereis os meus amigos',
    '        F           Dm',
    'se seguirdes meu preceito:',
    ' Gm              C',
    'Amai-vos uns aos outros',
    '     F             Dm',
    'como Eu vos tenho amado.',
    ' ',
    'Refrão:',
    'Dm                      Gm',
    'Prova de amor maior não há',
    'C                      Dm',
    'Que doar a vida pelo irmão.',
    ' ',
    '         Gm             C',
    '3. Como o Pai sempre me ama,',
    '          F          Dm',
    'assim também eu vos amei:',
    '  Gm             C',
    'Amai-vos uns aos outros',
    '     F             Dm',
    'como Eu vos tenho amado.',
    ' ',
    'Refrão:',
    'Dm                      Gm',
    'Prova de amor maior não há',
    'C                      Dm',
    'Que doar a vida pelo irmão.'
];

export const QuaoGrandeEsTu = [
	//_________________________________
    '  F            F',
    '1. Senhor meu Deus,',
    '                Bb/F',
    'quando eu, maravilhado',
    '          C/E',
    'Fico a pensar',
    '    C7              F  Bb',
    'nas obras de Tuas mãos',
    '         F                  Bb/F',
    'No céu azul de estrelas pontilhado',
    '        C/E',
    'O Teu poder,',
    '    C7           F  Bb',
    'mostrando a criação',
    ' ',
    'Refrão:',
    '   C       F   Bb/F            F  Dm',
    'Então minh´alma canta a Ti, Senhor',
    '              Gm  C               F  Bb',
    'Quão grande és Tu! Quão grande és Tu! (2x)',
    ' ',
    '               F',
    '2. Quando a vagar',
    '               Bb/F',
    'nas matas e florestas',
    '      C/E    C7              F  Bb',
    'O passaredo alegre ouço a cantar',
    '            F',
    'Olhando os montes,',
    '          Bb/F',
    'vales e florestas',
    '        C/E     C7           F  Bb',
    'O teu poder mostrando a criação',
    ' ',
    'Refrão:',
    '   C       F   Bb/F            F  Dm',
    'Então minh´alma canta a Ti, Senhor',
    '              Gm  C               F  Bb',
    'Quão grande és Tu! Quão grande és Tu! (2x)',
    ' ',
    '               F',
    '3. Quando eu medito',
    '                Bb/F',
    'em seu amor tão grande',
    '          C/E',
    'Teu filho dando',
    '    C7           F  Bb',
    'ao mundo pra salvar',
    '            F',
    'Na cruz vertendo',
    '               Bb/F',
    'o seu precioso sangue',
    '          C/E      C7      F  Bb',
    'Minh´alma pode assim purificar',
    ' ',
    'Refrão:',
    '   C       F   Bb/F            F  Dm',
    'Então minh´alma canta a Ti, Senhor',
    '              Gm  C               F  Bb',
    'Quão grande és Tu! Quão grande és Tu! (2x)'
];
