export const JumasSomosNos = [
  //_________________________________
  '    A       E      F#m',
  'Reunidos estamos aqui,',
  '  A      E         F#m',
  'com Maria e seu Filho.',
  '   D                 E',
  'Viver a Aliança de Amor,',
  '               F#m',
  'nosso grande ideal.',
  '    A          E       F#m',
  'No campo de batalha da vida',
  '         A        E      F#m',
  'construiremos um mundo melhor.',
  '        D           E',
  'Homens novos que caminham,',
  '            F#m',
  'Jumas vamos lá!',
  ' ',
  'Refrão:',
  '  A    E    F#m',
  'Jumas somos nós.',
  ' A     E        F#m',
  'Jumas marche a frente.',
  '          D         E',
  'Coração jovem e disposto,',
  '            F#m',
  'não vamos parar.',
  '      D       E',
  'Liderar e formar',
  '               F#m',
  'Homens para lutar.',
  ' ',
  'O Santuário há de ser',
  'o nosso grande quartel.',
  'Com muros vivos de amor,',
  'Jumas sua Missão.',
  'Nossa Espada é de Maria,',
  'nossos sonhos são sempre os mesmos.',
  'A vitória de cada dia,',
  'vamos buscar.',
  ' ',
  'Refrão:',
  '  A    E    F#m',
  'Jumas somos nós.',
  ' A     E        F#m',
  'Jumas marche a frente.',
  '          D         E',
  'Coração jovem e disposto,',
  '            F#m',
  'não vamos parar.',
  '      D       E',
  'Liderar e formar',
  '               F#m',
  'Homens para lutar.'
];

export const MaeDoNossoTabor = [
  //_________________________________
  '   A                  E',
  'Grandes desafios que eu enfrentei',
  '        F#m',
  'para estar aqui.',
  ' A                 E',
  'Muitos duvidaram, outros nem notaram,',
  'F#m',
  'mas eu resisti.',
  ' ',
  ' Bm    C#m',
  'Porque vale a pena',
  '   D               E',
  'lutar sempre por Ti,',
  'Bm    C#m',
  'Juntos com Maria',
  '      D         E',
  'a história construir.',
  'A             E       F#m',
  ' Aqui é bom estar, na força da Aliança',
  '      D        E',
  'a vontade de lutar.',
  'A             E          F#m',
  'Aqui é bom estar, na ousadia da Aliança',
  'D        E       A',
  'vamos o mundo mudar.'
];

export const MaeDaAlianca = [
  //_________________________________
  'Intro: A7+ (A/C#) D9',
  ' ',
  'A                  D',
  'Mãe, eu sei que é Tua',
  '  F#m    A',
  'a minha aliança.',
  'A          D',
  'O meu coração entrego',
  '  F#m    E',
  'a Ti, oh Mãe.',
  '        A         E/G#',
  'Mas perdoe a minha falta,',
  '  F#m',
  'pecador eu sei que sou.',
  '        Bm        E      A (D/E)',
  'É por isso que eu volto aqui.',
  ' ',
  'Refrão:',
  '        A   E/G#     F#m',
  'E te consagro todo meu ser',
  '              D',
  'Pois sou Teu filho e',
  '     A/C#          E',
  'sempre  assim quero ser,',
  '     (A/C#)',
  'oh Mãe',
  '   D           E/D    C#m',
  'E mesmo que eu volte a cair,',
  '   F#   Bm           D  E',
  'eu sei. Sei que estarás ali',
  '    D           E    F#m',
  'Por isso me consagro a ti,',
  '     E       D',
  'oh Mãe... oh Mãe...',
  '  E     A',
  'Mãe da Aliança',
  ' ',
  'A7+ (A/C#) D9',
  '(Oração de Consagração)',
  ' ',
  'Refrão:',
  '        A    E/G#     F#m',
  'E te consagro todo meu ser',
  '              D',
  'Pois sou Teu filho e',
  '     A/C#         E',
  'sempre assim quero ser,',
  '     (A/C#)',
  'oh Mãe',
  '    D          E/D    C#m',
  'E mesmo que eu volte a cair,',
  '   F#   Bm           D  E',
  'eu sei. Sei que estarás ali',
  '    D           E    F#m',
  'Por isso me consagro a ti,',
  '     E       D',
  'oh Mãe... oh Mãe...',
  ' E      F#m',
  'Mãe da Aliança',
  ' ',
  '  D        E/D',
  'E em teu Santuário,',
  'C#m        F#m',
  'recebo Tuas graças.',
  '  D           E/D',
  'De lá recebo abrigo,',
  '  C#m      F#m',
  'então sou enviado,',
  '   D              E',
  'depois de transformado.',
  '       A     A/C#',
  'Me assemelhas ao',
  '    D   A/C# Bm E',
  'Teu filho.',
  ' ',
  'Refrão:',
  '        A    E/G#    F#m',
  'E te consagro todo meu ser',
  '              D',
  'Pois sou Teu filho e',
  '     A/C#          E',
  'sempre assim quero ser,',
  '     (A/C#)',
  'oh Mãe',
  '   D           E/D    C#m',
  'E mesmo que eu volte a cair,',
  '    F#  Bm           D   E',
  'eu sei. Sei que estarás ali',
  '   C#m F#m    C#m D ',
  '....oh Mãe... Oh Mãe... ',
  'E     A',
  'Mãe da Aliança'
];

export const MasAllaDelMar = [
  //_________________________________
  'A            D',
  'Amaneció en la tierra',
  '        A',
  'del Reino de Dios',
  'A                   D',
  'Es el momento en que todos',
  '               E',
  'son parte del sol',
  '         F#m',
  'Hoy es la luz la',
  '      E         D',
  'que invade el silencio',
  '      F#m         E      D',
  'y que brilla cual invitación',
  '      Bm          F#m',
  'a ser llama para quién',
  '          E',
  'no crea en ti',
  '      Bm       G          E',
  'a ser extraordinario el vivir.',
  ' ',
  ' A                      D',
  'Hoy es encuentro de hermanos',
  '            A',
  'que van a partir',
  'A                  D',
  'Hoy son sus manos ejemplos',
  '                   E',
  'a los que han de venir',
  '         F#m        E          D',
  'Se hace inmenso el gozo en el cielo',
  '       F#m      E         D',
  'cuando hay humildad en la voz',
  '     Bm          F#m          E',
  'de aquellos que no temen a soñar',
  '      Bm             G       E',
  'si es Cristo el fundamento de la paz',
  ' ',
  'Refrão:',
  '       A                  E',
  'Que se llenen los oídos de cantar,',
  '         F#m          E          D',
  'que se inflamen las sonrisas al rezar,',
  '        Bm       F#m            E',
  'pues el corazón revienta de su ardor,',
  '          Bm',
  'porque es Cristo el que',
  'G             E',
  'inunda mi canción.',
  '           A',
  'Que seamos todos parte',
  '             E',
  'de su bienestar,',
  'F#m E D',
  'que su victoria vuele',
  ' ',
  'más allá del mar,',
  '         Bm',
  'pues la vida se hace',
  'F#m           E',
  'fácil con su voz,',
  '      F#m',
  'porque siempre',
  '      E             D',
  'está presente alrededor,',
  '    G',
  'ese Dios que es tangible,',
  '      D      E           A',
  'infinito y visible en el amor.',
  ' ',
  '  A                     D',
  'Se abre la puerta a los que',
  '           A',
  'necesitan bondad',
  'A                  D',
  'Hay que buscar expresión',
  '                    E',
  'más sencilla en el dar',
  '      F#m     E       D',
  'Porque se necesitan de pasos',
  '      F#m      E       D',
  'que recorran caminos sin fin',
  '    Bm       F#m           E',
  'Con María aferrada en las manos',
  '      Bm       G         E',
  'y la mente dispuesta a servir.',
  ' ',
  '(Refrão)',
  ' ',
  '   A                   D',
  'Se abren las puertas del',
  '               A',
  'cielo más allá del mar.'
];

export const NossaRazaoDeViver = [
  //_________________________________
  'Refrão:',
  'Em            D          G',
  'Ó Senhora, estamos aqui para te',
  '      B7 Em                 D',
  'oferecer tudo o que somos e temos:',
  '        G            B7  Em',
  'Homens novos, nosso ser, nossa razão de viver.',
  ' ',
  '    D             G',
  'Em busca das ligações',
  'D                   G',
  'entre a ciência e a fé,',
  '    B7             Em',
  'Deixando falar a razão,',
  '       B7         Em',
  'tendo Deus no coração.',
  ' G               D',
  'Vínculos ao Santuário,',
  '   C           B7',
  'a Ti e ao Fundador',
  '     G              D',
  'São metas a conquistar',
  '         C          B7',
  'no dia–a–dia, no falar.',
  ' ',
  'Tendo um estilo de vida, geração fundadora.',
  'Buscando organicidade em todas as situações.',
  'Unidos em um ideal, filiais e heroicos,',
  'seremos monumentos vivos guiados por um carisma.'
];

export const NovaGeracao = [
  //_________________________________
  'D               C           G',
  'Um novo amanhecer, uma nova missão,',
  '                 D',
  'lutar por teu amor.',
  'C                 G',
  'Maria espera por mim,',
  '                 D C G',
  'Espera por meu Sim',
  'D                     C',
  'Lembro o dia em que o céu',
  '                G',
  'e a terra se fizeram um,',
  '                 D',
  'E tudo por meu Sim',
  'C                G',
  'Do meu Sim ao Amor',
  '                     D',
  'Por Cristo, meu Senhor.',
  'C                G',
  'Confio em Ti, Maria',
  '               D        C G',
  'Em nossa Aliança de Amor',
  ' ',
  'Refrão:',
  'D                  C',
  'Vinculados por Maria,',
  '              G',
  'Ser Fogo do Cristo Tabor',
  '            D',
  'Viver meu Ideal',
  'C               G',
  'Levar a Tua alegria,',
  '                D',
  'Eis a Nova Geração!',
  'C               G',
  'Geração Missionária,',
  '              D',
  'fiel a Aliança de Amor!',
  ' ',
  'D                   C',
  'Um Mundo Novo surgirá,',
  '                 G',
  'Com Maria e por Cristo',
  '                     D',
  'A Humanidade transformar.',
  'C           G',
  'Em Teu coração,',
  '                D',
  'encontro meu lugar.',
  'C                G',
  'Confio em Ti, Maria.',
  '                 D',
  'Tua estrela me guiará'
];

export const NuevasPlayas = [
  //_________________________________
  'E                  C9',
  'En este mar navego, y cantando vengo',
  'D4                      E',
  'hacia las nuevas playas voy.',
  'En este barco encuentro un corazón muy nuevo',
  'que comienza a despertar.',
  'Y su madero huelo, es agua y sal, y el viento',
  'se lleva mi respirar.',
  'Y su bandera al vuelo muestra el rostro que refleja',
  'la fuerza de la vida.',
  '(E E/D C9 B7 E)',
  ' ',
  'Y quiero anclar mi barco en el cimiento del faro',
  'y alumbrar con los demás.',
  'En la playa vamos buscando corazones',
  'que nos quieran ayudar.',
  'Es el amor que urge, el podre me surge',
  'encuentra mi mano para darse.',
  'Y la alegría encuentro, los otros me la dieron',
  'y el Sol que alumbra una vez más.'
];

export const OMundoTudoENossoCampoDeBatalha = [
  //_________________________________
  'E',
  'Já aponta no horizonte',
  'E7                  E',
  '  missionários que levam',
  '      A4 A A4 A',
  'o Senhor',
  'E',
  'Vinculados na Aliança,',
  'E7             E',
  '  construindo um',
  '          A4 A A4 A',
  'Brasil-Tabor',
  'G                       A',
  'Seguiremos os passos de Engling',
  'G              D          E',
  'É por Cristo que vamos lutar!',
  ' ',
  'Refrão:',
  'Bm',
  'O mundo todo, todo o mundo,',
  '                  A   A9/11 A A9/11',
  'é nosso campo de batalha!',
  'Bm',
  'Maria, avança com Teu Filho!',
  '                      A    A7 A A7',
  'Somos a Geração Missionária!',
  ' ',
  'E',
  'Vem e avança no horizonte',
  'E7             E',
  '  a geração do fogo',
  '            A4 A A4 A',
  'do Cristo Tabor!',
  'E',
  'Uma missão lhes é confiada:',
  'E7              E',
  '  por Maria, levar',
  '         A4 A A4 A',
  'ao Salvador.',
  'G                           A',
  'Guardaremos fiel e heroicamente',
  'G             D           E',
  'Tua herança e vamos proclamar:',
  ' ',
  'Refrão:',
  'Bm',
  'O mundo todo, todo o mundo,',
  '                  A   A9/11 A A9/11',
  'é nosso campo de batalha!',
  'Bm',
  'Maria, avança com Teu Filho!',
  '                      A    A7 A A7',
  'Somos a Geração Missionária!'
];

export const PaiFundador = [
  //_________________________________
  'Dm             C',
  'Filialidade provada fez-se filho',
  '            Dm',
  'pra ser pai também.',
  'Dm                 C',
  'Com grande amor a Maria',
  '               Dm',
  'educou-se em sua missão.',
  ' C               Dm',
  'Ouvindo o seu chamado,',
  ' C7                   F',
  'intérprete da voz de Deus,',
  '  Gm          Dm',
  'exemplo de bondade,',
  '   Gm             A7',
  'modelo dos filhos seus.',
  ' ',
  'Dm     C',
  'Pai, Pai, Pai Fundador,',
  '                      Dm',
  'Seu carisma por nós é vivido,',
  ' ',
  'alguns viram, outros não,',
  '      C',
  'não importa,',
  '                          Dm',
  'somos Tabor de uma mesma Família.',
  ' ',
  ' Dm               C',
  'Paternidade espontânea, profunda,',
  '           Dm',
  'consciente e forte.',
  'Dm                        C',
  'A história marcou sua presença;',
  '                       Dm',
  'presenteou-nos com a fundação.',
  ' C                Dm',
  'Espelho da Mãe Admirável,',
  '       C7             F',
  'sempre Pai das gerações.',
  '  Gm                Dm',
  'Sente-se agora mais forte',
  '       Gm               A7',
  'a importância das vinculações.'
];

export const PegoAPeregrina = [
  //_________________________________
  'G                   C',
  'Hoje eu acordei com uma inspiração.',
  ' G',
  'Levar Maria ao mundo',
  '       D',
  'com a sua proteção',
  '   G',
  'Schoenstatt é um lugar',
  '       C',
  'em que posso confiar',
  '       G',
  'Minha vida vou amar',
  '            D',
  'e com alegria missionar',
  ' ',
  'Am                 C',
  'Deus está aqui, comigo Ele irá',
  '    G                          D',
  'Invadir as casas o seu amor levar',
  '    F        Em',
  'Por isso andarei',
  ' Am           G/B',
  'sem me desviar',
  '     C',
  'Com força e amor',
  '         D',
  'tenho o mundo a mudar',
  ' ',
  'Refrão:',
  '    G          C9',
  'Eu pego a Peregrina',
  '  D           G',
  'e levo na missão',
  ' D9/F#       C9',
  'Pulando e cantando',
  '     D              G',
  'eu mostro minha emoção',
  'G     C9 D   G',
  ' Parapapapapapa',
  ' D9/F# C9 D  G',
  'Parapapapapa...',
  ' ',
  'G                   C',
  'Família por família eu visitarei.',
  '       G',
  'Dando um sentido à vida',
  '      D',
  'nas palavras que direi.',
  '  G                   C',
  'Pela vinculação minha fé aumentarei.',
  '    G                      D',
  'A exemplo de Maria sua mensagem levarei.'
];

export const Pioneiro = [
  //_________________________________
  '      A                E',
  'O Pioneiro é amigo de todos.',
  '      A                  E',
  'O Pioneiro faz bem para todos.',
  '      A            D      E',
  'O Pioneiro ama a Maria e grita:',
  '               A   A7',
  '“NOS CUMPRO LEPIA”',
  ' ',
  'Refrão:',
  '        D   E                A',
  'Sou Pioneiro, com muita alegria',
  'A7       D  E                A',
  ' e sou amigo de quem ama a Maria.',
  ' ',
  '      A             E',
  'O Pioneiro abre caminho,',
  '       A                  E',
  'o Pioneiro nunca está sozinho.',
  '      A              D',
  'O Pioneiro ama a natureza',
  ' E                   A   A7',
  'e cuida dela com firmeza.',
  ' ',
  'Refrão:',
  '        D   E                A',
  'Sou Pioneiro, com muita alegria',
  'A7       D  E                A',
  ' e sou amigo de quem ama a Maria.'
];

export const Providencia = [
  //_________________________________
  'E',
  'Abre o céu,',
  '          A9          E A9',
  'manhã clara a nascer',
  'E              A9               E',
  'Águas calmas refletem teu poder',
  '                 A9 E A9 E A9',
  'Novo sol, novo ser',
  '  ',
  'E               A9            E A9',
  'Brisa leve cantando ao soprar',
  'E',
  'Brilho ameno,',
  '        A9           E',
  'seus raios a lançar',
  '             A9  E',
  'Para me iluminar',
  '  ',
  'Refrão:',
  'E           A9',
  'O teu rosto, os teus olhos,',
  ' E                 A9',
  'teu sorriso aguardando eu dizer',
  'E         A9',
  'A vontade, a minh´alma,',
  ' E                 A9',
  'em tuas mãos abandono',
  '     E   A9 E A9',
  'o meu viver',
  '  ',
  'Teu Amor me aponta a direção',
  'Teu abraço, a mais forte proteção',
  'Sinto teu coração'
];

export const PuerEtPater = [
  //_________________________________
  'Bm     F#m         G          D A#º',
  'Soy un niño aún, apenas yo te veo',
  'Bm          F#m',
  'Ni siquiera puedo pensar',
  '      G      D    A#º',
  'en decir si quiero',
  '   Bm           F#m',
  'me tomas en tus brazos',
  '   G             D   A#º',
  'me guías en mi llanto',
  '  Bm             F#m',
  'levantas tu mi frente',
  '     G         A7',
  'me enseñas a mirar',
  ' ',
  'Refrão:',
  '        D          Em',
  'Que al final del camino',
  '        F#m         G',
  'hay un Padre con su Hijo',
  '      D               Em',
  'y la Madre, desde el cielo',
  '     F#m               G',
  'cuida ya del mundo entero',
  '         D           Em',
  'Que mis obras no son nada',
  '     F#m           G  Gm',
  'si no son del corazón,',
  '     D                 Em',
  'del amor de un Padre al Hijo,',
  '     G       A       D',
  'del amor que me da Dios.',
  ' ',
  '   Bm        F#m',
  'Me meto al camino,',
  '     G              D    A#º',
  'tus huellas yo he de seguir,',
  '      Bm          F#m',
  'donde haz metido mano',
  '     G           D  A#º',
  'ahí he de construir',
  '        Bm            F#m',
  'y cantar al mundo entero',
  '       G          A7',
  'lo que aprendí de ti.',
  ' ',
  'Refrão:',
  '        D          Em',
  'Que al final del camino',
  '        F#m         G',
  'hay un Padre con su Hijo',
  '      D               Em',
  'y la Madre, desde el cielo',
  '     F#m               G',
  'cuida ya del mundo entero',
  '         D           Em',
  'Que mis obras no son nada',
  '     F#m           G  Gm',
  'si no son del corazón,',
  '     D                 Em',
  'del amor de un Padre al Hijo,',
  '     G       A       D',
  'del amor que me da Dios.',
  ' ',
  'A#º = x12020'
];

export const QueroHojeMeEntregar = [
  //_________________________________
  '  D               Bm',
  'Cristo eu quero sentir',
  'Bm/A     G      A7',
  '   que estás bem aqui',
  '  D      Eº      Bm  Bm/A',
  'Senhor inquieto estou,',
  '         G       A',
  'tenho um Mundo a mudar',
  '         D   A7',
  'e simples sou',
  'D              Bm Bm/A',
  'Sei que tu me amas,',
  '       G              A7',
  'sei também que tu me queres',
  'D          Eº      Bm Bm/A',
  'Quero, Senhor, honrar',
  '    G          A         D  D7',
  'a vida que me deste para amar',
  ' ',
  'Refrão:',
  ' G                 A7',
  'Senhor toma minhas mãos,',
  '    D   Eº        Bm',
  'faça delas teus instrumentos,',
  '      G         A7            D D7',
  'como jovem quero hoje me entregar',
  '    G      A7',
  'Com filialidade',
  '         D   Eº     Bm',
  'e minha força missionária,',
  '  G              A7          D',
  'quero um novo Schoenstatt fundar',
  ' ',
  'Cristo posso ouvir tua voz a me chamar',
  'Sinto-me seguro com o meu sim',
  'quero outros jovens cativar',
  'Sendo diferença quero seguir',
  'sempre ao mais alto',
  'Adoro-te senhor com minha fé',
  'e minha alegria em poder te ajudar',
  ' ',
  'Refrão:',
  ' G                 A7',
  'Senhor toma minhas mãos,',
  '    D   Eº        Bm',
  'faça delas teus instrumentos,',
  '      G         A7            D D7',
  'como jovem quero hoje me entregar',
  '    G      A7',
  'Com filialidade',
  '         D   Eº     Bm',
  'e minha força missionária,',
  '  G              A7          D',
  'quero um novo Schoenstatt fundar',
  ' ',
  'Eº = xx2323'
];

export const QueridaMta = [
  //_________________________________
  'Intro: Dm7 Am7 F Dm G',
  ' ',
  '         C',
  'Por que será que a minha força,',
  '  F',
  'é difícil de esgotar,',
  '          Dm7',
  'por que será que a minha voz,',
  '         C',
  'não se cansa de cantar,',
  '         F',
  'por que será que eu me alegro,',
  '       Em                 A7',
  'quando em Ti começo a pensar,',
  '        Em           A7',
  'e quando tudo esta perdido,',
  '       Dm            G',
  'novos sonhos tu me traz?',
  ' ',
  'Refrão:',
  'C         F         G',
  'Querida MTA, tu és Mãe,',
  '     C',
  'és a Rainha.',
  '          F',
  'Querida MTA,',
  '        G              C',
  'sou teu filho e teu soldado',
  '         F',
  'Querida MTA,',
  '        G         C',
  'tudo isso que eu sinto,',
  '          Am7',
  'não consigo explicar,',
  '      G',
  'não consigo decifrar,',
  '    Dm7                     G',
  'mas esta melodia nasceu do amor',
  '          C   G',
  'que Tu me dás.',
  ' ',
  'C',
  'Essa força que me faz',
  '      F',
  'sempre junto a ti estar,',
  '     Dm7',
  'essa voz firme e vibrante',
  '          C7+',
  'por ti não para de gritar',
  '      F',
  'A alegria de poder',
  '       Em              A7',
  'para Schoenstatt trabalhar, e',
  '        Dm7',
  'na Aliança de Amor,',
  '     G',
  'minha vida te entregar.',
  ' ',
  'Refrão:',
  'C         F          G           C',
  'Unido à Maria, conquistei um ideal.',
  '                F',
  'Nesse mundo desigual,',
  '     G        C',
  'vivencio a missão.',
  '                     F',
  'Do Cristo, Filho de Deus',
  '      G            C',
  'ser na terra um sinal,',
  '       Am7',
  'incendiar os corações,',
  '         G',
  'tendo um pouco deste amor.',
  '      Dm7',
  'Vinculados por Maria,',
  '    G             G# A# C',
  'fogo do Cristo Tabor'
];

export const SequeMeEscuchas = [
  //_________________________________
  ' G                      D',
  'Sí, Padre, sé que me escuchas',
  'C9                  D',
  'Por ti vivir no es solo existir',
  '       G        D',
  'Sino soñar y crear',
  '       C9',
  'Y la montaña escalar',
  '           D',
  'Aunque me cueste subir',
  '          C9          Cm',
  'Porque en pos de un ideal',
  '         G      Em',
  'Tiene sentido vivir',
  '       C       D',
  'Y no dejarme jamás vencer',
  '    C9  D       G  G7',
  'Y luchar hasta morir.',
  ' ',
  'C               Cm',
  'Por ti grito verdades',
  '       G          G7',
  'Sin callar jamás',
  'C            Cm',
  'Mis miedos enfrento',
  '       G         G7',
  'Y el “qué dirán”',
  'C9           Cm',
  'Me armo de coraje',
  '   G    F# E',
  'Soy roca y fuego',
  '  A',
  'Enciendo la magia que hay en mí',
  'C',
  'Y así por nobles',
  '   A           D',
  'ideales vivir.',
  ' ',
  'Sí, Padre, sé que me escuchas',
  'Como el siervo fiel,',
  'por ti, uso mis talentos',
  'Pongo mi fuerza en las cosas',
  'Mi esperanza virgen,',
  'mi fe combatiente',
  'Quiero ser como el roble',
  'Firme y fuerte',
  'Poner así mi sangre y mi ser',
  'Y luchar hasta morir.',
  ' ',
  'Por ti escalo la cumbre',
  'Sin mirar atrás',
  'De la playa mi barca',
  'Saco y entro al mar',
  'Despierto en el alba',
  'Y me alegro del día',
  'Escucho las olas que me hablan de Dios',
  'Despliego mis alas y logro volar.',
  ' ',
  ' G                     D',
  'Sí, Padre, sé que me escuchas',
  'C9         D',
  'Sí, Padre, sé',
  'G                  D',
  'Por los grandes ideales',
  ' C9',
  'tiene sentido',
  ' D',
  'tiene sentido,',
  ' C9       D      G',
  'tiene sentido vivir'
];

export const SiaoMulticolor = [
  //_________________________________
  ' E',
  'Ao acordar com novas forças,',
  '    A           B7',
  'olhamos para o monte.',
  '  E',
  'Uma luz que nos faz viver,',
  '       A            B7',
  'Uma luz que nos transforma.',
  ' A         B7         G#m7',
  'Seguimos até a fonte e bebemos',
  '        C#m7',
  'dos seus mistérios.',
  '    A           F#m7',
  'Sião dos homens novos,',
  '   A        B7',
  'Sião do fogo eterno.',
  ' ',
  'Refrão:',
  'E   G#m7    C#m7',
  'Sião é multicor,',
  '     A  F#m7     B7',
  'renova a nossa vida,',
  '   E        G#m7   C#m7',
  'Faz morada em cada cor.',
  '    A',
  'Santuário que vive',
  ' F#m7    B7  (2ª. vez: E)',
  'em nova vida. (2X)',
  ' ',
  'Hoje descemos ao mundo,',
  'Levamos o Deus de amor.',
  'Para iluminar as cidades,',
  'Com espirito de paz.',
  'Vida se acende com vida,',
  'O amor se acende com amor.',
  'Unidos no coração de Deus,',
  'Somos família do Pai Fundador.',
  ' ',
  'Refrão:',
  'E   G#m7    C#m7',
  'Sião é multicor,',
  '     A  F#m7     B7',
  'renova a nossa vida,',
  '   E        G#m7   C#m7',
  'Faz morada em cada cor.',
  '    A',
  'Santuário que vive',
  ' F#m7    B7  (2ª. vez: E)',
  'em nova vida. (2X)'
];

export const Stabat = [
  //_________________________________
  'Intr. A9 E F#m G A9 E F#m G E A',
  ' ',
  'A9    E      F#m    G',
  'Una tarde sin sol,',
  'A9      E       F#m G  E A9',
  ' fue probado el amo-o-o-or',
  'Con la sangre de un Dios,',
  'un hombre y su misión.',
  'Tus amigos se han ido,',
  'traicionado y vendido,',
  'Solo una te espera,',
  'aunque su alma se quiebra.',
  ' ',
  'E Bm                 D',
  '   No hay madero de gloria,',
  '                   A9',
  'no hay reino ni victoria.',
  '                E',
  'Las promesas flaquean,',
  '                 Bm',
  'pero tu Madre contempla.',
  '                    D',
  'Y pasaran dos mil años,',
  '                   A9',
  'y habrá tiempos de prueba,',
  '                E    G',
  'pero junto a la tuya,',
  '     D          A      E',
  'nacerán Cruces Negras.',
  'F#m        C#m           B',
  ' Si mi trabajo has de soñar,',
  '         D      E    F#m',
  '¡tu juventud te lo dará!',
  'Todas mis fuerzas derramar,',
  '¡tu juventud te lo dará!',
  'El fuego de mi corazón,',
  '¡tu juventud te lo dará!',
  'Ser fiel en mi Alianza de Amor,',
  '¡tu juventud te lo dará! (2X)',
  '(F#m G E A9 E F#m G A9)',
  ' ',
  'Fuente de tu costado,',
  'nuestra tierra has regado.',
  'La pradera florece,',
  'mi vasija has llenado.',
  'No has mirado mis manos,',
  'me has confiado un hermano,',
  'Me has dejado que elija,',
  'libremente te amo.',
  'Porque nuestra bandera',
  'no se iza en un mástil,',
  'fue grabada en el alma,',
  'en cada misa renace.',
  'Firmes como su reina,',
  'siempre al pie del Santuario,',
  'Por tu obra de Schoenstatt,',
  'aquí están tus soldados.',
  ' ',
  'Al final: ',
  'F#m       C#m           B',
  '  Decirte “Mater aquí estoy”,',
  '       D     E F#m',
  'tu juventud te lo dará'
];

export const TuAmor = [
  //_________________________________
  '  A9            Bm5b11/A',
  'María me regalas una nueva cruz',
  '  A9                       Bm5b11/A',
  'Y tengo miedo de perder tu luz',
  'A9',
  'Pero tú me dices:',
  'Bm5b11/A',
  '“Yo contigo estoy”',
  'A9            Bm5b11/A',
  'Y yo te digo: “Sin ti nada soy”',
  '      F#m7           C#m7   D7+',
  'Tengo miedo a lo que vaya pasar',
  '        Bm',
  'Sólo tu nombre',
  '    Bm/A    E     F7+/G',
  'yo quiero cantar',
  ' ',
  'Refrão:',
  ' C',
  'María madre mía,',
  '         Bsemiº Bº',
  'a esta aventura',
  '            Am',
  'me quiero lanzar',
  '       F7     Fm7       C',
  'De tu mano forjar santidad,',
  '        Bsemiº Bº        Am',
  'para el Padre poder entregar',
  '         F        D/F#  G Am  G',
  'Nuestra cruz en la fidelidad,',
  '         F         D/F# C',
  'nuestra cruz en la fidelidad.',
  '  C                       Bsemiº',
  'María madre mía por todos lados',
  'Bº            Am',
  '   yo quiero gritar',
  '        F7       Fm7   C',
  'Que tu nombre me regala paz,',
  '       Bsemiº Bº    Am',
  'que contigo yo puedo confiar',
  '        F        D/F#        G',
  'Y agradecerte por lo que me das',
  'Am G          F         G',
  '     y agradecerte por lo',
  '       C',
  'que me das.',
  '  A9             Bm5b11/A',
  'María tú conoces mi debilidad,',
  ' A9                  Bm5b11/A',
  'Tengo miedo a la soledad.',
  'A9',
  'Pero tú me dices:',
  'Bm5b11/A',
  '“Yo contigo estoy”',
  'A9',
  'Y yo te digo:',
  'Bm5b11/A',
  '“Sin ti nada soy”',
  '         F#m7      C#m7   D7+',
  'Ahora por fin tengo seguridad',
  '              Bm',
  'Porque en tus pasos',
  '      Bm/A     E    F7+/G',
  'yo encuentro verdad',
  ' ',
  'A9 x02420',
  'F7+/G 3x3210',
  'Bsemiº x2323x',
  'Bm5b11/A x03430',
  'Bº X2313X'
];

export const UmAliado = [
  //_________________________________
  '    G          C              G',
  'As coisas de criança não faço mais,',
  '               C              D',
  'e guardo na lembrança e no coração.',
  ' Am                      C',
  'Sei que eu preciso de uma nova atitude,',
  '        G',
  'pra encarar o mundo, enfrentar o mundo.',
  '      Am',
  'Se eu tenho uma Mãe,',
  '  C                          D',
  'só tenho uma missão, ser diferente.',
  ' ',
  'Refrão:',
  ' G     C                   G',
  'Sim, o mundo eu vou conquistar,',
  '     C',
  'e a minha resposta',
  '  Am                  C',
  'A tua missão Pai, é a minha missão,',
  '        D       ( G )',
  'serei um aliado (de ti).',
  ' ',
  'Em                 C           D',
  'E se o mundo não puder me entender,',
  'Em                  C             D',
  'eu digo agora sim eu sei porque viver.'
];
