export const Amem = [
	//_________________________________
    "  D  F#m    A G     F#m Em D",
    "Amém! Amém! Amém! Amém! Amém!"
];

export const Amem2 = [
	//_________________________________
    "D A  Bm F#m G   A   D  (B)",
    "Amém, amém, a a a amém",
    "E B  C#m G#m A   B   E",
    "Amém,  amém, a a a amém"
];

export const ABarca = [
	//_________________________________
    "   C G7                  C   C7",
    "1. Tu  te abeiraste na praia",
    "        F                    G7",
    "Não buscaste nem sábios, nem ricos",
    "          C   G7          C     C7",
    "Somente queres  que eu te siga.",
    " ",
    "    F  G7                  C    Am",
    "Senhor,  Tu me olhaste nos olhos",
    "   Dm    G7                 C    C7",
    "A sorrir,  pronunciaste meu nome",
    "       F    G7                 C     Am ",
    "Lá na praia,  eu larguei o meu barco",
    "       Dm  G7                C G7",
    "Junto a Ti,  buscarei outro mar",
    " ",
    "2. Tu sabes bem que em meu barco",
    "Eu não tenho nem ouro nem espadas",
    "Somente redes e o meu trabalho.",
    " ",
    "3. Tu minhas mãos solicitas",
    "Meu cansaço, que a outros descansem",
    "Amor que almeja seguir amando."
];

export const AcendeUmaLuz = [
	//_________________________________
    "              G",
    "Acende uma luz,",
    "                    Em",
    "e deixa ela brilhar;",
    "                C",
    "É a luz de Jesus",
    "        Am                D",
    "que brilha em todo lugar.",
    "                    G",
    "Não a podes esconder,",
    "                   Em",
    "não a podes calar.",
    "      C",
    "Em toda situação,",
    "Am         D              G",
    " acende uma luz na escuridão."
];

export const AlmaDeCristo = [
	//_________________________________
    "E        C#m     A       E",
    " Alma de Cristo santifícame",
    "B7          C#m   A     E",
    "  Cuerpo de Cristo sálvame",
    "           B7            C#m",
    "Sangre de Cristo embriágame",
    "A                     E   B7    E F#m",
    " Agua del costado de Cristo lávame",
    "            E   F#m        E",
    "Pasión de Cristo   confórtame",
    "F#m          E F#m  E",
    "  Oh buen Jesús  óyeme",
    "  A              E   B7       C#m",
    "Y dentro de tus llagas escóndeme",
    "        A          E         B7 F#m",
    "Y no permitas que aparte de Ti",
    "       E   F#m       E",
    "Del enemigo  defiéndeme",
    "F#m                  E F#m     E",
    "  En la hora de mi muerte llámame",
    "  A            E",
    "Y mándame ir a Ti,",
    "B7           C#m",
    "para con tus Santos",
    "     A            E",
    "Te alabe por los siglos",
    "       B7",
    "de los siglos",
    "  E   A E",
    "Amen, amen"
];

export const Amar = [
	//_________________________________
    "Intr. G6 D9/F# F7+ C G/B C Am C D",
    " ",
    "  G6         D9/F#",
    "Señor, yo no quiero sentir",
    "       F7+",
    "que tu mandamiento de amor",
    "   C        G/B   C",
    "es sólo una obligación",
    " Am",
    "quiero entregarme de adentro",
    " C         D",
    "quiero ser tu instrumento.",
    " ",
    "Señor, quiero ser feliz",
    "amando a los demás",
    "en mi forma natural",
    "quiero reír y quiero llorar",
    "con lo que me diste para gozar.",
    " ",
    "  G       D                 Em",
    "Amar, yo quiero aprender a amar",
    "          Bm      C  G/B",
    "como me hiciste amar",
    "   Am",
    "al darme tu soplo divino",
    "    C                 D",
    "cuando marcaste mi ideal.",
    "Amar, yo quiero aprender a amar",
    "como me hiciste amar",
    "para sentir que estoy vivo",
    "porque hay algo que puedo dar",
    "     G6 D9/F# e  C G6",
    "tu amor,   tu amor.",
    " ",
    "Señor, quiero descubrir",
    "que hay algo que me diste",
    "que puedo compartir",
    "y poder abrazarme confiado a la vida",
    "sabiendo que voy a hacerte feliz.",
    " ",
    "final:",
    "E  A       E                F#m",
    " Amar, yo quiero aprender a amar",
    "          C#m     D",
    "como me hiciste amar",
    "   Bm",
    "al darme tu soplo divino",
    "    D                 E",
    "cuando marcaste mi ideal.",
    " ",
    "Amar, yo quiero aprender a amar",
    "como me hiciste amar",
    "para sentir que estoy vivo",
    "porque hay algo que puedo dar",
    "    A   E  F#m   D A",
    "tu amor, tu amor.",
    " ",
    "G6 = 320030",
    "D9/F# = 200230"
];

export const AmorSemFim = [
	//_________________________________
    " Am",
    "Quando ouvi teu chamado",
    "    G",
    "Tentei me esconder",
    "  Dm",
    "Fugir de mim, Dizer, enfim,",
    "    E4         E",
    "Que tudo era bobagem.",
    " ",
    "Foi no Santuário",
    "Conversando com Maria",
    "Que eu descobri Que o seu Sim",
    "      E4         E     E4 E",
    "Permitiu gerar o Salvador",
    " ",
    "   Am             Dm",
    "A luz que vem de Ti, Jesus",
    "   G               Am",
    "É luz no meu coração",
    "    Dm",
    "Chamado de amor",
    " Dm /C",
    "Amor sem fim",
    "   E4       E   E4 E",
    "Saudades de Ti.",
    " ",
    "Por isso estou aqui, Jesus",
    "Venho me oferecer",
    "Pois só em Ti, encontro o fim",
    "  E4           E Am",
    "A luz do meu viver.",
    " ",
    "Quando estou contigo",
    "Me sinto um novo homem",
    "Chamado a dizer",
    "Convidado a levar",
    "Esse Amor ao mundo inteiro.",
    " ",
    "Como um fogo ardente",
    "Que incendeia e consome",
    "Eu percebi",
    "Que o meu sim",
    "É um incendiar corações",
    "A chama desse fogo em mim",
    " ",
    "A luz que ilumina o meu viver",
    "Braseiro de amor",
    "Amor sem fim",
    "É por Ti, Jesus, que eu sigo",
    " ",
    "Por isso estou aqui, Jesus",
    "Venho me oferecer",
    "Pois só em Ti, encontro o fim",
    "A luz do meu viver."
];

export const ABibliaEAPalavraDeDeus = [
	//_________________________________
    " F      F7    Bb        Bbm",
    "A Bíblia é a Palavra de Deus,",
    "   F        G      C  C7",
    "semeada no meio do Povo",
    "        F",
    "Que cresceu,",
    "     F7         Bb  Bbm",
    "cresceu e nos transformou",
    "     F          C7",
    "ensinando-nos viver",
    "         F",
    "um mundo novo",
    " ",
    "A                Dm",
    "Deus é bom, nos ensina a viver,",
    "C               F       F7",
    "nos revela o caminho a seguir:",
    "Bb      Bbm      F",
    "só no amor partilhando seus Dons,",
    "       G                C  C7",
    "sua presença iremos sentir.",
    " ",
    "Somos o povo, o povo de Deus,",
    "e formamos o Reino de irmãos",
    "e a Palavra que é viva",
    "nos guia e alimenta a nossa união."
];

export const CaminhoDeEternidade = [
	//_________________________________
    "Intr. D7+ Em (2x)",
    " ",
    "  D7+          Em",
    "Caminho de eternidade,",
    " D7+             Em",
    "na vinha de nosso senhor,",
    "  D7+               Em         Bm7  Em",
    "Na paz do filho perseguido, no amor.",
    " ",
    "No olhar do Pai que ilumina,",
    "mãos dadas com a mãe do céu.",
    "Sereno que luta e caminha,",
    "com a fé em Deus.",
    " ",
    "F#m7       Bm7    F#m7     Bm7",
    " Filho do céu, eternidade no ar",
    "    F#m7          Bm7         D7+",
    "No amor, caminho verdade minha vida",
    " ",
    "Sou terra, mas também sou filho,",
    "dia a dia passo a passo eu vou",
    "Semeando o verde a esperança,",
    "a flor eu vou",
    "Partilhar minha fé, minha cultura,",
    "coroando aliança de amor,",
    "Com minha cruz meu canto e minha alegria,",
    "com meu Senhor"
];

export const CantarABelzaDaVida = [
	//_________________________________
    "    D              A",
    "Cantar a beleza da vida,",
    "   Bm                 F#",
    "presente do amor sem igual",
    "   G          A7        D",
    "Missão do Teu povo escolhido!",
    "    E7                     A",
    "Senhor, vem livrar-nos do mal!",
    " ",
    "    D                     A",
    "Vem dar-nos Teu Filho, Senhor,",
    "   Bm                F#",
    "sustento no pão e no vinho,",
    "     G         A7      D  Bm",
    "e a força do Espírito Santo.",
    "  E7       A7       D",
    "Unindo Teu povo a caminho!",
    " ",
    "  D                      A",
    "Falar do Teu filho às nações,",
    " Bm                F#",
    "vivendo como Ele viveu",
    "   G          A7        D",
    "Missão do Teu povo escolhido,",
    "   E7                        A",
    "Senhor, vem cuidar do que é Teu!",
    " ",
    "Viver o perdão sem medida,",
    "servir sem jamais condenar",
    "Missão do Teu povo escolhido,",
    "Senhor, vem conosco ficar!",
    " ",
    "Erguer os que estão humilhados,",
    "doar-se aos pequenos, aos pobres",
    "Missão do Teu povo escolhido,",
    "Senhor, nossas forças redobre!",
    " ",
    "Buscar a verdade, a justiça,",
    "nas trevas brilhar como a luz",
    "Missão do Teu povo escolhido,",
    "Senhor nossos passos conduz!",
    " ",
    "Andar os caminhos do mundo,",
    "plantando Teu Reino de paz",
    "Missão do Teu povo escolhido,",
    "Senhor, nossos passos refaz!",
    " ",
    "Fazer deste mundo um só povo,",
    "fraterno, a serviço da vida",
    "Missão do Teu povo escolhido,",
    "Senhor, vem nutrir nossa lida!"
];

export const APazEstejaContigo = [
	//_________________________________
    " E              A  E",
    "A paz esteja contigo,",
    "                A E",
    "a paz esteja comigo",
    "   E             A",
    "A paz esteja com ele,",
    "    E         F#7         B7",
    "com ela e com todos os irmãos.",
    "   E            A  E",
    "A paz esteja contigo,",
    "                A E",
    "a paz esteja comigo",
    "   E             A",
    "A paz esteja com ele,",
    "    E         A           E",
    "com ela e com todos os irmãos.",
    " ",
    "Am            E",
    "Como Jesus pediu.",
    "Am           E",
    "Como Jesus orou.",
    "Am                  E",
    "Como Jesus nos ensinou.",
    " ",
    "E     A    E            A9",
    "Paz, paz, paz na nossa Igreja.",
    "E      Am",
    "Paz na Terra",
    "                      E",
    "em toda parte e assim seja. (2x)",
    " ",
    "E         A9",
    "Paz pra você",
    "          Am          E",
    "que tem Jesus no coração.",
    "C#m7      F#7           Am7",
    "Paz pra você que é meu amigo",
    "         E",
    "e meu irmão. (2x)"
];

export const CantanaroNino = [
	//_________________________________
    "D",
    "Cántaro de Barro,",
    "         F9",
    "que tus grietas se han notado,",
    "      G                          D",
    "y avergüenzan tu armonía y tu Ideal.",
    " ",
    "Cántaro de Barro, te incomoda tu pasado,",
    "Y no quieres confrontarte una vez más.",
    "Cántaro de Barro, has sellado tu costado,",
    "Y no dejas que perciban tu verdad.",
    "Cántaro de Barro, de tristezas te has llenado,",
    "Y no entiendes que agrietado te amo más.",
    " ",
    "      A/D",
    "Porque lo que llevas",
    "               G",
    "dentro es un milagro",
    "                 Bm F#m Em",
    "que Yo quise modela-a-a-ar",
    "      A/D",
    "Cada grieta que se abre",
    "        G",
    "son ventanas que",
    "              Bm F#m Em",
    "Mi luz regalará-á-á-án.",
    "      C      A",
    "Cántaro, cántalo",
    "D         G",
    "Hoy, te repito una vez",
    "           Em",
    "más que te amo",
    "                  G",
    "como estás y te elijo",
    "     A",
    "para derramarme (2X)",
    "Bm         F#m     G",
    "Hoy quiero ver tu Luz,",
    "Bm        F#m          G",
    "quiero que cargues tu Cruz.",
    " ",
    "Cántaro de Barro, no te inquietes si me tardo,",
    "no te apures elevando tu dolor.",
    "Siéntelo despacio, date tiempo es complicado,",
    "hay secretos en tu noble corazón.",
    "Cántaro de Barro, no me tengas por malvado,",
    "y si lo haces, sea por nuestra amistad.",
    "Cántaro de Barro, no sonrías por agrado,",
    "Fortalécete al contrario y vuela más.",
    " ",
    "(Refrão)",
    "Alfarero cuesta tanto, hacer vida lo que canto,",
    "pero sueño que algún día llegaré.",
    "Sé que es un regalo el sentirse así de amado,",
    "      G              A          D",
    "Te lo pido entonces con toda mi fe.",
    " ",
    "F9 = xx3010"
];

export const CenaDeJueves = [
	//_________________________________
    "Bm A6       G7+(b5)",
    "Sentado a la mesa,", 
    "       Bm A6 G7+(b5)",
    "me esperas Señor,",
    "Bm A6       G7+(b5)",
    "Recorres con calma,",
    "   Bm A6 G7+(b5)",
    "mi día de hoy.",
    "Bm A6      G7+(b5) Bm",
    "Ya comen los otros,",
    "A6     G7+(b5)",
    "rodeando tu rostro.",
    "Bm A6         G7+(b5)",
    "Un fuego encendido,",
    "Bm A6        G7+(b5)",
    "pan y jarras de vino.",
    " ",
    "Bm A6             G7+(b5)",
    "Pero aguardo lejano,",
    "        Bm A6 G7+(b5)",
    "no quiero arruinar",
    "Bm A6   G7+(b5)",
    "Tu última cena",
    "                 Bm A6 G7+(b5)",
    "con mi pobre amistad.",
    "Bm        A6    G7+(b5) Bm",
    "No has probado bocado,",
    " A6     G7+(b5)",
    "falta un invitado.",
    "Bm A6       G7+(b5) Bm A6",
    "Me buscas ansioso,",
    "    G7+(b5)   Em7",
    "me extiendes la mano.",
    " ",
    "  F#7     G F#7",
    "Tomad y comed,",
    "        Em7",
    "todos de Él.",
    "  F#7     G   A",
    "Tomad y bebed,",
    "               D",
    "¿Cómo negarme?",
    "        Em7",
    "No soy digno",
    "          G        D G6/9 D",
    "de que entres en mi casa,",
    "        Em7",
    "Y no entiendo",
    "        G        D G6/9 D",
    "cómo adoras mi morada.",
    "     Em7       G",
    "No merezco heredar",
    "         D        G6/9 D",
    "tus mandamientos",
    "         Em7",
    "No soy digno,",
    "         G          Bm A6 G7+(b5)",
    "pero aún así me llamas.",
    " ",
    "Bm A6",
    "Maestro,",
    "   G7+(b5)        Bm A6 G7+(b5)",
    "es difícil seguir tu verdad.",
    "Bm A6",
    "Me pides",
    "    G7+(b5)         Bm A6 G7+(b5)",
    "que deje lo que aún puedo dar.",
    "Bm A6       G7+(b5)",
    "Pretendo dar saltos,",
    "Bm A6            G7+(b5)",
    "    y cruces a cuestas.",
    "Bm A6    G7+(b5)",
    "Y dudo sincero,",
    "Bm A6       G7+(b5)",
    "   si soy de esta fiesta.",
    " ",
    "Bm A6     G7+(b5)",
    "Sonríes callado,",
    "            Bm A6 G7+(b5)",
    "y lavas mis pies.",
    "Bm A6",
    "Y aún de",
    "  G7+(b5)     Bm A6 G7+(b5)",
    "rodillas me dices “Lo se",
    "Bm A6         G7+(b5)",
    "No elijo a los sabios,",
    "Bm A6        G7+(b5)",
    "    ni a ricos, ni a santos.",
    "Bm A6      G7+(b5)",
    "Deja que habite,",
    "Bm A6      G7+(b5)      Em7",
    "  en tu casa este rato”.",
    " ",
    "A6* x02222",
    "G7+(b5)* 3x4420",
    "G6/9* xx5455"
];

export const ComoEsLindo = [
	//_________________________________
    "     D        A/C#",
    "Que bom, Senhor,",
    "           Bm     Bm/A",
    "ir ao teu encontro,",
    "   G           A          D        A",
    "poder chegar e adentrar à tua casa.",
    "  Bm        F#m",
    "Sentar-me contigo",
    "  G            A",
    "e partilhar da mesma mesa.",
    "D       A/C# Bm     F#m",
    "Te olha-ar,  te tocar",
    "  G",
    "e te dizer:",
    "     A7          D    A7",
    "meu Deus, como és lindo! (x2)",
    " ",
    "Ó meu Senhor, sei que não sou nada:",
    "sem merecer, fizeste em mim tua morada,",
    "mas ao receber-te perfeita comunhão se cria.",
    "Sou em Ti, és em mim.",
    "Minh'alma diz: meu Deus, como és lindo! (2x)"
];

export const ComoUmNino = [
	//_________________________________
    "Intr. D C9 G D C9 G",
    " ",
    "D              C9        G",
    "Como el río de vida que brota del",
    "              D   C9 G",
    "corazón de un volcán",
    "D                 C9               G",
    "Y las aguas cristalinas de las montañas",
    "           D   C9 G",
    "que bajan al mar",
    "C9              G/B",
    " Al compás del sonido del viento",
    "Am               C     D",
    " que recorre mi tierra.",
    "       G",
    "Que expresen mis labios",
    "    D",
    "la voz de mi alma",
    "   B7             Em",
    "Un canto de gozo del que me habita,",
    "      C",
    "Que expresen mis labios",
    "   Am",
    "la voz de mi alma",
    "B7                           Em",
    " Un canto de gozo fuerte y vibrante",
    "             C G/B D (C9 G/B D 2X)",
    "del que me habita.",
    " ",
    "C9            G/B           D",
    " Al haz de su luz las aves cantan,",
    "C9         G/B           D",
    "Los que conocieron el dolor,",
    "en Él descansan.",
    "B7                       Em",
    "¿Has visto el sol en el horizonte,",
    "C         G/B       D",
    "el atardecer en el mar?",
    "         C9      G/B",
    "Él, que todo ha creado,",
    "     Am     D        C9 G/B D",
    "Para Él mi voz ha de cantar.",
    " ",
    "G                D",
    "/: Reiré como un niño reiré,",
    "B7            Em",
    " Subiré a sus brazos subiré,",
    "    C              Am",
    "Mis ojos abriré colmados de su Amor.",
    "B7",
    " Lloraré de alegría",
    "      Em",
    "al encontrar a mi Padre,",
    "   C9      G/B",
    "cansado de juegos",
    "      Am      D       C9  G/B D",
    "dormiré arrullado con su voz :/",
    "       G",
    "con su voz."
];

export const Confia = [
	//_________________________________
    "  A           D                    A",
    "Hoy se abre entera la puerta hacia Dios",
    "        D                E",
    "habla clara y brillante tu voz",
    "      D                 A",
    "veo pleno el camino a seguir.",
    " A            D                  A",
    "Hoy tiene un nuevo sentido el luchar",
    "          D               E",
    "ya ni el miedo me impide amar",
    "         D               F#m",
    "y en tu fuerza aprendí a seguir.",
    " ",
    " D          E",
    "Quiero recorrer tus pasos",
    " Bm/C#       C#7",
    "y aferrarme de tu mano",
    "F#m        F               A",
    "llévame donde pueda ser testigo",
    "       B/D#       D",
    "de tu fuego y sentir",
    "        Dm            A/E          E",
    "como escribes con mis manos tu canción.",
    " ",
    " A         D   E  F#m  E D",
    "Hoy mi corazón con fí i a",
    " Bm     A/C#    D            G       A",
    "no hay amor más firme que el tuyo Señor.",
    " Bm/G#         F#m                  B",
    "Pues yo sé que mi descanso está en Ti",
    "   Bm         A/C#      D",
    "y no habrá tormenta que no me encuentre",
    "  E      F#m    B",
    "alerta y vivir,",
    " ",
    "FINAL:",
    "    Bm       A/C#",
    "pues vives conmigo",
    "     D      E       A   D",
    "y estás presente en mí.",
    " ",
    "Hoy cuando el alma no quiere luchar",
    "y el cansancio me va a derrotar",
    "tu mirada me mantiene en pie.",
    "Es el latido de tu corazón",
    "que se funde en mi pecho Señor,",
    "tu silencio acompaña la paz.",
    "Y si logro ver tu sombra mi alma en tu luz se asombra,",
    "óyeme, cantaré por ti",
    "a oídos que no escuchan",
    "que estás cada vez que vibra fuerte el corazón."
];

export const CristoQueroSerInstrumento = [
	//_________________________________
    " D                          Bm",
    "Cristo, quero ser instrumento",
    "                         G Em     A G A",
    "de tua paz e do teu infinito amor.",
    " D                    Bm",
    "Onde houver ódio e rancor,",
    "                  G",
    "que eu leve a concórdia,",
    "Em              A A7",
    " que eu leve o amor.",
    " G                  A",
    "Onde há ofensa que dói,",
    "                 F#m",
    "que eu leve o perdão,",
    "                   G",
    "Onde houver a discórdia",
    "                 Em A7     D  G A", 
    "que eu leve a união e Tua paz.",
    " ",
    "Mesmo que haja um só coração, que duvide do bem, do amor e do céu,",
    "quero com firmeza anunciar a palavra que traz a clareza da fé.",
    " ",
    "Onde houver erro Senhor, que eu leve a verdade, fruto da tua luz.",
    "Onde encontrar desespero, que eu leve a esperança do teu nome, Jesus.",
    " ",
    "Onde eu encontrar um irmão a chorar de tristeza sem ter voz e nem vez",
    "Quero bem no seu coração semear alegria pra florir gratidão.",
    " ",
    "Mestre, que eu saiba amar, compreender, consolar e dar sem receber.",
    "Quero sempre mais perdoar, trabalhar na conquista e vitória da paz."
];

export const DeCirene = [
	//_________________________________
    "  E    F#m*        A9        E",
    "Venías por aquel camino hacia mí.",
    "        F#m*         A9            E",
    "En realidad nunca pensé cruzarte así.",
    "         F#m*         A9",
    "Bajo esa cruz la majestad",
    "    B7         E F#m*  A9  E",
    "del Hijo de David.",
    " ",
    "Todo el pecado y la soberbia original,",
    "sobre tus hombros a mi lado pasarán.",
    "Y de repente el Salvador cayó y no sé si es que te puedo ayudar.",
    " ",
    "B     E6      E6/A        E/A",
    " Ayúdame a cargar tanto dolor,",
    "ayúdame necesitan de tu corazón.",
    "Pero Señor no puedo, mira mi debilidad.",
    "Ayúdame y verás cómo la hago mía,",
    " E/A",
    "y mía es tu capacidad de amar.",
    " ",
    "Los brazos se entrelazan para caminar,",
    "tu aliento lastimado me va haciendo callar.",
    "Y aunque nos griten voy entrando más, en nuestra intimidad.",
    " ",
    "¿Qué culpa hay en el hombre, qué merezca tu don?",
    "¿Acaso dar la vida transforma un corazón?",
    "Cuando llegamos a la cima entendí, que es por Amor.",
    " ",
    "F#m* = 044200 B = X024400 E6 = 042400 E/A = X02450"
];

export const Dejate = [
	//_________________________________
    "                   D",
    "Hace ya tiempo que comprendí",
    "G                          D",
    " Tú me buscaste en todas partes,",
    "Bm                           Em",
    " la llama que un día empezó a fallar,",
    "G                       A A7",
    " Tú no dejaste se apagase.",
    " ",
    "Yo no comprendo y digo que será,",
    "será que estaba equivocado,",
    "y he descubierto que este loco está,",
    "de amor muriendo porque le ame.",
    " ",
    "Yo no he querido saber más",
    "de la locura que me late,",
    "pero la fiebre quiere regresar",
    "y El no dejó de predicarme.",
    " ",
    "Y Tú me dices:",
    "D  A   G           A        Bm F#m",
    "Déjate, que te consuma este fuego",
    "G         A             Bm F#m",
    " no apagues ya más esta hoguera",
    " ",
    "G            Em            A  A7",
    " que si no hay fuego no habrá luz.",
    "D  A   G              A",
    "Créeme, que estoy clavado",
    "         Bm F#m",
    "porque te amo",
    "G        A            Bm F#m",
    " no encontrarás en otro lado,",
    "G             A          D",
    " quien quiera ya morir por ti.",
    " ",
    "No tengas miedo, no te dejaré,",
    "las veces que tú me reclames,",
    "yo gozo al ver que quieres regresar,",
    "déjame que yo te levante”.",
    " ",
    "Señor, no ves que quiero regresar,",
    "pero me pesa mi pasado,",
    "acaso pides lo que no sé dar,",
    "el tiempo me ha secado el alma.",
    " ",
    "Tanto he besado el suelo, no lo ves,",
    "mis manos se han cerrado tanto.",
    "“No te preocupes, te rescataré,",
    "mi vida cambio por la tuya”:",
    " ",
    "Final:",
    "D  A   G           A       Bm F#m",
    "Déjate, que te consuma este fuego,",
    "G         A             Bm F#m",
    "no apagues ya más esta hoguera",
    "G             Gm          D",
    "que yo encendí en tu corazón"
];

export const DespuesDeCaer = [
	//_________________________________
    "G            D       Em",
    "Una vez, te prometí que",
    "                C9     D     G",
    "no volvería a caer de nuevo ahí.",
    "G             D            Em",
    "Y parece que no lo cumplí aquí",
    "             C9     D      C",
    "me tienes estoy de nuevo aquí.",
    "D               C",
    "Hubiese sido mejor",
    "            G         D",
    "no comprometerme con nada,",
    "                 C",
    "de esa manera la culpa",
    "      G         D",
    "no sería tan pesada",
    " Am7  Bm  C A7         G  A# Am7 D7",
    "¿Cómo levantar mi corazón?",
    " ",
    " G          D/F#        Em         C9  D",
    "Madre no quisiera que Jesús me vea así.",
    "Oh Jesús yo quise ser perfecto para ti.",
    "Me siento tan pequeño pero mi orgullo no se quiere arrepentir.",
    "No hay forma de que mi miseria quieras preferir.",
    " ",
    "Aquella vez Yo te prometí que siempre volvería a creer de nuevo en ti.",
    "Y parece que fue así, nunca me he ido, estoy como antes aquí.",
    "Ha sido mejor que te tropieces y te caigas,",
    "de esa manera entendiste que tus glorias nos distancian,",
    "¡Déjame levantar tu corazón!",
    " ",
    "Madre no quisiera verlo tan lejos de mi.",
    "Nunca quise que merezcas mi Amor por ti.",
    "Yo te he dado una puerta cada vez que quisiste venir.",
    " G            D/F#",
    "Son pequeñas, no te asustes,",
    "Em",
    " sólo siendo niño,",
    " A7                Am7",
    "sólo siendo niño, sólo siendo niño",
    "G/B C D G",
    "podrás reír."
];

export const Entrega = [
	//_________________________________
    "Em",
    "Cuando siento tu amor",
    "  D/F#   Em      D/F#",
    "tocar mi corazón",
    "Em",
    "Cuando veo en tu luz",
    "   D/F#       C",
    "la fuerza de tu calor",
    "Am                      D",
    "No hay más respuesta posible",
    "          G Am B7",
    "que entregar todo lo que hay en mí.",
    "Em   D     C     Am",
    "Tómame Señor y seré como un niño ante ti",
    "      D        B7",
    "Seré tuyo como acto de amor",
    " ",
    "    Em        Bm              Em",
    "Déjame que te ame con todo mi ser",
    "        Bm                 D",
    "y en silencio puedas entender",
    "         Am                    F",
    "Lo que entrega mi amor cuando veo",
    "    C      Am         D",
    "en ti esa cruz de dolor",
    "     Em         Bm                 Em",
    "Y sabrás que quiero desangrarme por ti",
    "      Bm                 C",
    "Si me tomas la mano y me usas",
    "             F",
    "hoy para vencer",
    "      C        Am         D",
    "Y clavar tu bandera y tu voz",
    "               Am G/B C Am G/B C",
    "sin dudar ni temer",
    "       B7       Em   D/F#",
    "Sin dudar ni temer",
    " ",
    "Em                      D/F#",
    "Aunque no sea mi amor igual",
    "       Em          D/F#",
    "al que tú me das",
    "Em                    D/F#",
    "Toma mi corazón si en algo",
    "       C",
    "sirve a tu plan",
    "Am             D            G",
    "Y si me necesitaras por pequeña",
    "     Am     B7  Em  D      C",
    "que sea mi voz, pídeme Señor",
    "Am",
    "Que mi vida se entregue a tu amor.",
    "      D         B7",
    "Y valiente moriré para ti."
];